Repository seed4j/seed4j, pull requests merged in 2022-09, with the labels that each got.

#3378 Merge bean validation test in spring boot
  src/main/java/tech/jhipster/lite/generator/server/springboot/beanvalidationtest/application/BeanValidationTestApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/beanvalidationtest/domain/BeanValidationTestModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/beanvalidationtest/infrastructure/primary/BeanValidationTestModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootCoreModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/feature/infrastructure/primary/DummyFeatureModuleConfiguration.java
  src/main/resources/generator/server/springboot/core/BeanValidationAssertions.java.mustache
  src/main/resources/generator/server/springboot/core/BeanValidationTest.java.mustache
  src/test/features/bean-validation-test.feature
  src/test/java/tech/jhipster/lite/generator/server/springboot/beanvalidationtest/domain/BeanValidationTestModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootCoreModuleFactoryTest.java
  tests-ci/generate.sh
Labels: server: spring boot, area: refactoring

#3345 Pagination modules
  src/main/java/tech/jhipster/lite/generator/server/pagination/domainmodel/application/PaginationDomainApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/pagination/domainmodel/domain/PaginationDomainModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/pagination/domainmodel/infrastructure/primary/PaginationDomainModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/pagination/domainmodel/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/pagination/jpa/application/JpaPaginationModuleApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/pagination/jpa/domain/JpaPaginationModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/pagination/jpa/infrastructure/primary/JpaPaginationModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/pagination/jpa/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/pagination/rest/application/RestPaginationModuleApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/pagination/rest/domain/RestPaginationModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/pagination/rest/infrastructure/primary/RestPaginationModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/pagination/rest/package-info.java
  src/main/resources/generator/server/pagination/domain/main/AppPage.java.mustache
  src/main/resources/generator/server/pagination/domain/main/AppPageable.java.mustache
  src/main/resources/generator/server/pagination/domain/package-info.java.mustache
  src/main/resources/generator/server/pagination/domain/test/AppPageTest.java.mustache
  src/main/resources/generator/server/pagination/domain/test/AppPageableTest.java.mustache
  src/main/resources/generator/server/pagination/domain/test/AppPagesFixture.java.mustache
  src/main/resources/generator/server/pagination/jpa/AppPages.java.mustache
  src/main/resources/generator/server/pagination/jpa/AppPagesTest.java.mustache
  src/main/resources/generator/server/pagination/jpa/jpa-pages.md.mustache
  src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
  src/main/resources/generator/server/pagination/rest/main/RestAppPageable.java.mustache
  src/main/resources/generator/server/pagination/rest/rest-pagination.md.mustache
  src/main/resources/generator/server/pagination/rest/test/RestAppPageTest.java.mustache
  src/main/resources/generator/server/pagination/rest/test/RestAppPageableTest.java.mustache
  src/test/features/pagination.feature
  src/test/java/tech/jhipster/lite/generator/server/pagination/domainmodel/domain/PaginationDomainModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/pagination/jpa/domain/JpaPaginationModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/pagination/rest/domain/RestPaginationModuleFactoryTest.java
  tests-ci/generate.sh
Labels: area: feature request :bulb:, server: spring boot

#3383 Remove dependency to bean validation test
  src/main/java/tech/jhipster/lite/generator/server/pagination/rest/infrastructure/primary/RestPaginationModuleConfiguration.java
Labels: area: bug :bug:, server: spring boot

#3377 Remove bootstrap
  package-lock.json
  package.json
  src/main/glyph/config.json
  src/main/glyph/css/jhlite-icons-codes.css
  src/main/glyph/css/jhlite-icons-embedded.css
  src/main/glyph/css/jhlite-icons-ie7-codes.css
  src/main/glyph/css/jhlite-icons-ie7.css
  src/main/glyph/css/jhlite-icons.css
  src/main/glyph/font/jhlite-icons.eot
  src/main/glyph/font/jhlite-icons.svg
  src/main/glyph/font/jhlite-icons.ttf
  src/main/glyph/font/jhlite-icons.woff
  src/main/glyph/font/jhlite-icons.woff2
  src/main/style/molecule/_molecule.scss
  src/main/style/molecule/molecule.pug
  src/main/style/molecule/toast/_toast.scss
  src/main/style/molecule/toast/toast.code.pug
  src/main/style/molecule/toast/toast.md
  src/main/style/molecule/toast/toast.mixin.pug
  src/main/style/molecule/toast/toast.render.pug
  src/main/style/template/_template.scss
  src/main/style/template/template.pug
  src/main/style/template/toast-overlay/_toast-overlay.scss
  src/main/style/template/toast-overlay/toast-overlay.code.pug
  src/main/style/template/toast-overlay/toast-overlay.md
  src/main/style/template/toast-overlay/toast-overlay.mixin.pug
  src/main/style/template/toast-overlay/toast-overlay.render.pug
  src/main/style/token/_colors.scss
  src/main/webapp/app/common/primary/toast/Toast.component.ts
  src/main/webapp/app/common/primary/toast/Toast.vue
  src/main/webapp/app/main.ts
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
  src/main/webapp/app/module/primary/landscape/Landscape.html
  src/main/webapp/app/module/primary/project-actions/ProjectActions.component.ts
  src/main/webapp/app/module/primary/project-actions/ProjectActions.html
  src/test/javascript/spec/common/primary/toast/Toast.spec.ts
Labels: generator: internal, area: refactoring

#3390 Sonar: ignore WindowApplicationListener.ts
  sonar-project.properties
Labels: area: enhancement :wrench:, generator: internal

#3391 Remove Heroku
  README.md
  app.json
  release.sh
  system.properties
Labels: area: documentation:books:, generator: internal, area: refactoring

#3392 Allow to customize Tikui cache folder
  .gitignore
  package-lock.json
  package.json
Labels: area: enhancement :wrench:, generator: internal

#3393 Add buttons
  src/main/style/atom/_atom.scss
  src/main/style/atom/atom.pug
  src/main/style/atom/button/_button.scss
  src/main/style/atom/button/button.code.pug
  src/main/style/atom/button/button.md
  src/main/style/atom/button/button.mixin.pug
  src/main/style/atom/button/button.render.pug
  src/main/style/organism/_organism.scss
  src/main/style/organism/organism.pug
  src/main/style/organism/vertical-space/_vertical-space.scss
  src/main/style/organism/vertical-space/vertical-space.code.pug
  src/main/style/organism/vertical-space/vertical-space.md
  src/main/style/organism/vertical-space/vertical-space.mixin.pug
  src/main/style/organism/vertical-space/vertical-space.render.pug
  src/main/style/token/_colors.scss
  src/main/style/token/_size.scss
  src/main/style/token/_token.scss
  src/main/webapp/app/module/primary/landscape/Landscape.html
  src/main/webapp/app/module/primary/project-actions/ProjectActions.html
Labels: area: bug :bug:, generator: internal

#3448 Add module creation documentation
  CONTRIBUTING.md
  documentation/module-creation.md
Labels: area: documentation:books:, generator: internal

#3447 Switch docker compose command
  CONTRIBUTING.md
  README.md
  src/main/java/tech/jhipster/lite/generator/server/sonar/domain/SonarModulesFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/README.md
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/domain/MongoDbModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/sqlcommon/domain/SQLCommonModuleBuilder.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/common/domain/AuthenticationModulesFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/domain/OAuth2ModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/consul/README.md
  src/main/resources/generator/server/sonar/sonar.md.mustache
  src/main/resources/generator/server/springboot/broker/kafka/apache-kafka.md.mustache
  src/main/resources/generator/server/springboot/database/mariadb/mariadb.md.mustache
  src/main/resources/generator/server/springboot/database/mongodb/mongodb.md.mustache
  src/main/resources/generator/server/springboot/database/mssql/mssql.md.mustache
  src/main/resources/generator/server/springboot/database/mysql/mysql.md.mustache
  src/main/resources/generator/server/springboot/database/postgresql/postgresql.md.mustache
  src/test/java/tech/jhipster/lite/generator/server/sonar/domain/SonarModulesFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/domain/MongoDbModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/domain/OAuth2ModuleFactoryTest.java
Labels: area: documentation:books:, theme: docker :whale:

#3476 Priorize init module
  src/main/java/tech/jhipster/lite/module/domain/JHipsterSlug.java
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscape.java
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModuleSlugTest.java
  src/test/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeTest.java
Labels: generator: internal

#3475 Fix local payload handling
  tests-ci/generate.sh
Labels: area: bug :bug:, generator: CI

#3478 Upgrade Angular 14.2.1
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#3479 Svelte - Upgrade Jest
  src/main/resources/generator/dependencies/svelte/package.json
Labels: area: dependencies, client: svelte

#3483 Svelte: Upgrade sveltejs/kit 1.0.0-next.480
  src/main/resources/generator/client/svelte/.eslintrc.cjs
  src/main/resources/generator/client/svelte/svelte.config.js
  src/main/resources/generator/dependencies/svelte/package.json
Labels: area: dependencies, client: svelte

#3477 Refactor module action component with slot
  src/main/webapp/app/module/primary/landscape/Landscape.html
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.html
  src/main/webapp/app/module/primary/project-actions/ProjectActions.html
Labels: generator: internal, area: refactoring

#3481 Add timeout to toast
  src/main/webapp/app/common/primary/timeout/Timeout.ts
  src/main/webapp/app/common/primary/toast/Toast.component.ts
  src/main/webapp/app/main.ts
  src/test/javascript/spec/common/primary/timeout/Timeout.fixture.ts
  src/test/javascript/spec/common/primary/timeout/Timeout.spec.ts
  src/test/javascript/spec/common/primary/toast/Toast.spec.ts
Labels: area: bug :bug:, generator: internal

#3516 Add choice in readme
  README.md
  documentation/JHLiteChoice.png
Labels: area: documentation:books:, generator: internal

#3542 Add missing meta information in pom.xml of JHLite
  pom.xml
Labels: area: enhancement :wrench:, generator: internal, theme: maven

#3543 Add JHipster URL
  README.md
  documentation/jhlite-choice.png
Labels: area: documentation:books:, generator: internal

#3550 Display sponsors and contributing sections in README.md [skip ci]
  README.md
Labels: area: documentation:books:

#3546 Add config to deploy to Maven Central
  pom.xml
Labels: area: enhancement :wrench:, generator: internal

#3533 Consul: fix link to spring-boot-actuator
  src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/configclient/infrastructure/primary/SpringCloudConfigModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/consul/infrastructure/primary/ConsulModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/eureka/infrastructure/primary/EurekaModuleConfiguration.java
Labels: area: bug :bug:, server: spring boot, theme: microservices

#3537 Add field
  src/main/style/atom/_atom.scss
  src/main/style/atom/atom.pug
  src/main/style/atom/button/_button.scss
  src/main/style/atom/input/_input.scss
  src/main/style/atom/input/input-text/_input-text.scss
  src/main/style/atom/input/input-text/input-text.code.pug
  src/main/style/atom/input/input-text/input-text.md
  src/main/style/atom/input/input-text/input-text.mixin.pug
  src/main/style/atom/input/input-text/input-text.render.pug
  src/main/style/atom/input/input.pug
  src/main/style/atom/label/_label.scss
  src/main/style/atom/label/label.code.pug
  src/main/style/atom/label/label.md
  src/main/style/atom/label/label.mixin.pug
  src/main/style/atom/label/label.render.pug
  src/main/style/molecule/_molecule.scss
  src/main/style/molecule/field/_field.scss
  src/main/style/molecule/field/field.code.pug
  src/main/style/molecule/field/field.md
  src/main/style/molecule/field/field.mixin.pug
  src/main/style/molecule/field/field.render.pug
  src/main/style/molecule/molecule.pug
  src/main/style/quark/_quark.scss
  src/main/style/token/_colors.scss
  src/main/webapp/app/module/primary/landscape/Landscape.html
  src/main/webapp/app/module/primary/module-properties-form/ModulePropertiesForm.html
  src/main/webapp/app/module/primary/module-properties-form/ModulePropertiesForm.vue
Labels: area: enhancement :wrench:, generator: internal

#3548 Use default property value for blank value
  src/main/java/tech/jhipster/lite/module/domain/properties/JHipsterModuleParameters.java
  src/main/java/tech/jhipster/lite/module/domain/properties/JHipsterModuleProperties.java
  src/test/java/tech/jhipster/lite/module/domain/properties/JHipsterModulePropertiesTest.java
Labels: area: enhancement :wrench:, generator: internal

#3535 Move Bean Validation Test to Spring MVC
  src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootCoreModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/application/SpringBootMvcApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/domain/SpringBootMvcsModulesFactory.java
  src/main/resources/generator/server/springboot/mvc/web/test/BeanValidationAssertions.java.mustache
  src/main/resources/generator/server/springboot/mvc/web/test/BeanValidationTest.java.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootCoreModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/web/domain/SpringBootMvcsModulesFactoryTest.java
Labels: area: bug :bug:, server: spring boot

#3549 Fix horizontal scrollbar in actions panel
  src/main/webapp/app/module/primary/module-properties-form/ModulePropertiesForm.vue
Labels: area: bug :bug:, generator: internal

#3545 Disable format button without Prettier applied
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
  src/main/webapp/app/module/primary/landscape/Landscape.html
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.html
  src/main/webapp/app/module/primary/project-actions/ProjectActions.component.ts
  src/main/webapp/app/module/primary/project-actions/ProjectActions.html
  src/test/javascript/spec/module/domain/Modules.fixture.ts
  src/test/javascript/spec/module/domain/landscape/Landscape.fixture.ts
  src/test/javascript/spec/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/javascript/spec/module/primary/project-actions/ProjectActionsComponent.spec.ts
  src/test/javascript/spec/module/secondary/RestModulesRepository.spec.ts
Labels: area: enhancement :wrench:, generator: internal

#3576 Add maven-javadoc-plugin and maven-source-plugin
  pom.xml
  tests-ci/start.sh
Labels: area: enhancement :wrench:, generator: internal

#3581 Update badges in README [ci skip]
  README.md
Labels: area: documentation:books:, generator: internal

#3580 Upgrade liquibase
  src/main/resources/generator/dependencies/pom.xml
  src/main/resources/generator/server/springboot/dbmigration/liquibase/main/LiquibaseConfiguration.java.mustache
Labels: server: spring boot, area: dependencies, theme: database migration

#3583 Sonatype: auto close staging repository
  pom.xml
Labels: area: enhancement :wrench:, generator: internal

#3584 Ignore non lts node versions
  .github/dependabot.yml
Labels: generator: internal, area: dependencies

#3590 Close FileSystemNpmVersion visibility
  src/main/java/tech/jhipster/lite/npm/infrastructure/secondary/FileSystemNpmVersions.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/TestJHipsterModules.java
  src/test/java/tech/jhipster/lite/npm/infrastructure/secondary/NpmVersionsFixture.java
Labels: generator: internal, area: refactoring

#3599 Fix Assert javadoc format
  src/main/java/tech/jhipster/lite/error/domain/Assert.java
  src/main/resources/generator/server/javatool/base/Assert.java.mustache
Labels: area: bug :bug:, server: java

#3600 Build normal jar for deployment
  pom.xml
Labels: area: enhancement :wrench:, generator: internal

#3603 Remove unused needle
  src/main/resources/config/application.properties
Labels: area: enhancement :wrench:, generator: internal

#3602 Modules deactivation
  src/main/java/tech/jhipster/lite/generator/server/springboot/banner/infrastructure/primary/BannerModuleConfiguration.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModuleTags.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterHiddenResourcesProperties.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterModulesResourcesConfiguration.java
  src/main/resources/config/application.properties
  src/main/resources/generator/server/springboot/custom-jhlite/module-creation.md.mustache
  src/test/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResourceFixture.java
  src/test/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterModulesTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterModulesResourcesConfigurationTest.java
  tests-ci/generate.sh
Labels: area: enhancement :wrench:, generator: internal

#3633 Consul: fix shared security conflict between JWT and OAuth2
  src/main/resources/generator/server/springboot/springcloud/consul/docker/application.config.yml.mustache
Labels: area: bug :bug:, theme: security, server: spring boot

#3635 Upgrade Angular 14.2.3
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#3641 Add pug and style linters
  .github/workflows/github-actions.yml
  .github/workflows/release.yml
  .lintstagedrc.js
  .pug-lintrc.json
  .stylelintrc.json
  README.md
  package-lock.json
  package.json
  src/main/style/atom/button/_button.scss
  src/main/style/atom/input/input-text/_input-text.scss
  src/main/style/molecule/field/_field.scss
  src/main/style/molecule/toast/_toast.scss
  src/main/style/organism/vertical-space/_vertical-space.scss
  src/main/style/quark/_quark.scss
  src/main/style/template/toast-overlay/_toast-overlay.scss
  src/main/style/token/_colors.scss
Labels: area: enhancement :wrench:, generator: internal

#3648 Ehcache rename to cache
  src/main/java/tech/jhipster/lite/generator/server/springboot/cache/ehcache/infrastructure/primary/EHCacheModulesConfiguration.java
  src/test/features/ehcache.feature
  tests-ci/generate.sh
Labels: server: spring boot, theme: cache, area: refactoring

#3644 Deploy test-jar when releasing
  pom.xml
Labels: area: enhancement :wrench:, generator: internal

#3645 Fix lintstagedrc when adding prettier without front part
  src/main/resources/generator/prettier/.lintstagedrc.js
  src/test/resources/generator/common/.lintstagedrc.js
  src/test/resources/projects/files/.lintstagedrc.js
Labels: area: bug :bug:, theme: init

#3649 Add JHLite test dependency
  documentation/module-creation.md
  src/main/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/javabuild/command/AddJavaDependency.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/JavaDependency.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/JavaDependencyClassifier.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/JavaDependencyType.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/FileSystemProjectJavaDependenciesRepository.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/MavenCommandHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/MavenType.java
  src/main/resources/generator/dependencies/pom.xml
  src/main/resources/generator/server/springboot/custom-jhlite/module-creation.md.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModulesFixture.java
  src/test/java/tech/jhipster/lite/module/domain/javadependency/DirectJavaDependencyTest.java
  src/test/java/tech/jhipster/lite/module/domain/javadependency/JavaDependencyClassifierTest.java
  src/test/java/tech/jhipster/lite/module/domain/javadependency/JavaDependencyMangementTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModulesRepositoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/FileSystemProjectJavaDependenciesRepositoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/MavenCommandHandlerTest.java
  src/test/resources/projects/maven/pom.xml
Labels: area: enhancement :wrench:, generator: internal

#3651 React: Upgrade Jest 29
  src/main/resources/generator/dependencies/react/package.json
Labels: area: dependencies, client: react

#3652 React: clean code generated
  src/main/java/tech/jhipster/lite/generator/client/react/security/jwt/domain/ReactJwtModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/client/react/security/jwt/domain/ReactJwtModuleFactoryTest.java
Labels: area: enhancement :wrench:, client: react

#3666 Add eslint config to .lintstagedrc.js
  src/main/java/tech/jhipster/lite/generator/client/common/domain/ClientsModulesFactory.java
  src/test/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterModulesAssertions.java
  src/test/resources/projects/init/.lintstagedrc.js
Labels: area: enhancement :wrench:, theme: client

#3682 Move technical exception package
  src/main/java/tech/jhipster/lite/error/infrastructure/primary/BadRequestAlertException.java
  src/main/java/tech/jhipster/lite/error/infrastructure/primary/ErrorConstants.java
  src/main/java/tech/jhipster/lite/error/infrastructure/primary/ExceptionTranslator.java
  src/main/java/tech/jhipster/lite/error/infrastructure/primary/FieldErrorDTO.java
  src/main/java/tech/jhipster/lite/error/infrastructure/primary/HeaderUtil.java
  src/main/java/tech/jhipster/lite/error/infrastructure/primary/ProblemConfiguration.java
  src/test/java/tech/jhipster/lite/error/infrastructure/primary/BadRequestAlertExceptionTest.java
  src/test/java/tech/jhipster/lite/error/infrastructure/primary/ExceptionTranslatorIT.java
  src/test/java/tech/jhipster/lite/error/infrastructure/primary/ExceptionTranslatorTestController.java
  src/test/java/tech/jhipster/lite/error/infrastructure/primary/FieldErrorDTOTest.java
  src/test/java/tech/jhipster/lite/error/infrastructure/primary/HeaderUtilTest.java
Labels: generator: internal, area: refactoring

#3683 Move CORS configuration to dedicated package
  src/main/java/tech/jhipster/lite/security/infrastructure/primary/CorsFilterConfiguration.java
  src/main/java/tech/jhipster/lite/security/infrastructure/primary/CorsProperties.java
  src/main/java/tech/jhipster/lite/security/package-info.java
  src/test/java/tech/jhipster/lite/security/infrastructure/primary/CorsFilterConfigurationIT.java
Labels: theme: security, server: spring boot, area: refactoring

#3686 Delete technical package
  src/main/java/tech/jhipster/lite/documentation/infrastructure/primary/SpringdocConfiguration.java
  src/main/java/tech/jhipster/lite/documentation/package-info.java
  src/main/java/tech/jhipster/lite/frontend/infrastructure/primary/RedirectionResource.java
  src/main/java/tech/jhipster/lite/frontend/package-info.java
  src/main/java/tech/jhipster/lite/technical/package-info.java
  src/test/java/tech/jhipster/lite/documentation/infrastructure/primary/SpringDocSteps.java
  src/test/java/tech/jhipster/lite/frontend/infrastructure/primary/RedirectionResourceIT.java
  src/test/java/tech/jhipster/lite/projectfolder/infrastructure/primary/ForcedProjectFolderPrefixIntTest.java
Labels: generator: internal, area: refactoring

#3690 Delete modules readme files
  src/main/java/tech/jhipster/lite/generator/buildtool/gradle/README.md
  src/main/java/tech/jhipster/lite/generator/buildtool/maven/README.md
  src/main/java/tech/jhipster/lite/generator/client/angular/core/README.md
  src/main/java/tech/jhipster/lite/generator/client/angular/security/oauth2/README.md
  src/main/java/tech/jhipster/lite/generator/client/tools/playwright/README.md
  src/main/java/tech/jhipster/lite/generator/infinitest/README.md
  src/main/java/tech/jhipster/lite/generator/init/README.md
  src/main/java/tech/jhipster/lite/generator/prettier/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/base/README.md
  src/main/java/tech/jhipster/lite/generator/server/springboot/banner/README.md
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/README.md
  src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/mongock/README.md
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/flyway/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/zalandoproblem/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/consul/README.md
  src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/gateway/README.md
  src/main/java/tech/jhipster/lite/generator/server/springboot/technicaltools/actuator/README.md
  src/main/java/tech/jhipster/lite/generator/server/springboot/webflux/web/README.md
  src/main/java/tech/jhipster/lite/generator/setup/gitpod/README.md
Labels: area: documentation:books:, generator: internal

#3552 Redefining ArchUnit tests
  pom.xml
  src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocoauth/infrastructure/primary/SpringdocOauth2ModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/hivemq/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/cache/caffeine/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/cache/hazelcast/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/cache/infinispan/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/cache/memcached/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/cache/redis/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/cassandra/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/couchbase/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/oracle/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/search/elasticsearch/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/webflux/security/jwt/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/webflux/security/oauth2/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/webflux/springdoc/package-info.java
  src/main/resources/generator/dependencies/pom.xml
  src/main/resources/generator/server/javatool/arch/HexagonalArchTest.java.mustache
  src/test/java/tech/jhipster/lite/HexagonalArchTest.java
Labels: area: enhancement :wrench:, generator: internal, theme: tests

#3693 Ignore SonarQube generics name rule
  src/main/resources/generator/server/sonar/sonar-project.properties.mustache
Labels: area: bug :bug:, server: java

#3695 Ignore generics name in SonarQube fullstack
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
Labels: area: bug :bug:, server: java

#3694 MongoDB: fix start app
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/domain/MongoDbModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/domain/MongoDbModuleFactoryTest.java
Labels: area: bug :bug:, server: spring boot, theme: database

#3691 Angular, React, Vue modules depend on Prettier
  src/main/java/tech/jhipster/lite/generator/client/angular/core/infrastructure/primary/AngularCoreModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/react/core/infrastructure/primary/ReactCoreModulesConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/vue/core/infrastructure/primary/VueModuleConfiguration.java
  src/test/features/angular-health.feature
  src/test/features/angular-jwt.feature
  src/test/features/angular-oauth2.feature
  src/test/features/react.feature
  src/test/features/vue.feature
Labels: area: enhancement :wrench:, client: vue, client: angular, client: react

#3706 CI: start generated applications and test health check
  .github/workflows/github-actions.yml
  tests-ci/start.sh
  tests-ci/start_docker_compose.sh
Labels: area: enhancement :wrench:, generator: CI

#3707 Reduce logs during tests
  src/test/resources/logback.xml
Labels: area: enhancement :wrench:, generator: internal

#3708 Restore prettier on root files
  .lintstagedrc.js
  README.md
  package.json
Labels: area: enhancement :wrench:, generator: internal

#3710 remove deprecated SpringPhysicalNamingStrategy
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/sqlcommon/domain/SQLCommonModuleBuilder.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/mariadb/domain/MariaDBModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/mssql/domain/MsSQLModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQLModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/postgresql/domain/PostgresqlModuleFactoryTest.java
Labels: area: enhancement :wrench:, server: spring boot, theme: database

#3728 Upgrade Angular 14.2.4
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#3729 Angular: defaultProject option is deprecated
  src/main/resources/generator/client/angular/core/angular.json
Labels: area: refactoring, client: angular

#3730 Angular: clean code generated
  src/main/java/tech/jhipster/lite/generator/client/angular/security/jwt/domain/AngularJwtModuleFactory.java
  src/main/resources/generator/client/angular/core/src/main/webapp/index.html.mustache
Labels: area: refactoring, client: angular

#3747 Rework header
  src/main/style/atom/logo/_logo.scss
  src/main/style/molecule/icon-text/_icon-text.scss
  src/main/style/molecule/icon-text/icon-text.code.pug
  src/main/style/molecule/icon-text/icon-text.mixin.pug
  src/main/style/molecule/nav/_nav.scss
  src/main/style/token/_breakpoint.scss
  src/main/webapp/app/common/primary/header/Header.vue
Labels: area: enhancement :wrench:, generator: internal

#3744 Replace parent by dependency management
  pom.xml
Labels: area: enhancement :wrench:, generator: internal

#3749 Move commit button
  src/main/webapp/app/module/primary/module-properties-form/ModulePropertiesForm.html
Labels: area: enhancement :wrench:, generator: internal
