Repository seed4j/seed4j, pull requests merged in 2022-11, with the labels that each got.

#4193 add more details on generating local builds in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area: documentation:books:, generator: internal

#4198 React: Translate French texts into English
  src/main/resources/generator/client/react/src/main/webapp/app/login/primary/loginForm/index.tsx.mustache
  src/main/resources/generator/client/react/src/main/webapp/app/login/primary/loginModal/index.tsx.mustache
  src/main/resources/generator/client/react/src/test/javascript/spec/login/primary/loginForm/index.test.tsx.mustache
  src/main/resources/generator/client/react/src/test/javascript/spec/login/primary/loginModal/index.test.tsx.mustache
Labels: area: enhancement :wrench:, client: react

#4089 Add chip atom
  src/main/style/atom/_atom.scss
  src/main/style/atom/atom.pug
  src/main/style/atom/chip/_chip.scss
  src/main/style/atom/chip/chip.code.pug
  src/main/style/atom/chip/chip.md
  src/main/style/atom/chip/chip.mixin.pug
  src/main/style/atom/chip/chip.render.pug
  src/main/style/token/_animation.scss
  src/main/style/token/_colors.scss
  src/main/style/token/_fonts.scss
  src/main/style/token/_token.scss
  src/main/webapp/app/module/primary/landscape-module/LandscapeModule.html
  src/main/webapp/app/module/primary/landscape-module/LandscapeModule.vue
Labels: area: enhancement :wrench:, generator: internal, $$ bug-bounty $$, $200

#4226 Upgrade npm version
  pom.xml
Labels: area: triage

#4225 Add classifier in dependency ID
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
  src/main/java/tech/jhipster/lite/module/domain/javabuildplugin/JavaBuildPlugin.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/DependencyId.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/JavaDependency.java
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModulesFixture.java
  src/test/java/tech/jhipster/lite/module/domain/javadependency/JavaDependencyMangementTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/FileSystemProjectJavaDependenciesRepositoryTest.java
Labels: area: bug :bug:, generator: internal

#4229 Update node
  .github/dependabot.yml
  pom.xml
  src/main/resources/generator/dependencies/common/package.json
Labels: area: enhancement :wrench:, generator: internal

#4240 Update SonarQube version
  src/main/docker/sonar.yml
Labels: generator: internal

#4242 Unused imports
  src/main/java/tech/jhipster/lite/generator/server/springboot/cucumbercommon/domain/CucumbersModules.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/core/domain/OAuth2ModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdoccore/domain/SpringdocModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/FileSystemJavaDependenciesReaderTest.java
Labels: generator: internal, area: refactoring

#4243 Angular: Standalone Components (clean code)
  src/main/resources/generator/client/angular/core/src/main/webapp/app/app.component.ts.mustache
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/login/login.component.ts.mustache
  src/test/resources/projects/angular/app.component.ts
  src/test/resources/projects/angular/app.module-with-providers.ts
  src/test/resources/projects/angular/app.module.ts
Labels: area: refactoring, client: angular

#3231 Move to vitest
  jest.config.js
  package-lock.json
  package.json
  src/main/webapp/app/common/primary/timeout/Timeout.ts
  src/test/javascript/spec/common/domain/Optional.spec.ts
  src/test/javascript/spec/common/domain/Statistics.spec.ts
  src/test/javascript/spec/common/primary/app/App.spec.ts
  src/test/javascript/spec/common/primary/header/Header.spec.ts
  src/test/javascript/spec/common/primary/icon/Icon.spec.ts
  src/test/javascript/spec/common/primary/timeout/Timeout.spec.ts
  src/test/javascript/spec/common/primary/toast/Toast.spec.ts
  src/test/javascript/spec/common/secondary/ConsoleLogger.spec.ts
  src/test/javascript/spec/common/secondary/RestStatisticsRepository.spec.ts
  src/test/javascript/spec/common/secondary/alert/MittAlertBus.spec.ts
  src/test/javascript/spec/common/secondary/alert/MittAlertListener.spec.ts
  src/test/javascript/spec/http/AxiosHttp.spec.ts
  src/test/javascript/spec/loader/primary/Loader.spec.ts
  src/test/javascript/spec/module/domain/landscape/Landscape.spec.ts
  src/test/javascript/spec/module/domain/landscape/LandscapeSelectionTree.spec.ts
  src/test/javascript/spec/module/domain/landscape/LandscapeUnselectionTree.spec.ts
  src/test/javascript/spec/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/javascript/spec/module/primary/landscape/LandscapeConnector.spec.ts
  src/test/javascript/spec/module/primary/modules-patch/ModulesPatchComponent.spec.ts
  src/test/javascript/spec/module/primary/project-actions/ProjectActionsComponent.spec.ts
  src/test/javascript/spec/module/secondary/RestModulesRepository.spec.ts
  src/test/javascript/spec/module/secondary/RestProjectFoldersRepository.spec.ts
  tsconfig.json
  vitest.config.ts
Labels: area: enhancement :wrench:, generator: internal, $$ bug-bounty $$, $200, $300

#4261 Angular: unused code
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/auth/auth.interceptor.spec.ts.mustache
Labels: area: refactoring, client: angular

#4263 Upgrade Angular 14.2.9
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#4264 React: clean tests
  src/main/resources/generator/client/react/src/test/javascript/spec/login/primary/loginForm/index.test.tsx.mustache
  src/main/resources/generator/client/react/src/test/javascript/spec/login/services/login.test.ts.mustache
Labels: area: refactoring, client: react

#4265 Vue: Eslint dependencies
  src/main/resources/generator/dependencies/vue/package.json
Labels: area: dependencies, client: vue

#4266 Eslint dependencies
  .eslintrc.js
  package-lock.json
  package.json
Labels: generator: internal, area: dependencies

#4272 rename sonar modules to sonar-qube
  src/main/java/tech/jhipster/lite/generator/JHLiteModuleSlug.java
  src/main/java/tech/jhipster/lite/generator/server/sonar/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/sonarqube/application/SonarQubeApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/sonarqube/domain/SonarQubeModulesFactory.java
  src/main/java/tech/jhipster/lite/generator/server/sonarqube/infrastructure/primary/SonarQubeModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/sonarqube/package-info.java
  src/test/features/sonar.feature
  src/test/java/tech/jhipster/lite/generator/server/sonarqube/domain/SonarQubeModulesFactoryTest.java
  tests-ci/generate.sh
Labels: area: refactoring, theme: ci

#4268 Refactor AsyncSpringLiquibaseTest
  src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseModuleFactory.java
  src/main/resources/generator/server/springboot/dbmigration/liquibase/main/AsyncSpringLiquibase.java.mustache
  src/main/resources/generator/server/springboot/dbmigration/liquibase/test/AsyncSpringLiquibaseTest.java.mustache
  src/main/resources/generator/server/springboot/dbmigration/liquibase/test/LogbackRecorder.java.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseModuleFactoryTest.java
Labels: server: spring boot, theme: database, area: refactoring

#4352 Upgrade Angular 14.2.10
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#4359 Bump node version to 18.12.1
  pom.xml
Labels: generator: internal, area: dependencies

#4360 Bump Spring Boot to 3.0.0-RC2
  pom.xml
Labels: server: spring boot, generator: internal, area: dependencies

#4361 Kafka: clean unused classes
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/Akhq.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/Kafka.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/Zookeeper.java
Labels: server: spring boot, area: refactoring, theme: broker

#4362 Update URL documentation in Springdoc configuration
  src/main/java/tech/jhipster/lite/documentation/infrastructure/primary/SpringdocConfiguration.java
Labels: generator: internal, theme: api, area: refactoring

#4363 Infinitest move to setup
  src/main/java/tech/jhipster/lite/generator/infinitest/package-info.java
  src/main/java/tech/jhipster/lite/generator/setup/infinitest/application/InfinitestApplicationService.java
  src/main/java/tech/jhipster/lite/generator/setup/infinitest/domain/InfinitestModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/setup/infinitest/infrastructure/primary/InfinitestModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/setup/infinitest/package-info.java
  src/test/java/tech/jhipster/lite/generator/setup/infinitest/domain/InfinitestModuleFactoryTest.java
Labels: area: refactoring, theme: init

#4365 CI: remove spring-boot-3 branch
  .github/workflows/github-actions.yml
Labels: generator: CI, area: refactoring

#4367 pagination-domain: fix missing dependency commons-lang3
  src/main/java/tech/jhipster/lite/generator/server/pagination/domainmodel/domain/PaginationDomainModuleFactory.java
  src/main/resources/generator/dependencies/pom.xml
  src/test/features/pagination.feature
  src/test/java/tech/jhipster/lite/generator/server/pagination/domainmodel/domain/PaginationDomainModuleFactoryTest.java
Labels: area: bug :bug:, server: java

#4368 Add glyph, style and target public folders to checksum file
  pom.xml
Labels: area: enhancement :wrench:, generator: internal

#4370 Sonar: Similar tests should be grouped in a single Parameterized test
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/MavenCommandHandlerTest.java
Labels: generator: internal, area: refactoring

#4371 Similar tests should be grouped in a single Parameterized test
  src/test/java/tech/jhipster/lite/module/domain/replacement/TextNeedleBeforeReplacerTest.java
Labels: generator: internal, area: refactoring

#4130 Update end-to-end modules dependencies
  src/main/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/tools/cypress/infrastructure/primary/CypressModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/tools/playwright/domain/PlaywrightModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/tools/playwright/infrastructure/primary/PlaywrightModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/infrastructure/primary/FrontendMavenModuleConfiguration.java
  src/main/resources/generator/client/common/cypress/src/test/javascript/integration/common/primary/app/Home.spec.ts
  src/main/resources/generator/client/common/cypress/src/test/javascript/integration/cypress-config.ts
  src/main/resources/generator/client/common/playwright/playwright.config.ts
  src/main/resources/generator/client/common/playwright/src/test/javascript/integration/common/primary/app/Home-Page.ts
  src/main/resources/generator/client/common/playwright/src/test/javascript/integration/common/primary/app/Home.spec.ts
  src/test/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/tools/playwright/domain/PlaywrightModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: client

#4372 Revert "Similar tests should be grouped in a single Parameterized test"
  src/test/java/tech/jhipster/lite/module/domain/replacement/TextNeedleBeforeReplacerTest.java
Labels: area: triage

#4314 add graal vm native image support for jhipster lite
  README.md
  pom.xml
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/NativeHints.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/OpenApiModulesConfiguration.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/git/NativeHints.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/git/NativeJGitConfiguration.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/NativeHints.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/NativeJavaDependencyConfiguration.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/NativeHints.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/ProjectFormatterConfiguration.java
  src/main/resources/config/application.properties
  src/main/resources/logback-spring.xml
Labels: area: feature request :bulb:, generator: internal

#4373 Revert "Sonar: Similar tests should be grouped in a single Parameterized test"
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/MavenCommandHandlerTest.java
Labels: generator: internal, area: refactoring

#4481 group oauth2 modules under the same feature
  src/main/java/tech/jhipster/lite/generator/JHLiteFeatureSlug.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/auth0/infrastructure/primary/OAuth2Auth0ModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/okta/infrastructure/primary/OAuth2OktaModuleConfiguration.java
Labels: area: triage

#4497 Upgrade springdoc
  pom.xml
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterLandscape.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterLandscapeDependency.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterLandscapeFeature.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterLandscapeLevel.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterLandscapeModule.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterModule.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterModuleCategory.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterModuleProperties.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterModulePropertyDefinition.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterModulesToApply.java
  src/main/java/tech/jhipster/lite/project/infrastructure/primary/RestAppliedModule.java
  src/main/java/tech/jhipster/lite/statistic/infrastructure/primary/RestStatistics.java
Labels: area: dependencies

#4518 Upgrade to spring boot 3
  pom.xml
Labels: server: spring boot, generator: internal, area: dependencies

#4507 group springdoc auth modules under same features
  src/main/java/tech/jhipster/lite/generator/JHLiteFeatureSlug.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocauth0/infrastructure/primary/SpringDocAuth0ModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocjwt/infrastructure/primary/SpringdocJwtModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocoauth/infrastructure/primary/SpringdocOauth2ModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocokta/infrastructure/primary/SpringDocOktaModuleConfiguration.java
Labels: area: triage

#4519 fix minor typos in okta documentation
  src/main/resources/generator/server/springboot/mvc/security/oauth2/okta/documentation/okta.md.mustache
Labels: area: triage
