Repository seed4j/seed4j, pull requests merged in 2023-05, with the labels that each got.

#6105 fix native hints for jgit integration
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/git/NativeHints.java
Labels: area: enhancement :wrench:, generator: internal, $$ bug-bounty $$, $100, theme: docker :whale:

#6147 Sonarcloud: fix 6 bugs and 15 code smells
  sonar-project.properties
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.component.ts
  src/test/javascript/spec/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/javascript/spec/module/primary/modules-patch/ModulesPatchComponent.spec.ts
Labels: area: enhancement :wrench:, generator: internal

#6178 Sonarcloud: fix 2 bugs and 15 code smells
  sonar-project.properties
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
Labels: area: enhancement :wrench:, generator: internal

#6091 Share module properties between landscape and patch screens
  src/main/webapp/app/main.ts
  src/main/webapp/app/module/domain/ModuleParametersRepository.ts
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
  src/main/webapp/app/module/primary/landscape/Landscape.html
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.component.ts
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.html
  src/main/webapp/app/module/secondary/LocalStorageModuleParametersRepository.ts
  src/test/javascript/spec/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/javascript/spec/module/primary/modules-patch/ModulesPatchComponent.spec.ts
  src/test/javascript/spec/module/secondary/LocalStorageModuleParametersRepository.spec.ts
Labels: area: enhancement :wrench:, generator: internal

#6290 Dependabot: ignore Node 20 as not LTS
  .github/dependabot.yml
Labels: generator: CI, area: dependencies

#6171 Upgrade Angular 16
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#6316 Angular 16: Styles removal opt-in
  src/main/resources/generator/client/angular/core/src/main/webapp/main.ts.mustache
  src/test/resources/projects/angular/main.ts
Labels: area: enhancement :wrench:, client: angular

#6315 Angular 16: DestroyRef Provider
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/login/login.component.ts.mustache
Labels: area: enhancement :wrench:, client: angular

#6342 Spring-boot 3.1.0
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/domain/MongoDbModuleFactory.java
  src/main/resources/generator/dependencies/pom.xml
  src/main/resources/generator/server/springboot/mvc/security/jwt/authentication/main/infrastructure/primary/SecurityConfiguration.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/main/infrastructure/primary/SecurityConfiguration.java.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/domain/MongoDbModuleFactoryTest.java
Labels: server: spring boot, area: dependencies, $$ bug-bounty $$, $200

#6358 Sonar: disable redundant type alias rule
  sonar-project.properties
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
Labels: area: enhancement :wrench:, theme: ci

#6387 Angular 16.0.3
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#6247 add placeholder during load
  package-lock.json
  package.json
  src/main/webapp/app/module/primary/landscape-loader/LandscapeLoader.component.ts
  src/main/webapp/app/module/primary/landscape-loader/LandscapeLoader.html
  src/main/webapp/app/module/primary/landscape-loader/LandscapeLoader.vue
  src/main/webapp/app/module/primary/landscape-loader/ListPlaceHolder.component.ts
  src/main/webapp/app/module/primary/landscape-loader/ListPlaceHolder.html
  src/main/webapp/app/module/primary/landscape-loader/ListPlaceHolder.vue
  src/main/webapp/app/module/primary/landscape-loader/PhPicture.component.ts
  src/main/webapp/app/module/primary/landscape-loader/PhPicture.html
  src/main/webapp/app/module/primary/landscape-loader/PhPicture.vue
  src/main/webapp/app/module/primary/landscape-loader/PhRow.html
  src/main/webapp/app/module/primary/landscape-loader/PhRow.ts
  src/main/webapp/app/module/primary/landscape-loader/PhRow.vue
  src/main/webapp/app/module/primary/landscape-loader/index.ts
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
  src/main/webapp/app/module/primary/landscape/Landscape.html
  src/main/webapp/app/module/primary/modules-patch-loader/ModulesPatchLoader.component.ts
  src/main/webapp/app/module/primary/modules-patch-loader/ModulesPatchLoader.html
  src/main/webapp/app/module/primary/modules-patch-loader/ModulesPatchLoader.vue
  src/main/webapp/app/module/primary/modules-patch-loader/index.ts
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.component.ts
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.html
  vite.config.ts
Labels: area: enhancement :wrench:, generator: internal

#6441 Sonar: 'await' should only be used with promises
  src/test/javascript/spec/module/primary/landscape/LandscapeComponent.spec.ts
Labels: area: enhancement :wrench:, generator: internal

#6444 Angular: update angular.json
  src/main/resources/generator/client/angular/core/angular.json
  src/test/resources/projects/angular/angular.json
Labels: area: enhancement :wrench:, client: angular

#6442 Java: Concatenation can be replaced with text block
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/docker/FileSystemDockerImagesReaderTest.java
Labels: area: enhancement :wrench:, generator: internal

#6445 Java: duplicate branch in switch
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemSpringPropertiesCommandsHandler.java
Labels: area: enhancement :wrench:, generator: internal

#6446 Unused local variables should be removed
  src/main/java/tech/jhipster/lite/generator/client/angular/security/jwt/domain/AngularJwtModuleFactory.java
Labels: area: enhancement :wrench:, server: java
