Repository seed4j/seed4j, pull requests merged in 2023-10, with the labels that each got.

#7613 Bun compatibility
  package.json
  src/main/java/tech/jhipster/lite/generator/prettier/domain/PrettierModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/prettier/domain/PrettierModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: init

#7614 Enable some builds with java 21
  .github/actions/setup/action.yml
  .github/workflows/github-actions.yml
Labels: area: dependencies, server: java

#7592 Refactoring: ThemeButton.vue
  src/main/style/atom/_atom.scss
  src/main/style/atom/atom.pug
  src/main/style/atom/theme-button/_theme-button.scss
  src/main/style/atom/theme-button/theme-button.code.pug
  src/main/style/atom/theme-button/theme-button.md
  src/main/style/atom/theme-button/theme-button.mixin.pug
  src/main/style/atom/theme-button/theme-button.render.pug
  src/main/webapp/app/common/primary/theme-button/ThemeButton.vue
  src/test/javascript/spec/common/primary/theme-button/ThemeButton.spec.ts
Labels: generator: internal, area: refactoring

#7659 Upgrade json-web-token.version 0.12.1
  src/main/resources/generator/dependencies/pom.xml
  src/main/resources/generator/server/springboot/cucumberauthentication/oauth2/CucumberAuthenticationConfiguration.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/authentication/main/infrastructure/primary/JwtReader.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/authentication/main/infrastructure/primary/SecurityConfiguration.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/authentication/test/infrastructure/primary/JwtReaderTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/basic-auth/main/infrastructure/secondary/JwtTokensRepository.java.mustache
Labels: theme: security, server: spring boot, area: dependencies, server: java

#7660 Bump npm to 10.2.0
  CONTRIBUTING.md
  pom.xml
Labels: generator: internal, area: dependencies

#7672 KafkaPropertiesTest: fix raw use of parametrized HashMap
  src/main/resources/generator/server/springboot/broker/kafka/KafkaPropertiesTest.java.mustache
Labels: area: enhancement :wrench:, theme: broker

#7675 React - Sonar: Literals should not be used for promise rejection
  src/main/resources/generator/client/react/src/test/javascript/spec/login/services/login.test.ts.mustache
Labels: area: refactoring, client: react

#7662 Refactoring: Header.vue
  src/main/style/organism/header/_header.scss
  src/main/style/organism/header/header.mixin.pug
  src/main/webapp/app/common/primary/header/Header.vue
Labels: generator: internal, area: refactoring

#7671 Refactoring: TagFilter.vue
  src/main/style/molecule/_molecule.scss
  src/main/style/molecule/molecule.pug
  src/main/style/molecule/tag-filter/_tag-filter.scss
  src/main/style/molecule/tag-filter/tag-filter.code.pug
  src/main/style/molecule/tag-filter/tag-filter.md
  src/main/style/molecule/tag-filter/tag-filter.mixin.pug
  src/main/style/molecule/tag-filter/tag-filter.render.pug
  src/main/style/token/_colors.scss
  src/main/webapp/app/module/primary/tag-filter/TagFilter.html
  src/main/webapp/app/module/primary/tag-filter/TagFilter.vue
  src/test/javascript/spec/module/primary/modules-patch/ModulesPatchComponent.spec.ts
Labels: generator: internal, area: refactoring

#7674 Refactoring: ModuleParameters.vue
  src/main/style/organism/_organism.scss
  src/main/style/organism/module-parameters/_module-parameters.scss
  src/main/style/organism/module-parameters/module-parameters.code.pug
  src/main/style/organism/module-parameters/module-parameters.md
  src/main/style/organism/module-parameters/module-parameters.mixin.pug
  src/main/style/organism/module-parameters/module-parameters.render.pug
  src/main/style/organism/organism.pug
  src/main/webapp/app/module/primary/module-parameters/ModuleParameters.vue
Labels: generator: internal, area: refactoring

#7714 Improve doc for package-types
  src/main/resources/generator/server/javatool/base/main/package-types.md.mustache
Labels: area: documentation:books:, server: java

#7727 Format: reorder import
  src/main/resources/generator/server/javatool/base/main/collection/ProjectCollections.java.mustache
  src/main/resources/generator/server/javatool/base/test/collection/ProjectCollectionsTest.java.mustache
Labels: server: java, area: refactoring

#7716 Refactoring: ModuleProperties.vue
  src/main/style/organism/_organism.scss
  src/main/style/organism/module-properties/_module-properties.scss
  src/main/style/organism/module-properties/module-properties.code.pug
  src/main/style/organism/module-properties/module-properties.md
  src/main/style/organism/module-properties/module-properties.mixin.pug
  src/main/style/organism/module-properties/module-properties.render.pug
  src/main/style/organism/organism.pug
  src/main/style/token/_colors.scss
  src/main/webapp/app/module/primary/module-properties-form/ModulePropertiesForm.html
  src/main/webapp/app/module/primary/module-properties-form/ModulePropertiesForm.vue
Labels: generator: internal, area: refactoring

#7737 I fixed the typo.
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/documentation/application-errors.md.mustache
Labels: area: triage

#7732 CI: Disable interactive mode in maven settings.xml
  .github/actions/setup/action.yml
Labels: area: enhancement :wrench:, generator: CI

#7733 Switch back to temurin jdk distribution since temurin-21 has been released
  .github/actions/setup/action.yml
Labels: area: refactoring, theme: CI

#7738 Bump to Maven 3.9.5
  .devcontainer/devcontainer.json
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/resources/generator/buildtool/maven/.mvn/wrapper/maven-wrapper.jar
  src/main/resources/generator/buildtool/maven/.mvn/wrapper/maven-wrapper.properties
  src/main/resources/generator/buildtool/maven/mvnw
  src/main/resources/generator/buildtool/maven/mvnw.cmd
  src/main/resources/generator/buildtool/maven/pom.xml.mustache
  src/test/resources/generator/buildtool/maven/pom.test.xml
  src/test/resources/projects/init-maven/pom.xml
Labels: theme: maven, area: dependencies

#7739 Bump spring-cloud to 2022.0.4
  src/main/resources/generator/dependencies/pom.xml
Labels: server: spring boot, area: dependencies, theme: microservices

#7741 Refactoring: ProjectActions
  src/main/webapp/app/module/primary/project-actions/ProjectActions.vue
Labels: generator: internal, area: refactoring

#7744 Code cleanup
  src/main/java/tech/jhipster/lite/generator/client/angular/security/jwt/application/AngularJwtApplicationService.java
  src/main/java/tech/jhipster/lite/generator/client/tools/playwright/application/PlaywrightApplicationService.java
  src/main/java/tech/jhipster/lite/module/domain/javaproperties/SpringPropertyTypeFileName.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterModule.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemPackageJsonHandler.java
  src/main/java/tech/jhipster/lite/project/domain/history/ProjectActionsAppender.java
  src/test/java/tech/jhipster/lite/cucumber/ResponseAsserter.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterModulesAssertions.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/FileSystemProjectJavaDependenciesRepositoryTest.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepositoryTest.java
  src/test/java/tech/jhipster/lite/shared/error/infrastructure/primary/GeneratorExceptionFactory.java
Labels: area: refactoring

#7734 Preparation for Spring YAML configuration
  pom.xml
  src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdoccore/domain/SpringdocModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/sqlcommon/domain/SQLCommonModuleBuilder.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/configclient/domain/SpringCloudConfigModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/consul/domain/ConsulModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/eureka/domain/EurekaModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/gateway/domain/GatewayModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
  src/main/java/tech/jhipster/lite/module/domain/javaproperties/PropertyValue.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/PropertiesFileSpringFactoriesHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/PropertiesFileSpringPropertiesHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/YamlFileSpringPropertiesHandler.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemSpringCommentsCommandsHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemSpringPropertiesCommandsHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/PropertiesFileSpringPropertiesHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/YamlFileSpringPropertiesHandlerTest.java
  src/test/resources/projects/project-with-spring-application-properties/application.properties
  src/test/resources/projects/project-with-spring-application-yaml/application.yml
Labels: area: feature request :bulb:, generator: internal

#7754 Refactoring improve security part
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/main/infrastructure/primary/SecurityConfiguration.java.mustache
Labels: theme: security, server: spring boot, area: refactoring

#7743 Refactoring: ModulePatchLoader.vue
  src/main/style/layout.pug
  src/main/style/organism/_organism.scss
  src/main/style/organism/module-patch-loader/_module-patch-loader.scss
  src/main/style/organism/module-patch-loader/module-patch-loader.code.pug
  src/main/style/organism/module-patch-loader/module-patch-loader.md
  src/main/style/organism/module-patch-loader/module-patch-loader.mixin.pug
  src/main/style/organism/module-patch-loader/module-patch-loader.render.pug
  src/main/style/organism/organism.pug
  src/main/style/token/_colors.scss
  src/main/webapp/app/module/primary/modules-patch-loader/ModulesPatchLoader.html
  src/main/webapp/app/module/primary/modules-patch-loader/ModulesPatchLoader.vue
Labels: generator: internal, area: refactoring

#7755 Remove obsolete @ExcludeFromGeneratedCodeCoverage after jacoco upgrade
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscape.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterLandscapeElement.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemPackageJsonHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemSpringFactoriesCommandsHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemSpringPropertiesCommandsHandler.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/ProjectFormatterConfiguration.java
Labels: generator: internal, area: dependencies, area: refactoring

#7766 Bump Node to 18.18.2
  .github/actions/setup/action.yml
  CONTRIBUTING.md
  pom.xml
  src/main/resources/generator/ci/github/actions/.github/actions/setup/action.yml.mustache
  src/main/resources/generator/dependencies/common/package.json
Labels: generator: internal, area: dependencies

#7773 Refactoring: ModulesPatch.vue
  src/main/style/organism/_organism.scss
  src/main/style/organism/modules-patch/_modules-patch.scss
  src/main/style/organism/modules-patch/modules-patch.code.pug
  src/main/style/organism/modules-patch/modules-patch.md
  src/main/style/organism/modules-patch/modules-patch.mixin.pug
  src/main/style/organism/modules-patch/modules-patch.render.pug
  src/main/style/organism/organism.pug
  src/main/style/token/_colors.scss
  src/main/style/token/_token.scss
  src/main/style/token/custom.scss
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.html
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.vue
Labels: generator: internal, area: refactoring

#7791 Refactoring: LandscapeLoader.vue
  src/main/style/organism/_organism.scss
  src/main/style/organism/landscape-loader/_landscape-loader.scss
  src/main/style/organism/landscape-loader/landscape-loader.code.pug
  src/main/style/organism/landscape-loader/landscape-loader.md
  src/main/style/organism/landscape-loader/landscape-loader.mixin.pug
  src/main/style/organism/landscape-loader/landscape-loader.render.pug
  src/main/style/organism/organism.pug
  src/main/webapp/app/module/primary/landscape-loader/LandscapeLoader.html
  src/main/webapp/app/module/primary/landscape-loader/LandscapeLoader.vue
Labels: generator: internal, area: refactoring

#7747 (refactoring) Remove application(-.*).properties templates
  src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootCoreModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
  src/main/java/tech/jhipster/lite/module/domain/javaproperties/SpringProfile.java
  src/main/resources/generator/server/springboot/core/main/application-local.properties.mustache
  src/main/resources/generator/server/springboot/core/main/application.properties.mustache
  src/main/resources/generator/server/springboot/core/test/application-test.properties.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootCoreModuleFactoryTest.java
Labels: server: spring boot, area: refactoring

#7746 Support multi lines spring properties comments
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/PropertiesFileSpringCommentsHandler.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/PropertiesFileSpringCommentsHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandlerTest.java
Labels: area: enhancement :wrench:, server: java

#7803 Refactoring: Landscape.vue
  src/main/style/organism/_organism.scss
  src/main/style/organism/landscape/_landscape.scss
  src/main/style/organism/landscape/landscape.code.pug
  src/main/style/organism/landscape/landscape.md
  src/main/style/organism/landscape/landscape.mixin.pug
  src/main/style/organism/landscape/landscape.render.pug
  src/main/style/organism/organism.pug
  src/main/style/token/_colors.scss
  src/main/webapp/app/assets/global.scss
  src/main/webapp/app/module/primary/landscape-minimap/LandscapeMiniMap.html
  src/main/webapp/app/module/primary/landscape/Landscape.vue
Labels: generator: internal, area: refactoring

#7819 Landscape MiniMap: Add interactions (hover, selection, ...) to match current landscape state
  src/main/webapp/app/module/primary/landscape-minimap/LandscapeMiniMap.component.ts
Labels: area: enhancement :wrench:, generator: internal

#7804 Add Java prerequisites, when adding Maven
  src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/MavenModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModuleShortcuts.java
  src/main/java/tech/jhipster/lite/module/domain/replacement/TextNeedleAfterReplacer.java
  src/main/resources/generator/init/README.md.mustache
  src/test/java/tech/jhipster/lite/generator/buildtool/maven/domain/MavenModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/domain/replacement/TextNeedleAfterReplacerTest.java
  src/test/resources/projects/README.md
Labels: area: documentation:books:, theme: maven, $$ bug-bounty $$, $100

#7856 Generator: convert Spring configuration to YAML
  .github/workflows/github-actions.yml
  src/main/resources/config/application-angular.properties
  src/main/resources/config/application-angular.yml
  src/main/resources/config/application-cloud.properties
  src/main/resources/config/application-cloud.yml
  src/main/resources/config/application-react.properties
  src/main/resources/config/application-react.yml
  src/main/resources/config/application-vue.properties
  src/main/resources/config/application-vue.yml
  src/main/resources/config/application.properties
  src/main/resources/config/application.yml
  src/test/resources/config/application-mongodb.properties
  src/test/resources/config/application-mongodb.yml
  src/test/resources/config/application-test.yml
Labels: generator: internal, area: refactoring

#7855 Use more universal shebang for scripts
  release.sh
  tests-ci/generate.sh
  tests-ci/sonar.sh
  tests-ci/start.sh
  tests-ci/start_docker_compose.sh
  tests-ci/stop.sh
  tests-ci/wait_sonar.sh
Labels: area: enhancement :wrench:, generator: CI

#7869 Bump Node to 20.9.0 and NPM to 10.2.1
  .github/actions/setup/action.yml
  .github/dependabot.yml
  CONTRIBUTING.md
  pom.xml
  src/main/resources/generator/ci/github/actions/.github/actions/setup/action.yml.mustache
  src/main/resources/generator/dependencies/common/package.json
Labels: generator: internal, area: dependencies

#7878 Checkstyle rule to prevent usage of junit4
  checkstyle.xml
  src/main/resources/generator/server/javatool/checkstyle/main/checkstyle.xml.mustache
  src/test/java/tech/jhipster/lite/generator/server/javatool/checkstyle/domain/CheckstyleModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: tests

#7880 doc(README): remove typo
  README.md
Labels: area: documentation:books:, generator: internal

#7879 Clean: application.exception.*
  src/main/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/webflux/web/domain/SpringBootWebfluxModuleFactory.java
  src/main/resources/config/application.yml
  src/test/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/webflux/web/domain/SpringBootWebfluxModuleFactoryTest.java
  src/test/resources/config/application-test.yml
Labels: server: spring boot, area: refactoring

#7883 Tikui: add link to the home page on navbar
  src/main/style/index.pug
  src/main/style/layout-documentation.pug
Labels: area: enhancement :wrench:, generator: internal

#7886 documentation: fixed grammatical errors and typos
  documentation/hexagonal-architecture.md
  documentation/module-creation.md
Labels: area: documentation:books:

#7881 Some typos
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/cassandrapersistence/domain/DummyCassandraPersistenceModuleFactory.java
  src/test/java/tech/jhipster/lite/module/domain/file/JHipsterDestinationTest.java
  src/test/java/tech/jhipster/lite/shared/collection/domain/JHipsterCollectionsTest.java
Labels: server: java, area: refactoring

#7884 Fix punctuation
  src/main/resources/generator/server/springboot/dbmigration/cassandra/README.md
  src/main/resources/generator/server/springboot/dbmigration/cassandra/cassandra-migration.md
Labels: area: enhancement :wrench:, theme: docs

#7896 Dockerfile: use multi-stage build strategy
  .dockerignore
  Dockerfile
Labels: generator: internal, area: refactoring

#7897 Rename class: AngularhealthModuleConfiguration
  src/main/java/tech/jhipster/lite/generator/client/angular/admin/health/infrastructure/primary/AngularHealthModuleConfiguration.java
Labels: server: java, area: refactoring

#7898 Typo
  src/test/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeTest.java
Labels: server: java, area: refactoring

#7895 fix typo error in hexagonal-architecture.md
  documentation/hexagonal-architecture.md
Labels: area: documentation:books:
