Repository seed4j/seed4j, pull requests merged in 2024-04, with the labels that each got.

#9427 Fix CI builds: replace usage of "docker compose" by "docker-compose"
  .github/workflows/github-actions.yml
Labels: generator: CI

#9237 Fix deprecated methods
  src/main/resources/generator/server/springboot/cucumberauthentication/oauth2/CucumberAuthenticationConfiguration.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/authentication/test/infrastructure/primary/JwtReaderTest.java.mustache
Labels: area: enhancement :wrench:, theme: security

#9406 (ci) Test generated apps with LTS node version, excepted one that uses latest node version
  .github/actions/setup/action.yml
  .github/workflows/github-actions.yml
Labels: generator: CI, area: dependencies

#9407 Relax minimum node and maven versions required to contribute to jhipster-lite
  package-lock.json
  package.json
  pom.xml
  src/main/resources/generator/buildtool/maven/pom.xml.mustache
  src/main/resources/generator/ci/github/actions/.github/actions/setup/action.yml.mustache
  src/test/resources/generator/buildtool/maven/pom.test.xml
  src/test/resources/projects/init-maven/pom.xml
Labels: area: dependencies

#9462 Remove unnecessary space
  package.json
Labels: area: enhancement :wrench:

#9477 Use codecov-action@v4
  .github/actions/setup/action.yml
  .github/workflows/github-actions.yml
Labels: generator: CI

#9465 Upgrade node and npm
  CONTRIBUTING.md
  pom.xml
Labels: generator: internal, area: dependencies

#9488 Codecov: try to fix analysis
  .github/workflows/github-actions.yml
Labels: area: bug :bug:, generator: CI

#9492 Remove codecov: code coverage is already checked with javacoco and istanbul
  .github/workflows/github-actions.yml
  README.md
Labels: generator: CI, area: refactoring

#9493 Remove unused test resources
  src/test/resources/generator/server/springboot/core/application.src.local.properties
  src/test/resources/generator/server/springboot/core/application.src.properties
  src/test/resources/generator/server/springboot/core/application.test.properties
  src/test/resources/generator/server/springboot/liquibase/master.test.xml
  src/test/resources/generator/utils/example-readme.md
  src/test/resources/generator/utils/example.patch
  src/test/resources/generator/utils/readme-short.md
Labels: generator: internal, area: refactoring

#9497 Sonar: reinclude rules with Java 21 support
  sonar-project.properties
Labels: area: enhancement :wrench:, generator: internal

#9513 gradle ability to declare resources filtering in a generic way
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModulesApplyer.java
  src/main/java/tech/jhipster/lite/module/domain/gradleconfiguration/GradleConfiguration.java
  src/main/java/tech/jhipster/lite/module/domain/gradleconfiguration/JHipsterModuleGradleConfigurations.java
  src/main/java/tech/jhipster/lite/module/domain/javabuild/command/AddGradleConfiguration.java
  src/main/java/tech/jhipster/lite/module/domain/javabuild/command/JavaBuildCommand.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/FileSystemJavaBuildCommandsHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/JavaDependenciesCommandHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MavenCommandHandler.java
  src/main/resources/generator/buildtool/gradle/build.gradle.kts.mustache
  src/main/resources/generator/dependencies/build.gradle.kts
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModulesFixture.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModulesRepositoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandlerTest.java
  src/test/resources/projects/empty-gradle/build.gradle.kts
  src/test/resources/projects/gradle-with-properties/build.gradle.kts
  src/test/resources/projects/init-gradle/build.gradle.kts
Labels: area: feature request :bulb:, theme: gradle

#9498 Migrate from pug-lint to eslint pug plugin
  .eslintrc.cjs
  .lintstagedrc.js
  README.md
  package-lock.json
  package.json
Labels: generator: internal, area: dependencies

#9535 Upgrade Node and Npm
  CONTRIBUTING.md
  pom.xml
Labels: generator: internal, area: dependencies

#9534 Next: Migrate from pug-lint to eslint pug plugin
  .pug-lintrc.json
  package.json
Labels: generator: internal, area: dependencies

#9530 ArchUnit: rename package 'arch' to 'archunit'
  src/main/java/tech/jhipster/lite/generator/server/javatool/arch/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/archunit/application/JavaArchUnitApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/archunit/domain/ArchUnitModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/archunit/infrastructure/primary/ArchUnitModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/archunit/package-info.java
  src/main/resources/generator/server/javatool/archunit/test/AnnotationArchTest.java.mustache
  src/main/resources/generator/server/javatool/archunit/test/HexagonalArchTest.java.mustache
  src/main/resources/generator/server/javatool/archunit/test/archunit.properties.mustache
  src/test/java/tech/jhipster/lite/generator/server/javatool/archunit/domain/ArchUnitModuleFactoryTest.java
Labels: generator: internal, area: refactoring

#9537 Cypress: Use recommanded ESLint rules
  src/test/javascript/cypress/.eslintrc.cjs
  src/test/javascript/cypress/integration/Patch.spec.ts
Labels: area: enhancement :wrench:

#9536 Remove unused dependency: @rushstack/eslint-patch
  package-lock.json
  package.json
  src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactory.java
  src/main/resources/generator/dependencies/vue/package.json
  src/test/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.java
Labels: area: dependencies

#9540 Adding 'it' would make the text less colloquial
  src/main/resources/generator/server/springboot/mvc/sample/feature/sample.md
Labels: area: enhancement :wrench:

#9541 chore: remove useless application.properties test resources
  src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/cassandrapersistence/domain/SampleCassandraPersistenceModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/git/JGitGitRepositoryTest.java
  src/test/resources/projects/cassandra/application.properties
  src/test/resources/projects/files/application.properties
Labels: generator: internal, area: refactoring

#9551 support gradle at spring-boot-local-profile module
  src/main/java/tech/jhipster/lite/generator/server/springboot/localeprofile/domain/LocalProfileModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/buildproperties/PropertyValue.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/localeprofile/domain/LocalProfileModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandlerTest.java
  src/test/resources/projects/ci/.gitlab-ci-gradle.yml
  src/test/resources/projects/ci/github-actions-gradle.yml
  tests-ci/generate.sh
Labels: area: feature request :bulb:, theme: gradle

#9596 Migration from gradle enterprise to develocity
  .mvn/develocity.xml
  .mvn/extensions.xml
  pom.xml
Labels: theme: gradle, area: dependencies

#9597 fix(develocity): git-ignore workspace-id
  .gitignore
Labels: theme: gradle, area: dependencies

#9592 fix(lint-staged): fix configuration to avoid task concurrency
  .jhipster/modules/history.json
  .lintstagedrc.js
  .prettierignore
  package.json
  src/main/glyph/font/jhlite-icons.svg
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/auth/oauth2-auth.service.spec.ts
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/auth/oauth2-auth.service.ts
  src/main/resources/generator/client/common/cypress/src/test/javascript/integration/common/primary/app/Home.spec.ts
  src/main/resources/generator/client/common/cypress/src/test/javascript/integration/cypress-config.ts
  src/main/resources/generator/client/common/playwright/playwright.config.ts
  src/main/resources/generator/client/react/.eslintrc.cjs
  src/main/resources/generator/client/react/postcss.config.js
  src/main/resources/generator/client/react/tailwind.config.js
  src/main/resources/generator/typescript/test/javascript/spec/common/domain/optional/Optional.spec.ts
  src/main/style/atom/chip/_chip.scss
  src/main/style/organism/landscape-minimap/_landscape-minimap.scss
  src/main/style/organism/landscape/_landscape.scss
  src/main/style/template/menu-content-template/_menu-content-template.scss
  src/main/style/token/_colors.scss
  src/test/javascript/cypress/integration/Landscape.spec.ts
  src/test/javascript/cypress/integration/Patch.spec.ts
  src/test/resources/projects/react-app/App.tsx
  src/test/resources/projects/react-app/index.tsx
Labels: generator: internal, area: refactoring

#9611 Handle breaking changes in develocity.xml
  .mvn/develocity.xml
  .prettierignore
Labels: generator: internal, generator: CI

#9609 Simplify HexagonalArchTest: compute rootPackagePath on the fly from root package name constant
  src/main/java/tech/jhipster/lite/generator/server/javatool/archunit/domain/ArchUnitModuleFactory.java
  src/main/resources/generator/server/javatool/archunit/test/HexagonalArchTest.java.mustache
  src/test/java/tech/jhipster/lite/HexagonalArchTest.java
  src/test/java/tech/jhipster/lite/generator/server/javatool/archunit/domain/ArchUnitModuleFactoryTest.java
Labels: area: enhancement :wrench:, server: java

#9623 Format pug files with prettier
  .lintstagedrc.js
  .prettierrc
  package-lock.json
  package.json
  src/main/style/atom/atom.pug
  src/main/style/atom/button/button.mixin.pug
  src/main/style/atom/chip/chip.mixin.pug
  src/main/style/atom/icon/icon.mixin.pug
  src/main/style/atom/input/input-text/input-text.mixin.pug
  src/main/style/atom/input/input.pug
  src/main/style/atom/label/label.mixin.pug
  src/main/style/atom/logo/logo.mixin.pug
  src/main/style/atom/nav-item/nav-item.mixin.pug
  src/main/style/index.pug
  src/main/style/layout-documentation.pug
  src/main/style/layout.mixin.pug
  src/main/style/layout.pug
  src/main/style/molecule/field/field.mixin.pug
  src/main/style/molecule/icon-text/icon-text.mixin.pug
  src/main/style/molecule/molecule.pug
  src/main/style/molecule/toast/toast.mixin.pug
  src/main/style/organism/landscape-minimap/landscape-minimap.mixin.pug
  src/main/style/organism/landscape/landscape.mixin.pug
  src/main/style/organism/organism.pug
  src/main/style/organism/side-menu/side-menu.mixin.pug
  src/main/style/organism/side-menu/side-menu.render.pug
  src/main/style/template/template.pug
Labels: area: enhancement :wrench:, generator: internal

#9610 Develocity: replace deprecated "GRADLE_ENTERPRISE_ACCESS_KEY" environment variable by "DEVELOCITY_ACCESS_KEY"
  .github/workflows/github-actions.yml
  .mvn/develocity.xml
Labels: generator: internal, generator: CI

#9630 Generate a package.json requiring only the recent major node.js version, not the latest patch version
  src/main/java/tech/jhipster/lite/generator/init/domain/InitModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/npm/NpmPackageVersion.java
  src/main/java/tech/jhipster/lite/module/domain/npm/NpmVersions.java
  src/main/resources/generator/init/package.json.mustache
  src/test/java/tech/jhipster/lite/generator/init/domain/InitModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactoryTest.java
Labels: area: enhancement :wrench:

#9633 Wording: ESLint
  README.md
Labels: area: enhancement :wrench:

#9634 develocity: only publish scans if authenticated
  .dockerignore
  .mvn/develocity.xml
Labels: area: enhancement :wrench:, theme: CI

#9635 develocity: complete maven-frontend-plugin configuration
  pom.xml
Labels: generator: CI

#9624 Use Mustache.java for template rendering
  pom.xml
  src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/file/ArgumentsReplacer.java
  src/main/java/tech/jhipster/lite/module/domain/file/JHipsterFileContent.java
  src/main/java/tech/jhipster/lite/module/domain/file/JHipsterTemplatedFile.java
  src/main/java/tech/jhipster/lite/module/domain/file/TemplateRenderer.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModuleFiles.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModulesRepository.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/file/MustacheTemplateRenderer.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/FileSystemJavaBuildCommandsHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
  src/main/resources/generator/server/springboot/broker/kafka/kafka.yml.mustache
  src/main/resources/generator/server/springboot/dbmigration/liquibase/test/SpringLiquibaseUtilTest.java.mustache
  src/main/resources/generator/server/springboot/springcloud/configclient/application.config.properties.mustache
  src/main/resources/generator/server/springboot/springcloud/consul/docker/application.config.yml.mustache
  src/main/resources/generator/server/springboot/springcloud/eureka/application.config.properties.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModulesFixture.java
  src/test/java/tech/jhipster/lite/module/domain/file/ArgumentsReplacerTest.java
  src/test/java/tech/jhipster/lite/module/domain/file/JHipsterFileContentTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModuleFilesTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/TestJHipsterModules.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/file/MustacheTemplateRendererTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/FileSystemJavaBuildCommandsHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandlerTest.java
Labels: area: enhancement :wrench:, generator: internal, $$ bug-bounty $$, $200

#9606 Module: Property-based testing using jqwik
  src/main/java/tech/jhipster/lite/generator/server/javatool/pbt/application/PropertyBasedTestingApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/pbt/domain/PropertyBasedTestingModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/pbt/infrastructure/primary/PropertyBasedTestingModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/pbt/package-info.java
  src/main/java/tech/jhipster/lite/generator/slug/domain/JHLiteModuleSlug.java
  src/main/resources/generator/dependencies/pom.xml
  src/main/resources/generator/server/javatool/pbt/property-based-testing.md
  src/test/features/server/javatool/property-based-testing.feature
  src/test/java/tech/jhipster/lite/generator/server/javatool/pbt/domain/PropertyBasedTestingModuleFactoryTest.java
  tests-ci/generate.sh
Labels: area: feature request :bulb:, server: java

#9538 Archunit rules for wire packages
  src/main/resources/generator/server/javatool/archunit/test/HexagonalArchTest.java.mustache
  src/main/resources/generator/server/springboot/async/src/AsyncConfiguration.java.mustache
  src/main/resources/generator/server/springboot/cache/ehcache/main/EhcacheProperties.java.mustache
  src/main/resources/generator/server/springboot/dbmigration/liquibase/main/AsyncSpringLiquibase.java.mustache
  src/main/resources/generator/server/springboot/dbmigration/liquibase/main/SpringLiquibaseUtil.java.mustache
  src/main/resources/generator/server/springboot/logging/logstash/main/LogstashTcpConfiguration.java.mustache
  src/main/resources/generator/server/springboot/logging/logstash/main/LogstashTcpLifeCycle.java.mustache
  src/main/resources/generator/server/springboot/logging/logstash/main/LogstashTcpProperties.java.mustache
  src/main/resources/generator/server/springboot/mvc/web/main/cors/CorsFilterConfiguration.java.mustache
  src/main/resources/generator/server/springboot/mvc/web/main/cors/CorsProperties.java.mustache
  src/test/java/tech/jhipster/lite/HexagonalArchTest.java
Labels: area: feature request :bulb:, theme: tests

#9607 Module: Approval testing using ApprovalTests
  src/main/java/tech/jhipster/lite/generator/server/javatool/approvaltesting/application/ApprovalTestingApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/approvaltesting/domain/ApprovalTestingModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/approvaltesting/infrastructure/primary/AdvancedTestingModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/approvaltesting/package-info.java
  src/main/java/tech/jhipster/lite/generator/slug/domain/JHLiteModuleSlug.java
  src/main/resources/generator/dependencies/pom.xml
  src/test/features/server/javatool/approval-testing.feature
  src/test/java/tech/jhipster/lite/generator/server/javatool/approvaltesting/domain/ApprovalTestingModuleFactoryTest.java
  tests-ci/generate.sh
Labels: area: feature request :bulb:, server: java

#9657 [ignore ci] Remove unused codecov configuration
  codecov.yml
Labels: generator: CI, area: refactoring

#9372 Improve some toString methods in module domain API
  src/main/java/tech/jhipster/lite/module/domain/javabuild/command/AddMavenPluginManagement.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/DependencyId.java
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeModule.java
  src/main/java/tech/jhipster/lite/module/domain/mavenplugin/MavenPlugin.java
  src/main/java/tech/jhipster/lite/module/domain/mavenplugin/MavenPluginExecution.java
  src/main/java/tech/jhipster/lite/module/domain/properties/JHipsterPropertyKey.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModuleGroup.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModuleOperation.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModuleOrganization.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertiesDefinition.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertyDefinition.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModuleResource.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModuleTag.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModuleTags.java
  src/test/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeTest.java
  src/test/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertiesDefinitionTest.java
  src/test/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertyDefinitionTest.java
  src/test/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResourcesTest.java
Labels: generator: internal

#9659 develocity: package.json should be an input file for "npm build" and "npm test" executions
  pom.xml
Labels: area: enhancement :wrench:, theme: CI

#9662 Rework FileSystemProjectJavaBuildToolRepository
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javabuild/FileSystemProjectJavaBuildToolRepository.java
Labels: area: enhancement :wrench:, generator: internal

#9663 Rework JHipsterHiddenResourcesProperties
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenModules.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterHiddenResourcesProperties.java
Labels: generator: internal, area: refactoring

#9668 Add missing gitignore for jqwik/property-based testing module
  src/main/resources/generator/init/gitignore
Labels: area: enhancement :wrench:, theme: tests

#9667 Use the same maven cache when building native image as other builds
  .github/workflows/publish-native-docker-image.yml
Labels: area: enhancement :wrench:, generator: CI

#9670 (ci): Use new secret DEVELOCITY_ACCESS_KEY instead of GRADLE_ENTERPRiSE
  .github/workflows/github-actions.yml
Labels: generator: CI

#9632 Sonar: Fix tag em with role=img
  src/main/style/atom/icon/icon.mixin.pug
  src/main/webapp/app/common/primary/icon/Icon.vue
Labels: area: bug :bug:, area: enhancement :wrench:

#9671 Angular: add .mustache extension
  src/main/java/tech/jhipster/lite/generator/client/angular/security/oauth2/domain/AngularOauth2ModuleFactory.java
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/auth/http-auth.interceptor.spec.ts.mustache
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/auth/http-auth.interceptor.ts.mustache
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/auth/oauth2-auth.service.spec.ts.mustache
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/auth/oauth2-auth.service.ts.mustache
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/login/login.component.html.mustache
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/login/login.component.spec.ts.mustache
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/login/login.component.ts.mustache
Labels: area: enhancement :wrench:, client: angular

#9664 Rework YamlFileSpringPropertiesHandler
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/YamlFileSpringPropertiesHandler.java
Labels: generator: internal, area: refactoring

#9672 Dependabot: ignore Node 22 as not LTS
  .github/dependabot.yml
Labels: generator: CI, area: dependencies

#9681 enh(ci): tests-linux: start local sonar after the linting step
  .github/workflows/github-actions.yml
Labels: area: enhancement :wrench:, generator: CI
