Repository seed4j/seed4j, pull requests merged in 2024-11, with the labels that each got.

#11268 Remove deprecated code
  sonar-project.properties
  src/main/java/tech/jhipster/lite/module/domain/packagejson/JHipsterModulePackageJson.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemPackageJsonHandlerTest.java
Labels: area: enhancement :wrench:, generator: internal

#11269 Upgrade Angular 18.2.10
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#11270 Sonar: reactivate circular dependencies rules
  sonar-project.properties
Labels: area: enhancement :wrench:

#11271 Sonar: reactivate circular dependency rule on generated apps
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
  src/main/resources/generator/server/sonar/sonar-project.properties.mustache
Labels: area: enhancement :wrench:

#11274 Revert "Sonar: reactivate circular dependencies rules"
  sonar-project.properties
Labels: area: enhancement :wrench:

#11275 Revert "Sonar: reactivate circular dependency rule on generated apps"
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
  src/main/resources/generator/server/sonar/sonar-project.properties.mustache
Labels: area: enhancement :wrench:

#11283 Sonar: reactivate - Deprecated code should be removed
  sonar-project.properties
Labels: area: enhancement :wrench:

#11285 Angular/ESLint: reactivate consistent-type-definitions rule
  src/main/resources/generator/client/angular/core/eslint.config.mjs.mustache
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/auth/auth-jwt.service.ts.mustache
Labels: area: enhancement :wrench:, client: angular

#11295 Angular/ESLint: activate arrow-body-style rule
  src/main/resources/generator/client/angular/admin/src/main/webapp/app/admin/health/health.component.ts.mustache
  src/main/resources/generator/client/angular/core/eslint.config.mjs.mustache
Labels: area: enhancement :wrench:, client: angular

#11294 Angular/ESLint: activate no-unsafe-call rule
  src/main/resources/generator/client/angular/core/eslint.config.mjs.mustache
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/login/login.component.spec.ts.mustache
Labels: area: enhancement :wrench:, client: angular

#11284 Sonar: reactivate rule on generated apps - Deprecated code should be removed
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
  src/main/resources/generator/server/sonar/sonar-project.properties.mustache
Labels: area: enhancement :wrench:

#11273 Allow using langchain4j module
  src/main/java/tech/jhipster/lite/generator/server/springboot/langchain4j/application/LangChain4JApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/langchain4j/domain/LangChain4JModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/langchain4j/infrastructure/primary/LangChain4JModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/langchain4j/package-info.java
  src/main/java/tech/jhipster/lite/shared/slug/domain/JHLiteModuleSlug.java
  src/main/resources/generator/dependencies/pom.xml
  src/main/resources/generator/server/springboot/langchain4j/langchain4j.md.mustache
  src/test/features/server/springboot/langchain4j.feature
  src/test/java/tech/jhipster/lite/generator/server/springboot/langchain4j/domain/LangChain4JModuleFactoryTest.java
Labels: area: feature request :bulb:, server: java

#11302 Cypress: Best practices for selectors
  src/main/resources/generator/client/common/cypress/utils/DataSelector.ts
  src/main/webapp/app/module/primary/landscape-loader/LandscapeLoader.html
  src/main/webapp/app/module/primary/landscape-minimap/LandscapeMiniMap.component.ts
  src/main/webapp/app/module/primary/landscape-minimap/LandscapeMiniMap.html
  src/main/webapp/app/module/primary/landscape-module/LandscapeModule.html
  src/main/webapp/app/module/primary/landscape-preset-configuration/LandscapePresetConfiguration.html
  src/main/webapp/app/module/primary/landscape/Landscape.html
  src/main/webapp/app/module/primary/module-parameters/ModuleParameters.html
  src/main/webapp/app/module/primary/module-properties-form/ModulePropertiesForm.html
  src/main/webapp/app/module/primary/modules-patch-loader/ModulesPatchLoader.html
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.html
  src/main/webapp/app/module/primary/project-actions/ProjectActions.html
  src/main/webapp/app/module/primary/tag-filter/TagFilter.html
  src/main/webapp/app/shared/theme-button/infrastructure/primary/ThemeButton.vue
  src/main/webapp/app/shared/toast/infrastructure/primary/Toast.vue
  src/test/webapp/component/support/selector.ts
  src/test/webapp/e2e/support/selector.ts
  src/test/webapp/unit/WrappedElement.ts
  src/test/webapp/unit/common/primary/toast/Toast.spec.ts
Labels: area: enhancement :wrench:, theme: tests, theme: client

#11272 Sonar: Reactivate rule - Run container as default user
  src/main/resources/generator/server/sonar/sonar-project.properties.mustache
  src/main/resources/generator/server/springboot/dbmigration/cassandra/Cassandra-Migration.Dockerfile.mustache
Labels: area: enhancement :wrench:, theme: docker :whale:

#11316 Sonar: Fix - refactor this code to not nest functions more than 4 levels deep
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
Labels: area: enhancement :wrench:

#11324 Clean code
  src/main/java/tech/jhipster/lite/module/domain/npm/NpmVersions.java
  src/main/resources/generator/client/common/hexagonal-documentation/front-hexagonal-architecture.md.mustache
  src/main/resources/generator/server/springboot/database/jpa/MsSQLTestContainerExtension.java.mustache
Labels: area: enhancement :wrench:

#11317 Sonar: Fix - refactor this code to not nest functions more than 4 levels deep
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
Labels: generator: internal, area: refactoring, theme: tests

#11326 Clean code
  src/main/java/tech/jhipster/lite/shared/error/domain/Assert.java
Labels: area: enhancement :wrench:

#11328 Clean code
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/resources/assertions-errors/assertion-errors-messages.properties
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/resources/errors/application-errors-messages_fr.properties
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/ApplicationErrorsHandlerIT.java.mustache
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/AssertionErrorsHandlerIT.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/basic-auth/main/infrastructure/primary/RestAuthenticationQuery.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/docker/jhipster-realm.json.mustache
  src/main/resources/messages/assertions-errors/assertion-errors-messages.properties
  src/test/java/tech/jhipster/lite/shared/error/infrastructure/primary/AssertionErrorsHandlerIT.java
Labels: area: enhancement :wrench:

#11329 Rename file with typo
  src/test/webapp/unit/common/primary/toast/Toast.spec.ts
  src/test/webapp/unit/router/index.spec.ts
  src/test/webapp/unit/shared/alert/domain/AlertListener.fixture.ts
Labels: area: enhancement :wrench:

#11332 Upgrade Angular 18.2.11
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#11333 React: remove react-scripts dependency (unused)
  src/main/resources/generator/dependencies/react/package.json
Labels: area: enhancement :wrench:, client: react

#11336 Typo
  src/main/webapp/app/module/secondary/LocalStorageModuleParametersRepository.ts
  src/test/webapp/unit/module/secondary/LocalStorageModuleParametersRepository.spec.ts
Labels: generator: internal, area: refactoring

#11338 Remove unnecessary exclusion
  pom.xml
Labels: generator: internal, area: refactoring

#11327 Refacto: selector.ts to Selector.ts
  src/test/webapp/component/integration/Landscape.spec.ts
  src/test/webapp/component/integration/Patch.spec.ts
  src/test/webapp/component/support/Selector.ts
  src/test/webapp/e2e/integration/Patch.spec.ts
  src/test/webapp/e2e/support/Selector.ts
Labels: generator: internal, area: refactoring, theme: tests

#11337 Update maven enforcer messages
  pom.xml
Labels: generator: internal

#11296 Vue/ESLint: add @typescript-eslint/consistent-type-imports rule
  src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactory.java
  src/main/resources/generator/client/common/cypress/utils/Interceptor.ts
  src/main/resources/generator/client/common/playwright/common/primary/app/Home-Page.ts
  src/main/resources/generator/client/vue/documentation/vue-oauth2-keycloak-authentication-components.md
  src/main/resources/generator/client/vue/i18n/src/test/HomePageVue.spec.ts
  src/main/resources/generator/client/vue/security/oauth2_keycloak/webapp/app/auth/application/AuthProvider.ts.mustache
  src/main/resources/generator/client/vue/security/oauth2_keycloak/webapp/app/auth/infrastructure/secondary/KeycloakAuthRepository.ts.mustache
  src/main/resources/generator/client/vue/security/oauth2_keycloak/webapp/app/auth/infrastructure/secondary/KeycloakHttp.ts.mustache
  src/main/resources/generator/client/vue/security/oauth2_keycloak/webapp/app/test/webapp/unit/auth/infrastructure/secondary/KeycloakStub.ts.mustache
  src/main/resources/generator/client/vue/webapp/app/env.d.ts.mustache
  src/main/resources/generator/client/vue/webapp/app/test/webapp/unit/router/infrastructure/primary/HomeRouter.spec.ts.mustache
  src/test/resources/projects/vue/HomepageVue.spec.ts.template
  src/test/resources/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.shouldCreateVueModule.eslint.config.js.approved.txt
  src/test/webapp/unit/root/infrastructure/primary/App.spec.ts
Labels: area: enhancement :wrench:, client: vue

#11334 React/Sonar: void should not be used
  src/main/resources/generator/client/react/i18n/src/main/webapp/app/i18n.ts
Labels: area: enhancement :wrench:, client: react

#11335 Add Spring Boot LangChain4j sample
  .github/workflows/github-actions.yml
  CONTRIBUTING.md
  src/main/java/tech/jhipster/lite/generator/server/springboot/langchain4j/domain/LangChain4JModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/langchain4j/application/SampleLangChain4jApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/langchain4j/domain/SampleLangChain4jModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/langchain4j/infrastructure/primary/SampleLangChain4jModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/langchain4j/package-info.java
  src/main/java/tech/jhipster/lite/shared/slug/domain/JHLiteModuleSlug.java
  src/main/resources/generator/server/springboot/mvc/sample/langchain4j/main/infrastructure/primary/ChatResource.java.mustache
  src/main/resources/generator/server/springboot/mvc/sample/langchain4j/test/sample/infrastructure/primary/ChatResourceTest.java.mustache
  src/test/features/server/springboot/langchain4j.feature
  src/test/java/tech/jhipster/lite/generator/server/springboot/langchain4j/domain/LangChain4JModuleFactoryTest.java
  tests-ci/generate.sh
Labels: area: feature request :bulb:, server: spring boot, server: java

#11342 Refactoring LangChain4j
  src/main/java/tech/jhipster/lite/generator/server/springboot/langchain4j/application/LangChain4jApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/langchain4j/domain/LangChain4jModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/langchain4j/infrastructure/primary/LangChain4jModuleConfiguration.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/langchain4j/domain/LangChain4jModuleFactoryTest.java
Labels: server: java, area: refactoring

#11343 Refactoring generate sh
  tests-ci/generate.sh
Labels: generator: CI, area: refactoring

#10948 Generator: add missing test for RestManagementRepository
  src/test/webapp/unit/module/secondary/RestManagementRepository.spec.ts
  vitest.config.ts
Labels: area: enhancement :wrench:, generator: internal, theme: tests

#11323 Fix: Update apache/kafka-native Docker tag to v3.9.0
  src/main/resources/generator/dependencies/Dockerfile
  src/main/resources/generator/server/springboot/broker/kafka/KafkaTestContainerExtension.java.mustache
Labels: area: dependencies

#11353 ci: use java 23 version instead of 22 for at least one build
  .github/workflows/github-actions.yml
Labels: generator: CI, area: dependencies

#11355 React/ESLint: add @typescript-eslint/consistent-type-imports rule
  src/main/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactory.java
  src/test/resources/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.shouldBuildModuleWithStyle.eslint.config.js.approved.txt
Labels: area: enhancement :wrench:, client: react

#11356 Clean code
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/npm/NpmVersionsReader.java
  src/main/resources/generator/server/javatool/archunit/test/EqualsHashcodeArchTest.java.mustache
  src/main/resources/generator/server/javatool/archunit/test/HexagonalArchTest.java.mustache
  src/main/resources/messages/errors/generator-errors-messages_fr.properties
  src/test/java/tech/jhipster/lite/EqualsHashcodeArchTest.java
Labels: area: refactoring

#11352 improve the ci to allow adding new config
  .github/workflows/github-actions.yml
Labels: area: enhancement :wrench:, generator: CI

#11380 Upgrade Angular 18.2.12
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#11425 CSS: Properties may be safely replaced with a shorthand
  src/main/style/atom/button/button-main/_button-main.scss
Labels: generator: internal

#11427 CSS: remove unused file animation.css
  src/main/glyph/css/animation.css
Labels: generator: internal

#11426 Fix typos
  documentation/hexagonal-architecture.md
  src/main/resources/generator/server/springboot/dbmigration/mongock/mongock.md
Labels: generator: internal

#11423 Add mvc server as frontend dependency
  src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/infrastructure/primary/FrontendJavaBuildToolModuleConfiguration.java
Labels: area: bug :bug:, area: enhancement :wrench:, server: spring boot, server: java

#11434 Clients: Apply Prettier
  src/main/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactory.java
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/auth/auth-jwt.service.ts.mustache
  src/main/resources/generator/typescript/vitest.config.ts.mustache
  src/test/resources/projects/react-app/vitest.config.ts.template
  src/test/resources/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.shouldBuildModuleWithStyle.eslint.config.js.approved.txt
  src/test/resources/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.shouldBuildModuleWithStyle.vitest.config.ts.approved.txt
  src/test/resources/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.shouldCreateVueModule.vitest.config.ts.approved.txt
Labels: generator: internal, client: vue, client: angular, client: react, theme: client

#11443 fix tikui styles broken by inter.css
  src/main/style/atom/theme-button/_theme-button.scss
  src/main/style/token/_fonts.scss
Labels: area: bug :bug:

#11446 Remove unused type TimeoutLauncher
  src/main/webapp/app/shared/toast/domain/Timeout.ts
Labels: generator: internal
