Repository seed4j/seed4j, pull requests merged in 2024-03, with the labels that each got.

#9095 Remove redundant method
  src/main/java/tech/jhipster/lite/generator/server/sonarqube/domain/SonarQubeModulesFactory.java
Labels: generator: internal, theme: gradle, area: refactoring

#9090 Sonar: %n should be used in place of \n to produce the platform-specific line separator.
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandlerTest.java
Labels: area: enhancement :wrench:, generator: internal

#9097 Fix typo
  documentation/hexagonal-architecture.md
  src/main/resources/generator/server/documentation/hexagonal-application-service/hexagonal-application-service-architecture.md
Labels: area: enhancement :wrench:, generator: internal

#9096 (checkstyle) Update description: checkstyle is used for more than imports checks
  src/main/java/tech/jhipster/lite/generator/server/javatool/checkstyle/infrastructure/primary/CheckstyleModuleConfiguration.java
Labels: area: documentation :books:

#9099 (frontend-maven-plugin) Install node in target directory
  pom.xml
  src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactoryTest.java
Labels: area: enhancement :wrench:

#9100 (checkstyle) Separate clearly each category of rules
  checkstyle.xml
  src/main/resources/generator/server/javatool/checkstyle/main/checkstyle.xml.mustache
Labels: area: enhancement :wrench:

#9103 Collection declared by class, not interface inspection
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModuleContext.java
  src/main/java/tech/jhipster/lite/shared/error/infrastructure/primary/AssertionErrorsHandler.java
Labels: area: enhancement :wrench:, generator: internal

#9104 Delete comments
  src/test/java/tech/jhipster/lite/generator/server/javatool/jacoco/domain/JacocoModuleFactoryTest.java
Labels: area: enhancement :wrench:, generator: internal

#9105 Use renovate for handling npm dependencies of jhlite engine
  .github/dependabot.yml
  renovate.json
Labels: area: dependencies, theme: CI

#9102 Unused imports
  src/main/java/tech/jhipster/lite/generator/server/sonarqube/domain/SonarQubeModulesFactory.java
  src/test/java/tech/jhipster/lite/generator/server/sonarqube/domain/SonarQubeModulesFactoryTest.java
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModulesFixture.java
Labels: area: enhancement :wrench:, generator: internal

#9101 bump vue-tsc 2.0.3
  package-lock.json
  package.json
Labels: generator: internal, area: dependencies

#9116 (checkstyle) Remove duplicated rule RedundantImport
  checkstyle.xml
  src/main/resources/generator/server/javatool/checkstyle/main/checkstyle.xml.mustache
Labels: area: refactoring

#9118 Fix gradle default tasks command
  src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootCoreModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootCoreModuleFactoryTest.java
Labels: area: triage

#9138 Unchecked exception declared in 'throws' clause
  src/test/java/tech/jhipster/lite/LogsSpyExtension.java
  src/test/java/tech/jhipster/lite/shared/error/infrastructure/primary/BeanValidationErrorsHandlerTest.java
Labels: area: enhancement :wrench:, generator: internal

#9139 Fix: equals() called on enum value
  src/main/java/tech/jhipster/lite/module/domain/packagejson/PackageJsonDependency.java
Labels: area: enhancement :wrench:, generator: internal

#9149 Unnecessary 'final' on variable
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/application/KafkaApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
  src/test/java/tech/jhipster/lite/module/domain/file/JHipsterFileContentTest.java
  src/test/java/tech/jhipster/lite/module/domain/properties/JHipsterModulePropertiesTest.java
Labels: area: enhancement :wrench:, generator: internal

#9150 Unnecessary unboxing
  src/main/java/tech/jhipster/lite/module/domain/Indentation.java
Labels: area: enhancement :wrench:, generator: internal

#9148 Unnecessary braces
  src/test/java/tech/jhipster/lite/IntegrationTest.java
  src/test/java/tech/jhipster/lite/shared/projectfolder/infrastructure/primary/ForcedProjectFolderPrefixIT.java
Labels: area: enhancement :wrench:, generator: internal

#9119 add develocity integration
  .github/workflows/github-actions.yml
  .gitignore
  .mvn/extensions.xml
  .mvn/gradle-enterprise.xml
  README.md
  pom.xml
Labels: area: enhancement :wrench:, theme: maven, theme: gradle, theme: CI

#9162 Use archunit {be|are}MetaAnnotatedWith rather than {be|are}AnnotatedWith methods
  src/main/resources/generator/server/javatool/arch/AnnotationArchTest.java.mustache
  src/main/resources/generator/server/javatool/arch/HexagonalArchTest.java.mustache
  src/test/java/tech/jhipster/lite/AnnotationArchTest.java
  src/test/java/tech/jhipster/lite/HexagonalArchTest.java
Labels: area: enhancement :wrench:, server: java

#9164 Fix: Consider spelling out the number
  src/main/resources/generator/server/documentation/hexagonal-application-service/hexagonal-application-service-architecture.md
  src/main/resources/generator/server/springboot/database/cassandra/TestCassandraManager.java.mustache
  src/main/resources/generator/server/springboot/dbmigration/cassandra/cassandra-migration.md
  src/main/resources/generator/server/springboot/mvc/sample/feature/sample.md
  src/main/resources/generator/server/springboot/mvc/security/kipe/authorization/kipe-authorization.md.mustache
Labels: area: enhancement :wrench:, generator: internal

#9165 Fix: should probably be singular in a compound noun
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MavenCommandHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MavenProjectJavaDependenciesRepository.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MavenCommandHandlerTest.java
Labels: area: enhancement :wrench:, generator: internal

#9166 Fix: unnecessary qualified static method call
  src/main/java/tech/jhipster/lite/module/domain/javadependency/DependencyId.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/JavaDependency.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/ProjectJavaDependencies.java
  src/main/java/tech/jhipster/lite/shared/error/domain/Assert.java
  src/test/java/tech/jhipster/lite/TestFileUtils.java
  src/test/java/tech/jhipster/lite/cucumber/rest/CucumberRestTestContext.java
  src/test/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResourceFixture.java
Labels: area: enhancement :wrench:, generator: internal

#9171 Fix: Unnecessarily qualified statically imported element
  src/main/java/tech/jhipster/lite/generator/server/springboot/banner/domain/BannerModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/typescript/optional/domain/OptionalTypescriptModuleFactory.java
  src/test/java/tech/jhipster/lite/cucumber/rest/CucumberRestAssertions.java
  src/test/java/tech/jhipster/lite/cucumber/rest/ElementAssertions.java
  src/test/java/tech/jhipster/lite/cucumber/rest/HeaderAssertions.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemSpringFactoriesCommandsHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/PropertiesFileSpringCommentsHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/PropertiesFileSpringFactoriesHandlerTest.java
Labels: area: enhancement :wrench:, generator: internal

#9170 Fix: No-arg constructor is redundant
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModuleChanges.java
  src/main/java/tech/jhipster/lite/module/domain/gradleplugin/GradleCommunityPlugin.java
  src/main/java/tech/jhipster/lite/module/domain/gradleplugin/GradleCorePlugin.java
  src/main/java/tech/jhipster/lite/module/domain/javabuild/MavenBuildExtension.java
  src/main/java/tech/jhipster/lite/module/domain/javabuild/command/AddGradlePlugin.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/JavaDependency.java
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeModule.java
  src/main/java/tech/jhipster/lite/module/domain/mavenplugin/MavenPlugin.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertyDefinition.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModuleResource.java
  src/main/java/tech/jhipster/lite/statistic/domain/AppliedModule.java
Labels: area: enhancement :wrench:, generator: internal

#9173 Add doc for java-build-tool
  CONTRIBUTING.md
Labels: area: documentation :books:

#9174 Fix: Modifier 'public' is redundant for interface members
  src/main/resources/generator/server/springboot/cucumber/rest/ResponseAsserter.java.mustache
Labels: area: enhancement :wrench:, generator: internal

#9175 Improve CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area: documentation :books:

#9200 Bump maven-model-helper to version 29
  pom.xml
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MavenCommandHandler.java
Labels: area: dependencies, area: refactoring

#9199 Sonar: Functions should not be nested too deeply
  src/test/javascript/spec/common/domain/Optional.spec.ts
Labels: area: enhancement :wrench:, generator: internal

#9176 React: Improve Lighthouse (accessibility)
  src/main/resources/generator/client/react/src/main/webapp/app/common/primary/app/App.css.mustache
Labels: area: enhancement :wrench:, client: react

#9210 Refacto README
  src/main/resources/generator/init/README.md.mustache
  src/test/resources/generator/utils/example-readme.md
  src/test/resources/projects/README.md
Labels: area: enhancement :wrench:, generator: internal

#9227 Performance: Replace string literals with character literals
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/docker/FileSystemDockerImagesReader.java
  src/main/java/tech/jhipster/lite/shared/error/infrastructure/primary/BeanValidationErrorsHandler.java
Labels: area: enhancement :wrench:, generator: internal

#9077 Use Kafka official docker image, without zookeeper
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
  src/main/resources/generator/dependencies/Dockerfile
  src/main/resources/generator/server/springboot/broker/kafka/KafkaTestContainerExtension.java.mustache
  src/main/resources/generator/server/springboot/broker/kafka/kafka.yml.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactoryTest.java
  src/test/resources/generator/dependencies/Dockerfile
  tests-ci/modulePayload.json
Labels: area: feature request :bulb:, theme: broker

#9232 Bump NPM to 10.5.0
  CONTRIBUTING.md
  pom.xml
Labels: area: dependencies

#9207 add properties to gradle profile
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleDependencyErrorKey.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/MissingGradleProfileException.java
  src/main/resources/messages/errors/generator-errors-messages.properties
  src/main/resources/messages/errors/generator-errors-messages_fr.properties
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModulesFixture.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModulesRepositoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandlerTest.java
  src/test/resources/projects/gradle-with-local-profile-and-properties/buildSrc/src/main/kotlin/profile-local.gradle.kts
  src/test/resources/projects/gradle-with-local-profile/buildSrc/src/main/kotlin/profile-local.gradle.kts
Labels: area: feature request :bulb:, theme: gradle

#9236 Fix deprecated methods
  src/main/resources/generator/server/springboot/cucumberauthentication/jwt/AuthenticationSteps.java.mustache
  src/main/resources/generator/server/springboot/cucumberauthentication/oauth2/AuthenticationSteps.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/authentication/test/infrastructure/primary/JwtReaderTest.java.mustache
Labels: area: enhancement :wrench:, theme: security

#9238 Remove unnecessary throws declarations
  src/main/resources/generator/server/springboot/cucumber/rest/CucumberRestTestContextUnitTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/web/test/BeanValidationErrorsHandlerTest.java.mustache
Labels: area: enhancement :wrench:, generator: internal

#9240 Fix some typos
  documentation/cucumber.md
  src/main/resources/generator/server/springboot/cucumber/cucumber.md.mustache
  src/main/resources/generator/server/springboot/cucumberauthentication/cucumber-authentication.md
Labels: area: documentation :books:, area: enhancement :wrench:

#9239 make npm tasks cachable again via gradle enterprise plugin
  pom.xml
Labels: generator: internal, generator: CI

#9241 Remove maven-failsafe-plugin double execution
  pom.xml
Labels: generator: internal, generator: CI

#9242 Remove unused import
  src/main/resources/generator/server/springboot/dbmigration/liquibase/test/AsyncSpringLiquibaseTest.java.mustache
Labels: area: enhancement :wrench:

#9243 Missing semicolon
  src/main/resources/generator/server/pagination/rest/rest-pagination.md.mustache
Labels: area: enhancement :wrench:

#9244 Remove unnecessary throws declaration
  src/main/resources/generator/server/springboot/dbmigration/liquibase/test/AsyncSpringLiquibaseTest.java.mustache
Labels: area: enhancement :wrench:

#9247 Explicit type is useless
  src/main/resources/generator/server/springboot/mvc/security/kipe/expression/test/ObjectAccessCheckerTest.java.mustache
Labels: area: enhancement :wrench:

#9248 (fix) Missing output directory for npm run test in via gradle enterprise plugin configuration
  pom.xml
Labels: area: bug :bug:, generator: CI

#9246 Useless javadoc
  src/main/resources/generator/server/springboot/dbmigration/liquibase/main/AsyncSpringLiquibase.java.mustache
Labels: area: enhancement :wrench:

#9250 Fix typo in gradle enterprise configuration
  pom.xml
Labels: area: triage, generator: internal

#9269 Remove gradle checkstyle workaround fix
  src/main/java/tech/jhipster/lite/generator/server/javatool/checkstyle/domain/CheckstyleModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/server/javatool/checkstyle/domain/CheckstyleModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: gradle

#9303 Improve covariance in generator APIs
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModulesApplyer.java
  src/main/java/tech/jhipster/lite/module/domain/javabuild/command/JavaBuildCommands.java
  src/main/java/tech/jhipster/lite/module/domain/javabuildprofile/JHipsterModuleJavaBuildProfiles.java
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeDependencies.java
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeFeature.java
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeLevel.java
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeLevels.java
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeModule.java
  src/main/java/tech/jhipster/lite/module/domain/replacement/ContentReplacers.java
  src/main/java/tech/jhipster/lite/module/domain/replacement/JHipsterModuleOptionalReplacementsFactory.java
  src/main/java/tech/jhipster/lite/module/domain/replacement/JHipsterModuleReplacementsFactory.java
  src/main/java/tech/jhipster/lite/module/domain/startupcommand/JHipsterStartupCommands.java
  src/main/java/tech/jhipster/lite/shared/collection/domain/JHipsterCollections.java
  src/main/resources/generator/server/javatool/base/main/collection/ProjectCollections.java.mustache
  src/test/java/tech/jhipster/lite/shared/collection/domain/JHipsterCollectionsTest.java
Labels: area: enhancement :wrench:, generator: internal

#9267 create agnostic javabuildproperties for gradle and maven
  src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModulesApplyer.java
  src/main/java/tech/jhipster/lite/module/domain/buildproperties/JHipsterModuleBuildProperties.java
  src/main/java/tech/jhipster/lite/module/domain/javabuildprofile/JHipsterModuleJavaBuildProfile.java
  src/main/java/tech/jhipster/lite/module/domain/javabuildprofile/JHipsterModuleJavaBuildProfiles.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/JHipsterModuleJavaDependencies.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModulesFixture.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModulesRepositoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandlerTest.java
  src/test/resources/projects/gradle-with-properties/build.gradle.kts
Labels: area: feature request :bulb:, theme: gradle

#9270 Bump model-maven-helper to version 35
  pom.xml
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MavenCommandHandlerTest.java
Labels: theme: maven, area: dependencies, $$ bug-bounty $$, $200

#9333 Remove unnecessary qualifier
  src/main/java/tech/jhipster/lite/module/domain/javabuild/command/JavaBuildCommands.java
Labels: area: enhancement :wrench:

#9335 Factorization in JHipsterModulesFixture
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModulesFixture.java
Labels: generator: internal, area: refactoring

#9334 Missing @Override annotations
  src/main/java/tech/jhipster/lite/module/domain/javabuild/command/AddGradlePlugin.java
  src/main/java/tech/jhipster/lite/module/domain/javabuild/command/AddMavenPluginBuilder.java
  src/main/java/tech/jhipster/lite/module/domain/properties/InvalidPropertyTypeException.java
Labels: generator: internal, area: refactoring

#9337 (ci) Use 'properties' spring-config-format for another app using SQL database
  .github/workflows/github-actions.yml
Labels: generator: CI

#9332 Remove H2 dependency from liquibase
  src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModuleContext.java
  src/main/java/tech/jhipster/lite/module/domain/properties/JHipsterModuleProperties.java
  src/main/java/tech/jhipster/lite/module/domain/properties/SpringConfigurationFormat.java
  src/main/resources/generator/server/springboot/dbmigration/liquibase/test/SpringLiquibaseUtilTest.java.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModuleContextTest.java
Labels: area: dependencies, theme: database migration, theme: tests

#9339 Align terminology for jhipster property "SpringConfigurationFormat"
  src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocauth0/infrastructure/primary/SpringDocAuth0ModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdoccore/infrastructure/primary/SpringdocModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocoauth/infrastructure/primary/SpringdocOauth2ModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocokta/infrastructure/primary/SpringDocOktaModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/async/infrastructure/primary/SpringBootAsyncModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/infrastructure/primary/KafkaModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/infrastructure/primary/PulsarModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/cache/ehcache/infrastructure/primary/EHCacheModulesConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/core/infrastructure/primary/SpringBootCoreModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/customjhlite/infrastructure/primary/CustomJHLiteModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/cassandra/infrastructure/primary/CassandraModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/hibernate2ndlevelcache/infrastructure/primary/Hibernate2ndLevelCacheModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/mariadb/infrastructure/primary/MariaDBModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/infrastructure/primary/MongoDbModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/mssql/infrastructure/primary/MsSQLModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/infrastructure/primary/MySQLModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/infrastructure/primary/Neo4jModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/postgresql/infrastructure/primary/PostgresqlModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/redis/infrastructure/primary/RedisModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/flyway/infrastructure/primary/FlywayModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/infrastructure/primary/LiquibaseModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/mongock/infrastructure/primary/MongockModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/neo4jmigrations/infrastructure/primary/Neo4jMigrationsModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/devtools/infrastructure/primary/DevToolsModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/localeprofile/infrastructure/primary/LocalProfileModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/logging/logstash/infrastructure/primary/LogstashModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/jwt/infrastructure/primary/JwtAuthenticationModulesConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/auth0/infrastructure/primary/OAuth2Auth0ModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/core/infrastructure/primary/OAuth2ModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/okta/infrastructure/primary/OAuth2OktaModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/infrastructure/primary/SpringBootMvcModulesConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/technicaltools/actuator/infrastructure/primary/SpringBootActuatorModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/technicaltools/gitinfo/infrastructure/primary/GitInfoModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/infrastructure/primary/SpringBootThymeleafModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/template/infrastructure/primary/ThymeleafTemplateModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/webflux/web/infrastructure/primary/SpringBootWebfluxModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/webjars/infrastructure/primary/WebjarsModuleConfiguration.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModuleContext.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModulesApplyer.java
  src/main/java/tech/jhipster/lite/module/domain/properties/JHipsterModuleProperties.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertiesDefinition.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertyDefinition.java
  src/main/resources/generator/server/springboot/dbmigration/liquibase/test/SpringLiquibaseUtilTest.java.mustache
  src/test/features/server/springboot/database/mariadb.feature
  src/test/features/server/springboot/database/mssql.feature
  src/test/features/server/springboot/database/mysql.feature
  src/test/features/server/springboot/database/postgresql.feature
  src/test/features/server/springboot/dev-tools.feature
  src/test/features/server/springboot/spring-boot-core.feature
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModuleContextTest.java
  tests-ci/modulePayload.json
Labels: area: enhancement :wrench:, generator: internal

#9349 Remove unnecessary qualifier
  src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactory.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MavenCommandHandlerTest.java
Labels: area: enhancement :wrench:, generator: internal

#9356 Reformat file: uses whitespaces instead of indentations
  src/main/resources/generator/client/svelte/src/main/webapp/app/common/primary/app/App.svelte.mustache
Labels: area: enhancement :wrench:, client: svelte

#9367 Properties file is alphabetically unsorted
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/resources/assertions-errors/assertion-errors-messages.properties
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/resources/assertions-errors/assertion-errors-messages_fr.properties
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/resources/errors/application-errors-messages.properties
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/resources/errors/application-errors-messages_fr.properties
  src/main/resources/messages/assertions-errors/assertion-errors-messages.properties
  src/main/resources/messages/assertions-errors/assertion-errors-messages_fr.properties
  src/main/resources/messages/errors/generator-errors-messages.properties
  src/main/resources/messages/errors/generator-errors-messages_fr.properties
Labels: generator: internal, area: refactoring

#9370 Upgrade node version to 20.12.0
  .github/actions/setup/action.yml
  CONTRIBUTING.md
  package.json
  pom.xml
  src/main/resources/generator/ci/github/actions/.github/actions/setup/action.yml.mustache
  src/main/resources/generator/dependencies/common/package.json
Labels: area: enhancement :wrench:, generator: internal, area: dependencies

#9371 Fix checkstyle warnings
  src/main/java/tech/jhipster/lite/ApplicationStartupTraces.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/DependencyId.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/ProjectJavaDependencies.java
  src/main/java/tech/jhipster/lite/module/domain/mavenplugin/MavenPluginExecution.java
  src/main/java/tech/jhipster/lite/module/domain/packagejson/PackageJsonDependency.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterLandscapeModule.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterModule.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterModulePropertyDefinition.java
  src/main/java/tech/jhipster/lite/project/domain/history/ProjectAction.java
  src/test/java/tech/jhipster/lite/cucumber/rest/CucumberRestAssertions.java
  src/test/java/tech/jhipster/lite/module/domain/javadependency/DirectJavaDependencyTest.java
  src/test/java/tech/jhipster/lite/module/domain/javadependency/JavaDependencyManagementTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterModulesAssertions.java
  src/test/java/tech/jhipster/lite/shared/memoizer/domain/MemoizersTest.java
Labels: generator: internal

#9352 Add toString methods to a couple of objects
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeModule.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertiesDefinition.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertyDefinition.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModuleResource.java
  src/test/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeTest.java
  src/test/java/tech/jhipster/lite/module/domain/properties/JHipsterModulePropertiesDefinitionTest.java
  src/test/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResourcesTest.java
Labels: area: enhancement :wrench:, generator: internal

#9369 support dependencies and dependencies management in a build profile
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
  src/main/resources/generator/buildtool/gradle/buildSrc/settings.gradle.kts.template
  src/main/resources/generator/buildtool/gradle/buildSrc/src/main/kotlin/profile.gradle.kts.template
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModulesFixture.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModulesRepositoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandlerTest.java
  src/test/resources/projects/gradle-with-local-profile/build.gradle.kts
  src/test/resources/projects/gradle-with-local-profile/buildSrc/src/main/kotlin/profile-local.gradle.kts
Labels: area: feature request :bulb:, theme: gradle

#9378 enh(gradle): minor improvement in handling IOException and test coverage
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
Labels: generator: internal, theme: gradle, area: refactoring

#9377 fix(error-messages): French messages for not after/before time exceptions were incomplete
  src/main/resources/messages/assertions-errors/assertion-errors-messages_fr.properties
Labels: area: enhancement :wrench:, generator: internal

#9402 chore(deps): update dependency @prettier/plugin-xml to v3.4.1
  package-lock.json
  package.json
Labels: area: dependencies

#9351 Add new module renovate
  src/main/java/tech/jhipster/lite/generator/ci/renovate/application/RenovateApplicationService.java
  src/main/java/tech/jhipster/lite/generator/ci/renovate/domain/RenovateModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/ci/renovate/infrastructure/primary/RenovateModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/ci/renovate/package-info.java
  src/main/java/tech/jhipster/lite/generator/slug/domain/JHLiteFeatureSlug.java
  src/main/java/tech/jhipster/lite/generator/slug/domain/JHLiteModuleSlug.java
  src/main/resources/generator/ci/renovate/renovate.json.mustache
  src/test/features/ci/renovate.feature
  src/test/java/tech/jhipster/lite/generator/ci/renovate/RenovateModuleFactoryTest.java
  tests-ci/generate.sh
Labels: area: feature request :bulb:, area: dependencies, theme: CI

#9401 Renovate config tweaking
  renovate.json
  src/main/resources/generator/ci/renovate/renovate.json.mustache
Labels: area: dependencies

#9404 (ci) Use java 22 for one generated app
  .github/workflows/github-actions.yml
Labels: generator: CI, server: java
