Repository seed4j/seed4j, pull requests merged in 2024-08, with the labels that each got.

#10468 Modernize typescript module
  src/main/java/tech/jhipster/lite/generator/typescript/core/domain/TypescriptModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/typescript/optional/domain/OptionalTypescriptModuleFactory.java
  src/main/resources/generator/dependencies/common/package.json
  src/main/resources/generator/typescript/.eslintrc.cjs
  src/main/resources/generator/typescript/tsconfig.json
  src/main/resources/generator/typescript/vitest.config.ts.mustache
  src/test/java/tech/jhipster/lite/generator/typescript/domain/core/TypescriptModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/typescript/domain/optional/OptionalTypescriptModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: typescript

#10475 Sonar: clean exlusions files
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
  src/main/resources/generator/server/sonar/sonar-project.properties.mustache
  src/test/java/tech/jhipster/lite/generator/server/sonarqube/domain/SonarQubeModulesFactoryTest.java
Labels: area: enhancement :wrench:

#10476 rename LocalProfile Package
  src/main/java/tech/jhipster/lite/generator/server/springboot/locale_profile/application/LocalProfileApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/locale_profile/domain/LocalProfileModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/locale_profile/infrastructure/primary/LocalProfileModuleConfiguration.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/localeprofile/domain/LocalProfileModuleFactoryTest.java
Labels: area: enhancement :wrench:, generator: internal

#10483 rename cucumber authentication package
  src/main/java/tech/jhipster/lite/generator/server/springboot/cucumber_authentication/application/CucumberAuthenticationApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/cucumber_authentication/domain/CucumberAuthenticationModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/cucumber_authentication/infrastructure/primary/CucumberAuthenticationModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/cucumber_authentication/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/cucumberauthentication/package-info.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/cucumberauthentication/domain/CucumberAuthenticationModuleFactoryTest.java
Labels: area: enhancement :wrench:, generator: internal

#10484 added package-info.java in local_profile package.
  src/main/java/tech/jhipster/lite/generator/server/springboot/locale_profile/package-info.java
Labels: area: enhancement :wrench:, generator: internal

#10504 TsLoaderModuleFactory source and destination as class contants
  src/main/java/tech/jhipster/lite/generator/client/loader/domain/TsLoaderModuleFactory.java
Labels: area: triage

#10505 Add tests for Router (improve Sonar)
  sonar-project.properties
  src/main/webapp/app/router/index.ts
  src/test/webapp/unit/router/index.spec.ts
Labels: area: enhancement :wrench:

#10506 Bug: templatize application name in ApplicationErrorsHandlerTest.java…
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/ApplicationErrorsHandlerTest.java.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/internationalized_errors/domain/InternationalizedErrorsModuleFactoryTest.java
Labels: area: bug :bug:, server: spring boot, server: java

#10514 Move locals variables to class constants
  src/main/java/tech/jhipster/lite/generator/client/pagination_domain/domain/TSPaginationDomainModuleFactory.java
Labels: area: enhancement :wrench:, generator: internal

#10515 Remove useless file extension
  src/main/resources/generator/client/loader/Loader.spec.ts.mustache
Labels: area: enhancement :wrench:, theme: client

#10526 Sonar: consistency in paths
  sonar-project.properties
Labels: area: enhancement :wrench:

#10527 Sonar: remove unused rule
  sonar-project.properties
Labels: area: enhancement :wrench:

#10528 Fix CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area: documentation :books:, generator: internal

#10490 Sonar: remove svelte files
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
  src/test/java/tech/jhipster/lite/generator/server/sonarqube/domain/SonarQubeModulesFactoryTest.java
Labels: area: enhancement :wrench:, client: svelte

#10534 Sonar: consistency in paths
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
  src/main/resources/generator/server/sonar/sonar-project.properties.mustache
Labels: area: enhancement :wrench:

#10535 Fix: Method declared 'final' in 'final' class
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/ApplicationExceptionFactory.java.mustache
Labels: area: enhancement :wrench:, generator: internal

#10536 Fix: Wildcard type argument '?' explicitly extends 'java.lang.Object'
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/main/ArgumentsReplacer.java.mustache
Labels: area: enhancement :wrench:, generator: internal

#10537 Fix: This assertion is unnecessary since it does not change the type of the expression
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
Labels: area: enhancement :wrench:

#10538 Remove unnecessary comment
  src/test/webapp/unit/router/index.spec.ts
Labels: area: enhancement :wrench:

#10485 display preset options at landscape mode
  src/main/glyph/config.json
  src/main/glyph/css/jhlite-icons-codes.css
  src/main/glyph/css/jhlite-icons-embedded.css
  src/main/glyph/css/jhlite-icons-ie7-codes.css
  src/main/glyph/css/jhlite-icons-ie7.css
  src/main/glyph/css/jhlite-icons.css
  src/main/glyph/font/jhlite-icons.eot
  src/main/glyph/font/jhlite-icons.svg
  src/main/glyph/font/jhlite-icons.ttf
  src/main/glyph/font/jhlite-icons.woff
  src/main/glyph/font/jhlite-icons.woff2
  src/main/resources/preset.json
  src/main/style/atom/_atom.scss
  src/main/style/atom/atom.pug
  src/main/style/atom/select/_select.scss
  src/main/style/atom/select/select.code.pug
  src/main/style/atom/select/select.md
  src/main/style/atom/select/select.mixin.pug
  src/main/style/atom/select/select.render.pug
  src/main/style/organism/_organism.scss
  src/main/style/organism/landscape-preset-configuration/_landscape-preset-configuration.scss
  src/main/style/organism/landscape-preset-configuration/landscape-preset-configuration.code.pug
  src/main/style/organism/landscape-preset-configuration/landscape-preset-configuration.md
  src/main/style/organism/landscape-preset-configuration/landscape-preset-configuration.mixin.pug
  src/main/style/organism/landscape-preset-configuration/landscape-preset-configuration.render.pug
  src/main/style/organism/landscape/_landscape.scss
  src/main/style/organism/organism.pug
  src/main/webapp/app/module/domain/ModulesRepository.ts
  src/main/webapp/app/module/domain/Preset.ts
  src/main/webapp/app/module/domain/Presets.ts
  src/main/webapp/app/module/primary/landscape-preset-configuration/LandscapePresetConfiguration.component.ts
  src/main/webapp/app/module/primary/landscape-preset-configuration/LandscapePresetConfiguration.html
  src/main/webapp/app/module/primary/landscape-preset-configuration/LandscapePresetConfiguration.vue
  src/main/webapp/app/module/primary/landscape-preset-configuration/index.ts
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
  src/main/webapp/app/module/primary/landscape/Landscape.html
  src/main/webapp/app/module/secondary/RestModulesRepository.ts
  src/main/webapp/app/module/secondary/RestPreset.ts
  src/main/webapp/app/module/secondary/RestPresetModuleToApply.ts
  src/main/webapp/app/module/secondary/RestPresets.ts
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepositoryTest.java
  src/test/webapp/unit/module/domain/Modules.fixture.ts
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/webapp/unit/module/primary/landscape/LandscapePresetConfigurationComponent.spec.ts
  src/test/webapp/unit/module/secondary/RestModulesRepository.spec.ts
  src/test/webapp/unit/router/index.spec.ts
Labels: area: feature request :bulb:, generator: internal

#10549 Fix lint
  src/main/resources/generator/client/pagination/secondary/RestPage.spec.ts.mustache
Labels: area: enhancement :wrench:, theme: client

#10550 Sonar: This assertion is unnecessary since it does not change the type of the expression
  src/test/webapp/unit/module/primary/landscape/LandscapePresetConfigurationComponent.spec.ts
Labels: area: enhancement :wrench:, generator: internal

#10545 ESLint 9
  .eslintrc.cjs
  eslint.config.js
  package-lock.json
  package.json
  src/main/webapp/app/env.d.ts
Labels: generator: internal, area: dependencies

#10551 Vue: Type-Only Imports and Export
  src/main/resources/generator/client/vue/test/unit/common/domain/Logger.fixture.ts.mustache
  src/main/resources/generator/client/vue/test/unit/http/AxiosHttp.spec.ts.mustache
  src/main/resources/generator/client/vue/test/unit/http/AxiosHttpStub.ts.mustache
  src/main/resources/generator/client/vue/test/unit/http/AxiosStub.ts.mustache
Labels: area: enhancement :wrench:, client: vue

#10562 Add missing package-info file in jqassistant package
  src/main/java/tech/jhipster/lite/generator/server/documentation/jqassistant/package-info.java
Labels: area: enhancement :wrench:, generator: internal

#10566 Cypress && Vue not working
  src/main/resources/generator/client/common/cypress/src/test/webapp/component/tsconfig.json
Labels: area: bug :bug:, client: vue, theme: client

#10568 Use Map.forEach
  src/main/resources/generator/server/springboot/cucumber/rest/ElementAssertions.java.mustache
Labels: area: enhancement :wrench:, theme: tests

#10574 Angular 18.2.0 + Migrate dependency injection
  src/main/resources/generator/client/angular/admin/src/main/webapp/app/admin/health/modal/health-modal.component.ts.mustache
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#10579 Docs: sonar commands in sonar.md
  src/main/java/tech/jhipster/lite/generator/server/sonarqube/domain/SonarQubeModulesFactory.java
  src/main/resources/generator/server/sonar/sonar.md.mustache
  src/test/java/tech/jhipster/lite/generator/server/sonarqube/domain/SonarQubeModulesFactoryTest.java
Labels: area: documentation :books:, theme: tests

#10585 Deploy to GCP
  .github/workflows/deploy.yml
  app.yaml
  src/main/resources/config/application-cloud.yml
Labels: area: feature request :bulb:, generator: internal, generator: cloud

#10578 define preset json file name at spring boot application config
  src/main/java/tech/jhipster/lite/project/domain/resource/JHipsterPresetFile.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepository.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/JHipsterPresetFileProperties.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/JHipsterPresetFilePropertiesConfiguration.java
  src/main/resources/config/application.yml
  src/test/java/tech/jhipster/lite/cucumber/CucumberConfiguration.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/FakedJHipsterPresetFilePropertiesConfiguration.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepositoryTest.java
Labels: area: enhancement :wrench:, generator: internal

#10586 GCP: fix version tag
  .github/workflows/deploy.yml
Labels: area: bug :bug:, generator: internal

#10587 Revert "define preset json file name at spring boot application config"
  src/main/java/tech/jhipster/lite/project/domain/resource/JHipsterPresetFile.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepository.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/JHipsterPresetFileProperties.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/JHipsterPresetFilePropertiesConfiguration.java
  src/main/resources/config/application.yml
  src/test/java/tech/jhipster/lite/cucumber/CucumberConfiguration.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/FakedJHipsterPresetFilePropertiesConfiguration.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepositoryTest.java
Labels: area: bug :bug:, generator: internal

#10588 Revert "Update typescript-eslint monorepo to v8 (major)"
  src/main/resources/generator/dependencies/common/package.json
Labels: area: dependencies

#10589 GCP: update cors
  src/main/resources/config/application-cloud.yml
Labels: area: enhancement :wrench:, generator: internal

#10597 Switch to Kafka native image in KafkaTestContainer
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
  src/main/resources/generator/dependencies/Dockerfile
  src/test/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: broker, theme: tests

#10600 feat(typescript): generates the node project with the type "module"
  src/main/java/tech/jhipster/lite/generator/typescript/core/domain/TypescriptModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/typescript/domain/core/TypescriptModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: typescript

#10467 feat(packagejson): Use a proper typed enum for the package type
  src/main/java/tech/jhipster/lite/generator/client/react/security/jwt/domain/ReactJwtModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactory.java
  src/main/java/tech/jhipster/lite/generator/typescript/core/domain/TypescriptModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/packagejson/JHipsterModulePackageJson.java
  src/main/java/tech/jhipster/lite/module/domain/packagejson/NodeModuleFormat.java
  src/main/java/tech/jhipster/lite/module/domain/packagejson/PackageJsonType.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemPackageJsonHandler.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemPackageJsonHandlerTest.java
  src/test/resources/projects/node/package.json
Labels: generator: internal, area: refactoring

#10590 parametrize the preset json file name in the spring boot configuration
  src/main/java/tech/jhipster/lite/project/domain/resource/JHipsterPresetFile.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepository.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/JHipsterPresetFileProperties.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/JHipsterPresetFilePropertiesConfiguration.java
  src/main/resources/config/application.yml
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/FakedJHipsterPresetFilePropertiesConfiguration.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepositoryTest.java
Labels: area: enhancement :wrench:, generator: internal

#10609 Revert "parametrize the preset json file name in the spring boot configuration"
  src/main/java/tech/jhipster/lite/project/domain/resource/JHipsterPresetFile.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepository.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/JHipsterPresetFileProperties.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/JHipsterPresetFilePropertiesConfiguration.java
  src/main/resources/config/application.yml
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/FakedJHipsterPresetFilePropertiesConfiguration.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepositoryTest.java
Labels: area: triage

#10610 Set preset in Spring Config
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepository.java
  src/main/resources/config/application.yml
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepositoryTest.java
  src/test/resources/config/application-test.yml
Labels: area: enhancement :wrench:, generator: internal

#10611 Fix lint on React app
  src/main/resources/generator/client/common/cypress/src/test/webapp/component/.eslintrc.cjs
  src/main/resources/generator/client/react/.eslintrc.cjs
Labels: area: bug :bug:, client: react

#10624 CSS warnings
  src/main/style/atom/input/input-text/_input-text.scss
  src/main/style/atom/logo/_logo.scss
  src/main/style/atom/nav-item/_nav-item.scss
Labels: generator: internal, area: refactoring

#10625 Prettier: Format some files
  src/main/resources/generator/server/springboot/database/cassandra/CassandraJSR310DateConverters.java.mustache
  src/main/resources/generator/server/springboot/database/cassandra/cassandra.yml.mustache
  src/main/resources/generator/server/springboot/thymeleaf/template/documentation/thymeleaf.md.mustache
Labels: area: refactoring

#10623 feat(cypress): automatically start dev server before launching frontend component tests
  src/main/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactory.java
  src/main/resources/generator/dependencies/common/package.json
  src/test/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: tests

#10628 Playwright component tests improvements
  src/main/java/tech/jhipster/lite/generator/client/tools/playwright/domain/PlaywrightModuleFactory.java
  src/main/resources/generator/client/common/playwright/playwright.config.ts.mustache
  src/main/resources/generator/client/common/playwright/src/test/webapp/component/common/primary/app/Home-Page.ts
  src/test/java/tech/jhipster/lite/generator/client/tools/playwright/domain/PlaywrightModuleFactoryTest.java
  tests-ci/generate.sh
Labels: area: enhancement :wrench:, theme: tests

#10630 Prettier: Format some files
  src/main/resources/generator/server/springboot/broker/pulsar/PulsarConfigurationIT.java.mustache
  src/main/resources/generator/server/springboot/broker/pulsar/PulsarProperties.java.mustache
  src/main/resources/generator/server/springboot/database/cassandra/CassandraDatabaseConfiguration.java.mustache
  src/main/resources/generator/server/springboot/database/cassandra/CassandraJSR310DateConverters.java.mustache
  src/main/resources/generator/server/springboot/database/cassandra/CassandraJSR310DateConvertersTest.java.mustache
  src/main/resources/generator/server/springboot/database/cassandra/CassandraKeyspaceIT.java.mustache
  src/main/resources/generator/server/springboot/database/cassandra/TestCassandraManager.java.mustache
Labels: area: enhancement :wrench:

#10632 Bump Node to 20.17.0
  CONTRIBUTING.md
  pom.xml
Labels: area: enhancement :wrench:, generator: internal

#10631 Prettier: Format some files
  src/main/resources/generator/ci/github/actions/.github/workflows/github-actions-gradle.yml.mustache
  src/main/resources/generator/ci/gitlab/.gitlab-ci-gradle.yml.mustache
  src/main/resources/generator/server/sonar/sonar.md.mustache
  src/main/resources/generator/server/springboot/apidocumentation/springdocoauth/SpringdocOAuth2Configuration.java.mustache
  src/main/resources/generator/server/springboot/broker/kafka/KafkaProperties.java.mustache
  src/main/resources/generator/server/springboot/broker/kafka/SampleProducer.java.mustache
  src/main/resources/generator/server/springboot/custom-jhlite/main/FeatureSlug.java.mustache
  src/main/resources/generator/server/springboot/custom-jhlite/main/ModuleSlug.java.mustache
  src/main/resources/generator/server/springboot/dbmigration/mongock/MongockDatabaseConfiguration.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/account/main/domain/Account.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/account/main/infrastructure/primary/RestAccount.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/account/main/infrastructure/secondary/OAuth2AuthenticationReader.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/main/application/AuthenticatedUser.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/main/infrastructure/primary/ApplicationSecurityProperties.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/main/infrastructure/primary/OAuth2Configuration.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/useridentity/main/domain/Email.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/useridentity/main/domain/Firstname.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/useridentity/main/domain/Lastname.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/useridentity/main/domain/Name.java.mustache
Labels: area: refactoring

#10636 chore: remove redundant character escape in RegExp
  src/main/java/tech/jhipster/lite/generator/client/angular/security/oauth2/domain/AngularOauth2ModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactory.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/YamlFileSpringPropertiesHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/MavenDependenciesReader.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/npm/FileSystemNpmVersionReader.java
  src/test/java/tech/jhipster/lite/HexagonalArchTest.java
Labels: generator: internal, area: refactoring

#10637 Prettier: Format some files
  src/main/resources/generator/server/springboot/cucumberauthentication/oauth2/AuthenticationSteps.java.mustache
  src/main/resources/generator/server/springboot/custom-jhlite/test/CucumberConfiguration.java.mustache
  src/main/resources/generator/server/springboot/database/mongodb/test/TestMongoDBManager.java.mustache
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/ApplicationExceptionTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/account/test/domain/AccountsFixture.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/account/test/infrastructure/primary/RestAccountTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/test/application/AuthenticatedUserTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/test/infrastructure/primary/CustomClaimConverterTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/test/infrastructure/primary/JwtGrantedAuthorityConverterTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/test/infrastructure/primary/TestSecurityConfiguration.java.mustache
Labels: area: enhancement :wrench:

#10629 tests: ran generated frontend component tests in CI
  .github/workflows/github-actions.yml
  src/main/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactoryTest.java
  src/test/resources/projects/angular/angular.json
  tests-ci/generate.sh
Labels: area: enhancement :wrench:, generator: CI, theme: tests

#10638 Replace eslint-plugin-prettier usage by eslint-config-prettier
  .github/workflows/github-actions.yml
  .lintstagedrc.js
  .stylelintignore
  eslint.config.js
  package-lock.json
  package.json
  src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactory.java
  src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactory.java
  src/main/java/tech/jhipster/lite/generator/typescript/core/domain/TypescriptModuleFactory.java
  src/main/resources/generator/client/vue/.eslintrc.cjs
  src/main/resources/generator/dependencies/common/package.json
  src/main/resources/generator/dependencies/svelte/package.json
  src/main/resources/generator/dependencies/vue/package.json
  src/main/resources/generator/typescript/.eslintrc.cjs
  src/main/resources/generator/typescript/jest.config.js
  src/test/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/typescript/domain/core/TypescriptModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/npm/FileSystemNpmVersionReaderTest.java
Labels: area: enhancement :wrench:

#10646 Tikui: use jhlite-icon
  src/main/style/organism/landscape/landscape.mixin.pug
  src/main/style/organism/modules-patch/modules-patch.mixin.pug
Labels: area: enhancement :wrench:, generator: internal

#10645 Improve groups of jhipster-lite modules in Api documentation
  src/main/java/tech/jhipster/lite/generator/ci/renovate/infrastructure/primary/RenovateModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/angular/admin/health/infrastructure/primary/AngularHealthModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/angular/core/infrastructure/primary/AngularCoreModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/angular/security/jwt/infrastructure/primary/AngularJwtModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/angular/security/oauth2/infrastructure/primary/AngularOAuth2ModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/loader/infrastructure/primary/TsLoaderModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/pagination_domain/infrastructure/primary/TsPaginationDomainModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/react/core/infrastructure/primary/ReactCoreModulesConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/react/security/jwt/infrastructure/primary/ReactJwtModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/rest_pagination/infrastructure/primary/TSRestPaginationModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/svelte/core/infrastructure/primary/SvelteModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/vue/core/infrastructure/primary/VueModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/hexagonaldocumentation/infrastructure/primary/HexagonalArchitectureDocumentationModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/infrastructure/primary/FrontendJavaBuildToolModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/infrastructure/primary/KafkaModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/logging/logstash/infrastructure/primary/LogstashModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/cassandrapersistence/infrastructure/primary/SampleCassandraPersistenceModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/feature/infrastructure/primary/SampleFeatureModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/flyway/infrastructure/primary/SampleFlywayModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/jpapersistence/infrastructure/primary/SampleJpaPersistenceModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/liquibase/infrastructure/primary/SampleLiquibaseModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/mongopersistence/infrastructure/primary/SampleMongoDBPersistenceModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/technicaltools/gitinfo/infrastructure/primary/GitInfoModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/infrastructure/primary/SpringBootThymeleafModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/template/infrastructure/primary/ThymeleafTemplateModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/setup/codespaces/infrastructure/primary/CodespaceModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/setup/gitpod/infrastructure/primary/GitpodModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/setup/infinitest/infrastructure/primary/InfinitestModuleConfiguration.java
Labels: area: enhancement :wrench:, generator: internal

#10656 Release drafter: add breaking change section
  .github/release-drafter.yml
Labels: area: documentation :books:, generator: internal

#10648 Tikui: new organism (Project actions)
  src/main/style/organism/landscape/landscape.mixin.pug
  src/main/style/organism/modules-patch/modules-patch.mixin.pug
  src/main/style/organism/organism.pug
  src/main/style/organism/project-actions/project-actions.code.pug
  src/main/style/organism/project-actions/project-actions.md
  src/main/style/organism/project-actions/project-actions.mixin.pug
  src/main/style/organism/project-actions/project-actions.render.pug
Labels: area: enhancement :wrench:, generator: internal

#10661 Preset: improvements of default
  src/main/resources/preset.json
  src/main/style/atom/select/select.mixin.pug
  src/main/style/organism/landscape-preset-configuration/landscape-preset-configuration.mixin.pug
Labels: area: enhancement :wrench:, generator: internal

#10659 Dockerfile: use entrypoint instead of cmd
  Dockerfile
  src/main/resources/generator/server/springboot/docker/Dockerfile-gradle.mustache
  src/main/resources/generator/server/springboot/docker/Dockerfile-maven.mustache
Labels: area: bug :bug:, theme: docker :whale:

#10662 CI: format generate.sh
  tests-ci/generate.sh
Labels: generator: CI, area: refactoring

#10663 Fix: preset modules selected and deselected
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
  src/test/webapp/unit/module/domain/Modules.fixture.ts
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/webapp/unit/module/secondary/RestModulesRepository.spec.ts
Labels: generator: internal

#10664 feat: setup prettier-plugin-sh for automatically formatting shell scripts
  .lintstagedrc.js
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
  release.sh
  src/main/resources/generator/server/springboot/dbmigration/cassandra/autoMigrate.sh
  src/main/resources/generator/server/springboot/dbmigration/cassandra/execute-cql.sh
  tests-ci/sonar.sh
  tests-ci/start.sh
  tests-ci/start_docker_compose.sh
  tests-ci/start_docker_container.sh
  tests-ci/wait_sonar.sh
Labels: area: enhancement :wrench:, generator: internal

#10639 add react internationalization
  src/main/java/tech/jhipster/lite/generator/client/react/i18n/application/ReactI18nApplicationService.java
  src/main/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/react/i18n/infrastructure/primary/ReactI18nModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/react/i18n/package-info.java
  src/main/java/tech/jhipster/lite/generator/slug/domain/JHLiteFeatureSlug.java
  src/main/java/tech/jhipster/lite/generator/slug/domain/JHLiteModuleSlug.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
  src/main/resources/generator/client/common/reacti18n/src/main/webapp/app/i18n.ts.mustache
  src/main/resources/generator/client/common/reacti18n/src/main/webapp/assets/english.json.mustache
  src/main/resources/generator/client/common/reacti18n/src/main/webapp/assets/french.json.mustache
  src/main/resources/generator/client/react/i18n/src/main/webapp/app/i18n.ts
  src/main/resources/generator/client/react/i18n/src/main/webapp/assets/locales/en/translation.json
  src/main/resources/generator/client/react/i18n/src/main/webapp/assets/locales/fr/translation.json
  src/main/resources/generator/dependencies/common/package.json
  src/main/resources/generator/dependencies/react/package.json
  src/test/features/client/reacti18n.feature
  src/test/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/npm/FileSystemNpmVersionReaderTest.java
  src/test/resources/projects/react-app/App.spec.tsx
Labels: area: enhancement :wrench:, client: react, theme: client

#10668 React resources reorg
  src/main/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactory.java
  src/main/java/tech/jhipster/lite/generator/client/react/security/jwt/domain/ReactJwtModuleFactory.java
  src/main/resources/generator/client/common/reacti18n/src/main/webapp/app/i18n.ts.mustache
  src/main/resources/generator/client/common/reacti18n/src/main/webapp/assets/english.json.mustache
  src/main/resources/generator/client/common/reacti18n/src/main/webapp/assets/french.json.mustache
  src/main/resources/generator/client/react/core/.eslintrc.cjs
  src/main/resources/generator/client/react/core/src/main/webapp/app/common/primary/app/App.css.mustache
  src/main/resources/generator/client/react/core/src/main/webapp/app/common/primary/app/App.tsx.mustache
  src/main/resources/generator/client/react/core/src/main/webapp/app/index.css.mustache
  src/main/resources/generator/client/react/core/src/main/webapp/app/index.tsx.mustache
  src/main/resources/generator/client/react/core/src/main/webapp/app/vite-env.d.ts.mustache
  src/main/resources/generator/client/react/core/src/main/webapp/assets/JHipster-Lite-neon-blue.png
  src/main/resources/generator/client/react/core/src/main/webapp/assets/ReactLogo.png
  src/main/resources/generator/client/react/core/src/main/webapp/index.html.mustache
  src/main/resources/generator/client/react/core/src/test/webapp/unit/common/primary/app/App.spec.tsx.mustache
  src/main/resources/generator/client/react/core/src/test/webapp/unit/common/primary/app/App.test.tsx.mustache
  src/main/resources/generator/client/react/core/tsconfig.json
  src/main/resources/generator/client/react/core/vite.config.ts.mustache
  src/main/resources/generator/client/react/core/vitest.config.ts.mustache
  src/main/resources/generator/client/react/security/jwt/postcss.config.js
  src/main/resources/generator/client/react/security/jwt/src/main/webapp/app/common/primary/app/LoginApp.tsx.mustache
  src/main/resources/generator/client/react/security/jwt/src/main/webapp/app/common/services/storage.ts.mustache
  src/main/resources/generator/client/react/security/jwt/src/main/webapp/app/login/primary/loginForm/index.tsx.mustache
  src/main/resources/generator/client/react/security/jwt/src/main/webapp/app/login/primary/loginModal/EyeFilledIcon.tsx.mustache
  src/main/resources/generator/client/react/security/jwt/src/main/webapp/app/login/primary/loginModal/EyeSlashFilledIcon.tsx.mustache
  src/main/resources/generator/client/react/security/jwt/src/main/webapp/app/login/primary/loginModal/LoginModal.scss.mustache
  src/main/resources/generator/client/react/security/jwt/src/main/webapp/app/login/primary/loginModal/index.tsx.mustache
  src/main/resources/generator/client/react/security/jwt/src/main/webapp/app/login/primary/loginModal/interface.d.ts.mustache
  src/main/resources/generator/client/react/security/jwt/src/main/webapp/app/login/services/login.ts.mustache
  src/main/resources/generator/client/react/security/jwt/src/test/webapp/unit/common/services/storage.test.ts.mustache
  src/main/resources/generator/client/react/security/jwt/src/test/webapp/unit/login/primary/loginForm/index.test.tsx.mustache
  src/main/resources/generator/client/react/security/jwt/src/test/webapp/unit/login/primary/loginModal/index.test.tsx.mustache
  src/main/resources/generator/client/react/security/jwt/src/test/webapp/unit/login/services/login.test.ts.mustache
  src/main/resources/generator/client/react/security/jwt/tailwind.config.js
  src/test/features/client/react-i18n.feature
  src/test/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactoryTest.java
Labels: generator: internal, area: refactoring, client: react, theme: client

#10671 Fonts loaded twice on Tikui
  src/main/style/layout.pug
Labels: area: enhancement :wrench:, generator: internal

#10670 Fix: placeholder-loading not loaded
  src/main/style/layout.pug
  src/main/style/tikui.scss
  vite.config.ts
Labels: area: bug :bug:, generator: internal

#10672 Remove deprecated code
  src/main/java/tech/jhipster/lite/module/domain/packagejson/JHipsterModulePackageJson.java
Labels: generator: internal

#10673 Vue: meta description is missing
  src/main/resources/generator/client/vue/webapp/index.html.mustache
Labels: area: enhancement :wrench:, generator: internal

#10678 Angular 18.2.1
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#10680 Vue: fix contrast for accessibility
  src/main/resources/generator/client/vue/webapp/app/common/primary/homepage/HomepageVue.vue.mustache
Labels: area: enhancement :wrench:, client: vue

#10679 Frontend: update meta description
  src/main/resources/generator/client/angular/core/src/main/webapp/index.html.mustache
  src/main/resources/generator/client/react/core/src/main/webapp/index.html.mustache
  src/main/resources/generator/client/vue/webapp/index.html.mustache
Labels: area: enhancement :wrench:, client: vue, client: angular, client: react, theme: client

#10689 Frontend: update title tag
  src/main/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/tools/playwright/domain/PlaywrightModuleFactory.java
  src/main/resources/generator/client/angular/core/src/main/webapp/index.html.mustache
  src/main/resources/generator/client/common/cypress/common/primary/app/Home.spec.ts.mustache
  src/main/resources/generator/client/common/playwright/common/primary/app/Home.spec.ts.mustache
  src/main/resources/generator/client/react/core/src/main/webapp/index.html.mustache
  src/main/resources/generator/client/vue/webapp/index.html.mustache
Labels: area: enhancement :wrench:, client: vue, client: angular, client: react, theme: client

#10702 harmonize the css with the current jhipster-website design
  src/main/style/atom/button/_button.scss
  src/main/style/atom/select/_select.scss
  src/main/style/font/inter/Inter-Bold.ttf
  src/main/style/font/inter/Inter-Regular.ttf
  src/main/style/font/inter/Inter-SemiBold.ttf
  src/main/style/font/inter/inter.scss
  src/main/style/font/roboto/Roboto-Bold.ttf
  src/main/style/font/roboto/Roboto-Regular.ttf
  src/main/style/font/roboto/roboto.scss
  src/main/style/layout.pug
  src/main/style/molecule/field/field.code.pug
  src/main/style/organism/landscape-preset-configuration/_landscape-preset-configuration.scss
  src/main/style/organism/landscape-preset-configuration/landscape-preset-configuration.mixin.pug
  src/main/style/organism/modules-patch/_modules-patch.scss
  src/main/style/quark/_quark.scss
  src/main/style/root/_root.scss
  src/main/style/token/_colors.scss
  src/main/style/token/_fonts.scss
  src/main/style/token/_size.scss
  src/main/style/token/color/_brand.scss
Labels: area: feature request :bulb:, generator: internal
