Repository seed4j/seed4j, pull requests merged in 2024-10, with the labels that each got.

#11015 I18n modules in tests ci
  src/main/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/vue/i18n/domain/VueI18nModuleFactory.java
  src/main/resources/generator/client/common/i18n/Translations.ts
  src/main/resources/generator/client/common/i18n/i18n.spec.ts
  src/main/resources/generator/client/react/i18n/src/main/webapp/app/i18n.ts
  src/test/features/client/vue-i18n.feature
  src/test/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/vue/i18n/domain/VueI18nModuleFactoryTest.java
  src/test/resources/projects/react-app/vitest.config.ts.template
  tests-ci/generate.sh
Labels: area: enhancement :wrench:, generator: CI, client: react

#11031 Sonar-React: Rename this constant name to match the regular expression
  src/test/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactoryTest.java
Labels: area: enhancement :wrench:, client: react

#11032 Fix upgrade: org.testcontainers:testcontainers-bom to v1.20.2
  pom.xml
  src/main/resources/generator/dependencies/pom.xml
  src/main/resources/generator/server/springboot/database/cassandra/TestCassandraManager.java.mustache
Labels: area: dependencies

#11036 Add prettier pug plugin on Tikui
  src/main/java/tech/jhipster/lite/generator/client/tikui/domain/TikuiModuleFactory.java
  src/main/resources/generator/dependencies/common/package.json
  src/test/java/tech/jhipster/lite/generator/client/tikui/domain/TikuiModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: client

#11035 Upgrade sonarqube v10.7.0
  src/main/docker/sonar.yml
  src/main/resources/generator/dependencies/Dockerfile
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
  src/main/resources/generator/server/sonar/sonar-project.properties.mustache
  src/main/resources/generator/server/springboot/database/redis/TestRedisManager.java.mustache
  src/main/resources/generator/server/springboot/dbmigration/cassandra/Cassandra-Migration.Dockerfile.mustache
  src/main/resources/generator/server/springboot/dbmigration/cassandra/TestCassandraMigrationLoader.java.mustache
Labels: area: dependencies

#11049 Sonar: Fields that are only assigned in the constructor should be readonly
  src/main/webapp/app/module/secondary/RestManagementRepository.ts
Labels: area: enhancement :wrench:

#11060 Remove unused npm dependencies + only use one dependency type in npm sources
  src/main/resources/generator/dependencies/angular/package.json
  src/main/resources/generator/dependencies/common/package.json
  src/main/resources/generator/dependencies/react/package.json
  src/main/resources/generator/dependencies/svelte/package.json
  src/main/resources/generator/dependencies/vue/package.json
Labels: area: dependencies, area: refactoring

#11076 Revert zone.js 0.15.0
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies

#11093 Get a catch block error message with TypeScript
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/webapp/unit/module/primary/modules-patch/ModulesPatchComponent.spec.ts
Labels: area: enhancement :wrench:, generator: internal

#11088 add `vuejwtapp` and `vueoauth2app` at the matrix in `github-actions.yml`
  .github/workflows/github-actions.yml
  tests-ci/generate.sh
Labels: area: feature request :bulb:, theme: security, client: vue

#11040 Improve Tikui generated style
  src/main/java/tech/jhipster/lite/generator/client/tikui/domain/TikuiModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/file/JHipsterModuleFiles.java
  src/main/resources/generator/client/tikui/style/atom/_atom.scss.mustache
  src/main/resources/generator/client/tikui/style/atom/atom.pug.mustache
  src/main/resources/generator/client/tikui/style/atom/page-title/_page-title.scss.mustache
  src/main/resources/generator/client/tikui/style/atom/page-title/page-title.code.pug.mustache
  src/main/resources/generator/client/tikui/style/atom/page-title/page-title.md.mustache
  src/main/resources/generator/client/tikui/style/atom/page-title/page-title.mixin.pug.mustache
  src/main/resources/generator/client/tikui/style/atom/page-title/page-title.render.pug.mustache
  src/main/resources/generator/client/tikui/style/atom/paragraph/_paragraph.scss.mustache
  src/main/resources/generator/client/tikui/style/atom/paragraph/paragraph.code.pug.mustache
  src/main/resources/generator/client/tikui/style/atom/paragraph/paragraph.md.mustache
  src/main/resources/generator/client/tikui/style/atom/paragraph/paragraph.mixin.pug.mustache
  src/main/resources/generator/client/tikui/style/atom/paragraph/paragraph.render.pug.mustache
  src/main/resources/generator/client/tikui/style/molecule/_molecule.scss.mustache
  src/main/resources/generator/client/tikui/style/molecule/molecule.pug.mustache
  src/main/resources/generator/client/tikui/style/molecule/toast/_toast.scss.mustache
  src/main/resources/generator/client/tikui/style/molecule/toast/toast.code.pug.mustache
  src/main/resources/generator/client/tikui/style/molecule/toast/toast.md.mustache
  src/main/resources/generator/client/tikui/style/molecule/toast/toast.mixin.pug.mustache
  src/main/resources/generator/client/tikui/style/molecule/toast/toast.render.pug.mustache
  src/main/resources/generator/client/tikui/style/organism/_organism.scss.mustache
  src/main/resources/generator/client/tikui/style/organism/columns/_columns.scss.mustache
  src/main/resources/generator/client/tikui/style/organism/columns/columns.code.pug.mustache
  src/main/resources/generator/client/tikui/style/organism/columns/columns.md.mustache
  src/main/resources/generator/client/tikui/style/organism/columns/columns.mixin.pug.mustache
  src/main/resources/generator/client/tikui/style/organism/columns/columns.render.pug.mustache
  src/main/resources/generator/client/tikui/style/organism/organism.pug.mustache
  src/main/resources/generator/client/tikui/style/organism/toasts/_toasts.scss.mustache
  src/main/resources/generator/client/tikui/style/organism/toasts/toasts.code.pug.mustache
  src/main/resources/generator/client/tikui/style/organism/toasts/toasts.md.mustache
  src/main/resources/generator/client/tikui/style/organism/toasts/toasts.mixin.pug.mustache
  src/main/resources/generator/client/tikui/style/organism/toasts/toasts.render.pug.mustache
  src/main/resources/generator/client/tikui/style/template/_template.scss.mustache
  src/main/resources/generator/client/tikui/style/template/template-page/_template-page.scss.mustache
  src/main/resources/generator/client/tikui/style/template/template-page/template-page.code.pug.mustache
  src/main/resources/generator/client/tikui/style/template/template-page/template-page.md.mustache
  src/main/resources/generator/client/tikui/style/template/template-page/template-page.mixin.pug.mustache
  src/main/resources/generator/client/tikui/style/template/template-page/template-page.render.pug.mustache
  src/main/resources/generator/client/tikui/style/template/template.pug.mustache
  src/main/resources/generator/client/tikui/style/template/toasting/_toasting.scss.mustache
  src/main/resources/generator/client/tikui/style/template/toasting/toasting.code.pug.mustache
  src/main/resources/generator/client/tikui/style/template/toasting/toasting.md.mustache
  src/main/resources/generator/client/tikui/style/template/toasting/toasting.mixin.pug.mustache
  src/main/resources/generator/client/tikui/style/template/toasting/toasting.render.pug.mustache
  src/main/resources/generator/client/tikui/style/tikui.scss.mustache
  src/main/resources/generator/client/tikui/style/token/_color.scss.mustache
  src/main/resources/generator/client/tikui/style/token/_radius.scss.mustache
  src/main/resources/generator/client/tikui/style/variables/_breakpoint.scss.mustache
  src/test/java/tech/jhipster/lite/generator/client/tikui/domain/TikuiModuleFactoryTest.java
Labels: area: enhancement :wrench:, area: feature request :bulb:, $$ bug-bounty $$, $500, theme: client

#10949 Generator: add missing test for WindowApplicationListener
  src/test/webapp/unit/shared/alert/infrastructure/primary/WindowApplicationListener.spec.ts
  vitest.config.ts
Labels: area: enhancement :wrench:, generator: internal, theme: tests

#11061 fix(arch-tests): allow wire packages to depend on shared kernels
  src/main/resources/generator/server/javatool/archunit/test/HexagonalArchTest.java.mustache
Labels: area: enhancement :wrench:, theme: tests

#11096 Enable tikui module
  src/main/resources/config/application.yml
  src/test/webapp/unit/shared/alert/infrastructure/primary/WindowApplicationListener.spec.ts
  tests-ci/generate.sh
Labels: area: enhancement :wrench:, theme: client

#11097 Typo: needed as a participle seems unnatural
  src/main/resources/generator/server/springboot/logsspy/logs-spy.md
Labels: area: enhancement :wrench:

#11101 fix(jqassistant): execute maven plugin on verify phase
  src/main/java/tech/jhipster/lite/generator/server/documentation/jqassistant/domain/JQAssistantModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/server/documentation/jqassistant/domain/JQAssistantModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: docs

#11105 Disable sonar rule: Circular dependencies between classes in the same package should be resolved
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
  src/main/resources/generator/server/sonar/sonar-project.properties.mustache
Labels: area: enhancement :wrench:, theme: security, server: spring boot

#11120 Upgrade Angular 18.2.8
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#11121 feat(liquibase): use changelog path from LiquibaseProperties rather than injecting it with @Value
  src/main/resources/generator/server/springboot/dbmigration/liquibase/main/LiquibaseConfiguration.java.mustache
Labels: area: enhancement :wrench:, server: spring boot, theme: database migration

#11131 Upgrade Piqure v2.1.1
  package-lock.json
  package.json
  src/main/resources/generator/dependencies/common/package.json
Labels: area: dependencies

#11136 Reformat pug files (for generated app) with prettier
  src/main/resources/generator/client/tikui/style/atom/atom.pug.mustache
  src/main/resources/generator/client/tikui/style/atom/button/button.mixin.pug.mustache
  src/main/resources/generator/client/tikui/style/atom/input-text/input-text.mixin.pug.mustache
  src/main/resources/generator/client/tikui/style/atom/label/label.mixin.pug.mustache
  src/main/resources/generator/client/tikui/style/index.pug.mustache
  src/main/resources/generator/client/tikui/style/layout-documentation.pug.mustache
  src/main/resources/generator/client/tikui/style/layout.pug.mustache
  src/main/resources/generator/client/tikui/style/molecule/field/field.mixin.pug.mustache
  src/main/resources/generator/client/tikui/style/molecule/molecule.pug.mustache
  src/main/resources/generator/client/tikui/style/organism/lines/lines.mixin.pug.mustache
Labels: area: enhancement :wrench:

#11137 Reformat angular files with prettier
  src/main/resources/generator/client/angular/core/src/main/webapp/app/app.component.spec.ts.mustache
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/auth/oauth2-auth.service.spec.ts.mustache
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/auth/oauth2-auth.service.ts.mustache
Labels: area: enhancement :wrench:, client: angular

#11141 Align JHLite properties
  src/main/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactory.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterPresetRepository.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterHiddenResourcesProperties.java
  src/main/java/tech/jhipster/lite/shared/projectfolder/infrastructure/primary/ProjectFolderConfiguration.java
  src/main/resources/config/application-angular.yml
  src/main/resources/config/application-cloud.yml
  src/main/resources/config/application-react.yml
  src/main/resources/config/application-vue.yml
  src/main/resources/config/application.yml
  src/main/resources/generator/server/springboot/custom-jhlite/module-creation.md.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/shared/projectfolder/infrastructure/primary/ForcedProjectFolderPrefixIT.java
  src/test/resources/config/application-test.yml
Labels: generator: internal, area: refactoring, area: breaking change

#11145 Reformat react files with prettier
  src/main/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactory.java
Labels: area: enhancement :wrench:

#11143 Reformat vue files with prettier
  src/main/resources/generator/client/common/playwright/common/primary/app/Home.spec.ts.mustache
  src/main/resources/generator/client/common/playwright/playwright.config.ts.mustache
  src/main/resources/generator/client/vue/security/jwt/webapp/app/auth/application/AuthProvider.ts.mustache
  src/main/resources/generator/client/vue/security/jwt/webapp/app/auth/domain/AuthRepository.ts.mustache
  src/main/resources/generator/client/vue/security/jwt/webapp/app/test/webapp/unit/auth/application/AuthProvider.spec.ts.mustache
Labels: area: enhancement :wrench:

#11144 Variables should not be shadowed
  src/main/resources/generator/client/common/i18n/Translations.ts
Labels: area: enhancement :wrench:, generator: internal

#11150 Lint-staged for pug in tikui
  src/main/java/tech/jhipster/lite/generator/client/tikui/domain/TikuiModuleFactory.java
Labels: area: enhancement :wrench:, theme: client

#11159 Add lint-staged for css/scss in tikui module
  src/main/java/tech/jhipster/lite/generator/client/tikui/domain/TikuiModuleFactory.java
Labels: area: enhancement :wrench:, theme: client

#11161 Remove useless exclusion in tsconfig
  src/main/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactoryTest.java
  src/test/resources/projects/ts-config-with-cypress-component-exclusions/tsconfig.json
  src/test/resources/projects/ts-config-with-cypress-e2e-exclusions/tsconfig.json
  src/test/resources/projects/ts-config-with-empty-exclusions/tsconfig.json
  src/test/resources/projects/ts-config-with-exclusions/tsconfig.json
Labels: theme: client

#11113 fix: lazily run npm install when applying 'prettier' and client modules
  src/main/java/tech/jhipster/lite/generator/client/angular/core/application/AngularApplicationService.java
  src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/react/core/application/ReactCoreApplicationService.java
  src/main/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactory.java
  src/main/java/tech/jhipster/lite/generator/client/svelte/core/application/SvelteApplicationService.java
  src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/vue/core/application/VueApplicationService.java
  src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactory.java
  src/main/java/tech/jhipster/lite/generator/prettier/application/PrettierApplicationService.java
  src/main/java/tech/jhipster/lite/generator/prettier/domain/PrettierModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/typescript/core/application/TypescriptApplicationService.java
  src/main/java/tech/jhipster/lite/generator/typescript/core/domain/TypescriptModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/npm/NpmLazyInstaller.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/npm/FileSystemNpmLazyInstaller.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/npm/NpmErrorKey.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/npm/NpmInstallException.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/NpmInstallationType.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/ProjectFormatterConfiguration.java
  src/main/java/tech/jhipster/lite/shared/npmdetector/infrastructure/secondary/NpmInstallationReader.java
  src/main/java/tech/jhipster/lite/shared/npmdetector/infrastructure/secondary/NpmInstallationType.java
  src/main/java/tech/jhipster/lite/shared/npmdetector/package-info.java
  src/main/resources/messages/errors/generator-errors-messages.properties
  src/main/resources/messages/errors/generator-errors-messages_fr.properties
  src/test/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/prettier/domain/PrettierModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/typescript/domain/core/TypescriptModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/npm/NoopNpmLazyInstaller.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/ProjectFormatterConfigurationTest.java
Labels: area: bug :bug:, theme: client

#11151 add search module bar into landscape screen
  src/main/style/atom/chip/_chip.scss
  src/main/style/organism/landscape/_landscape.scss
  src/main/style/token/_colors.scss
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
  src/main/webapp/app/module/primary/landscape/Landscape.html
  src/main/webapp/app/module/primary/landscape/LandscapeScroller.ts
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/webapp/unit/module/primary/landscape/LandscapeScroller.spec.ts
Labels: area: feature request :bulb:, generator: internal

#11175 Typo: emphasisize=>emphasize
  src/main/webapp/app/module/primary/landscape-module/LandscapeModule.component.ts
  src/main/webapp/app/module/primary/landscape-module/LandscapeModule.html
Labels: area: enhancement :wrench:

#11184 Fix upgrade dependency org.apache.pulsar:pulsar-client to v4.0.0
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/domain/PulsarModuleFactory.java
  src/main/resources/generator/dependencies/pom.xml
  src/test/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/domain/PulsarModuleFactoryTest.java
Labels: area: dependencies

#11191 Typo: selectabled=>selectable
  src/main/style/atom/chip/chip.mixin.pug
Labels: area: enhancement :wrench:

#11192 Typo: unmatching=>non-matching
  src/main/resources/generator/typescript/test/webapp/unit/common/domain/optional/Optional.spec.ts
Labels: area: enhancement :wrench:, theme: tests

#11190 feat(approval-tests): git ignore received.txt files
  .gitignore
  src/main/java/tech/jhipster/lite/generator/server/javatool/approvaltesting/domain/ApprovalTestingModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/server/javatool/approvaltesting/domain/ApprovalTestingModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: tests

#11197 Remove multiple space
  src/main/resources/generator/server/springboot/dbmigration/cassandra/Cassandra-Migration.Dockerfile.mustache
Labels: area: refactoring

#11142 Fix vitest config after prettier format to allow applying front modules
  src/main/resources/generator/typescript/vitest.config.ts.mustache
  src/test/resources/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.shouldBuildModuleWithStyle.vitest.config.ts.approved.txt
  src/test/resources/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.shouldCreateVueModule.vitest.config.ts.approved.txt
Labels: area: bug :bug:, theme: client

#11198 Some fixes
  src/main/java/tech/jhipster/lite/module/domain/replacement/EndOfFileReplacer.java
  src/main/resources/generator/client/angular/admin/src/main/webapp/app/admin/health/modal/health-modal.component.spec.ts.mustache
  src/main/resources/generator/client/angular/admin/src/main/webapp/app/admin/health/modal/health-modal.component.ts.mustache
  src/main/resources/generator/client/common/hexagonal-documentation/front-hexagonal-architecture.md.mustache
Labels: area: enhancement :wrench:

#11209 Bump dependencies
  package-lock.json
  package.json
  pom.xml
Labels: area: dependencies

#11212 Some fixes
  src/test/java/tech/jhipster/lite/shared/collection/domain/JHipsterCollectionsTest.java
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/webapp/unit/module/primary/modules-patch/ModulesPatchComponent.spec.ts
Labels: area: enhancement :wrench:

#11213 Some fixes
  src/main/resources/messages/assertions-errors/assertion-errors-messages_fr.properties
  src/main/webapp/app/module/primary/landscape/LandscapeNavigation.ts
  src/test/features/client/tikui.feature
Labels: area: enhancement :wrench:

#11224 Some fixes
  src/main/resources/generator/client/vue/documentation/vue-jwt-authentication-components.md.mustache
Labels: area: enhancement :wrench:

#11225 Angular: import can be shortened
  src/main/resources/generator/client/angular/admin/src/main/webapp/app/admin/health/health.service.spec.ts.mustache
  src/main/resources/generator/client/angular/admin/src/main/webapp/app/admin/health/health.service.ts.mustache
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/login/login.component.ts.mustache
Labels: area: enhancement :wrench:, client: angular

#11233 feat(approval-tests): suppress warnings on PackageSettings
  sonar-project.properties
  src/main/resources/generator/server/javatool/approvaltesting/test/PackageSettings.java.mustache
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
  src/main/resources/generator/server/sonar/sonar-project.properties.mustache
  src/test/java/tech/jhipster/lite/PackageSettings.java
Labels: area: enhancement :wrench:, theme: tests

#11234 Upgrade Angular 18.2.9
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#11242 React: remove unused property
  src/main/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactory.java
Labels: area: enhancement :wrench:, client: react

#11248 Some typo fixes
  src/test/features/sample-feature.feature
  src/test/java/tech/jhipster/lite/shared/collection/domain/JHipsterCollectionsTest.java
  src/test/webapp/unit/module/primary/modules-patch/ModulesPatchComponent.spec.ts
Labels: generator: internal, area: refactoring

#11249 chore(deps): allow node 22 that is now the LTS version
  renovate.json
Labels: area: dependencies

#11251 Bump Node to 22.11.0
  CONTRIBUTING.md
  pom.xml
Labels: area: dependencies

#11250 Some fixes
  pom.xml
  src/test/webapp/unit/module/secondary/LocalStorageModuleParametersRepository.spec.ts
Labels: generator: internal, area: refactoring

#11236 Sonar: ignore Sections of code should not be commented out
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
  src/main/resources/generator/server/sonar/sonar-project.properties.mustache
Labels: area: enhancement :wrench:

#11210 Pulsar: use spring-boot-starter-pulsar
  src/main/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/domain/PulsarModuleFactory.java
  src/main/resources/generator/dependencies/pom.xml
  src/test/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/domain/PulsarModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: broker

#11257 Fix typo: goback=>go back
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
Labels: area: enhancement :wrench:
