Repository seed4j/seed4j, pull requests merged in 2024-06, with the labels that each got.

#9972 enh: use "release" configuration for setting java version rather than "source" and "target"
  pom.xml
  src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/MavenModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/buildtool/maven/domain/MavenModuleFactoryTest.java
  src/test/resources/generator/buildtool/maven/pom.test.xml
  src/test/resources/projects/init-maven/pom.xml
Labels: area: enhancement :wrench:, theme: maven

#9971 chore: simplify code by using Optional::stream
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeFeature.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/docker/FileSystemDockerImagesReader.java
Labels: generator: internal, area: refactoring

#9882 Angular 18
  src/main/resources/generator/client/angular/admin/src/main/webapp/app/admin/health/health.component.spec.ts.mustache
  src/main/resources/generator/client/angular/admin/src/main/webapp/app/admin/health/health.service.spec.ts.mustache
  src/main/resources/generator/client/angular/core/angular.json.mustache
  src/main/resources/generator/client/angular/core/src/main/webapp/index.html.mustache
  src/main/resources/generator/client/angular/core/tsconfig.json
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/auth/account.service.spec.ts.mustache
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/auth/auth-jwt.service.spec.ts.mustache
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/auth/auth.interceptor.spec.ts.mustache
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/login/login.component.spec.ts.mustache
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/login/login.service.spec.ts.mustache
  src/main/resources/generator/dependencies/angular/package.json
  src/test/resources/projects/angular/angular.json
  src/test/resources/projects/angular/empty-angular.json
Labels: area: dependencies, client: angular, $$ bug-bounty $$, $200

#9990 enh(spring-properties): use a TreeMap rather than an HashMap to store properties
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/cassandra/domain/CassandraModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/jwt/domain/JwtBasicAuthModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/javaproperties/JHipsterModuleSpringProperties.java
  src/main/java/tech/jhipster/lite/module/domain/javaproperties/PropertyKey.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocauth0/domain/SpringDocAuth0ModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdoccore/domain/SpringdocModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocoauth/domain/SpringDocOauth2ModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocokta/domain/SpringDocOktaModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/async/domain/SpringBootAsyncModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/cache/ehcache/domain/EHCacheModulesFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootCoreModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/cassandra/domain/CassandraModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/mariadb/domain/MariaDBModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/mssql/domain/MsSQLModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQLModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/domain/Neo4jModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/postgresql/domain/PostgresqlModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/redis/domain/RedisModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/devtools/domain/DevToolsModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/logging/logstash/domain/LogstashModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/security/jwt/domain/JwtBasicAuthModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/core/domain/OAuth2ModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/springcloud/configclient/domain/SpringCloudConfigModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/springcloud/consul/domain/ConsulModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/springcloud/eureka/domain/EurekaModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/springcloud/gateway/domain/GatewayModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/technicaltools/actuator/domain/SpringBootActuatorModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/technicaltools/gitinfo/domain/GitInfoModuleFactoryTest.java
Labels: area: enhancement :wrench:, server: spring boot

#9921 safely remove property version when removing dependency
  src/main/java/tech/jhipster/lite/module/domain/javadependency/DirectJavaDependency.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/JavaDependency.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/JavaDependencyCommandsCreator.java
  src/main/java/tech/jhipster/lite/module/domain/javadependency/JavaDependencyManagement.java
  src/main/java/tech/jhipster/lite/module/domain/mavenplugin/JHipsterModuleMavenPlugins.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MavenCommandHandler.java
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModulesFixture.java
  src/test/java/tech/jhipster/lite/module/domain/javadependency/DirectJavaDependencyTest.java
  src/test/java/tech/jhipster/lite/module/domain/javadependency/JavaDependencyManagementTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModulesRepositoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterModulesAssertions.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MavenCommandHandlerTest.java
  src/test/resources/projects/maven-with-multiple-dependencies-management/pom.xml
  src/test/resources/projects/maven-with-multiple-dependencies/pom.xml
Labels: area: enhancement :wrench:, generator: internal, theme: maven

#10013 Remove unused dependency: stylelint-config-standard
  package-lock.json
  package.json
Labels: area: enhancement :wrench:, area: dependencies

#10014 React: remove unused dependency
  src/main/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactory.java
  src/main/resources/generator/dependencies/react/package.json
  src/test/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.java
Labels: area: enhancement :wrench:, area: dependencies, client: react

#10016 fix: StatisticsCriteria should use the more abstract JHipsterModuleSlug
  src/main/java/tech/jhipster/lite/statistic/domain/criteria/StatisticsCriteria.java
  src/main/java/tech/jhipster/lite/statistic/infrastructure/secondary/InMemoryStatisticsRepository.java
  src/main/java/tech/jhipster/lite/statistic/infrastructure/secondary/MongoDBStatisticsRepository.java
Labels: area: enhancement :wrench:, generator: internal

#10017 chore(deps): use common npm dependencies, and deleted duplicated react dependencies
  src/main/java/tech/jhipster/lite/generator/client/react/security/jwt/domain/ReactJwtModuleFactory.java
  src/main/resources/generator/dependencies/react/package.json
Labels: area: enhancement :wrench:, generator: internal, area: dependencies, client: react

#10021 Sonar: Use concise character class syntax '\d' instead of '[0-9]'
  src/main/resources/generator/server/javatool/base/test/ReplaceCamelCase.java.mustache
  src/test/java/tech/jhipster/lite/ReplaceCamelCase.java
Labels: area: enhancement :wrench:

#10020 Sonar: Remove useless curly braces around statement
  src/main/resources/generator/server/springboot/mvc/web/test/BeanValidationTest.java.mustache
Labels: area: enhancement :wrench:

#10022 React: bump @testing-library/react from 15.0.7 to 16.0.0
  src/main/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactory.java
  src/main/resources/generator/dependencies/react/package.json
  src/test/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.java
Labels: area: dependencies

#10015 Vue: use standart vite/vitest gonfig file extension
  src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactory.java
  src/main/resources/generator/client/vue/.eslintrc.cjs
  src/main/resources/generator/client/vue/vite.config.ts.mustache
  src/main/resources/generator/client/vue/vitest.config.ts.mustache
  src/test/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.java
Labels: area: enhancement :wrench:, client: vue

#10026 React: recommend using act with await and an async function
  src/main/resources/generator/client/react/src/test/javascript/spec/login/primary/loginModal/index.test.tsx.mustache
Labels: area: enhancement :wrench:, client: react

#10033 Sonar: Control structures should use curly braces
  src/main/resources/generator/client/react/src/main/webapp/app/login/primary/loginModal/index.tsx.mustache
Labels: area: enhancement :wrench:, client: react

#10023 feat(custom-jhlite): add shell scripts for helping testing generated apps in ci
  src/main/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactory.java
  src/main/java/tech/jhipster/lite/module/domain/file/JHipsterModuleFiles.java
  src/main/resources/generator/server/springboot/custom-jhlite/tests-ci/generate.sh.mustache
  src/main/resources/generator/server/springboot/custom-jhlite/tests-ci/modulePayload.json.mustache
  src/main/resources/generator/server/springboot/custom-jhlite/tests-ci/start.sh.mustache
  src/main/resources/generator/server/springboot/custom-jhlite/tests-ci/stop.sh
  src/test/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactoryTest.java
Labels: area: enhancement :wrench:, generator: internal

#10035 Sonar: Loggers should be private static final and should share a naming convention
  src/main/resources/generator/server/springboot/mvc/web/main/cors/CorsFilterConfiguration.java.mustache
Labels: area: enhancement :wrench:

#10046 fix(ci): prevent code injection by using the commit message or the pu…
  .github/workflows/github-actions.yml
Labels: area: bug :bug:, theme: CI

#10036 fix(deps): bump tikui-core to v4.1.1
  package-lock.json
  package.json
Labels: area: dependencies

#10024 feat(bean-validation-test): simplify code
  src/main/resources/generator/server/springboot/mvc/web/test/BeanValidationTest.java.mustache
Labels: area: enhancement :wrench:, server: java, area: refactoring

#10053 feat(custom-jhlite): generate slug shared kernel with feature and module enum slugs skeleton
  src/main/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactory.java
  src/main/resources/generator/server/springboot/custom-jhlite/main/FeatureSlug.java.mustache
  src/main/resources/generator/server/springboot/custom-jhlite/main/ModuleSlug.java.mustache
  src/main/resources/generator/server/springboot/custom-jhlite/main/package-info.java.mustache
  src/main/resources/generator/server/springboot/custom-jhlite/test/CucumberConfiguration.java.mustache
  src/main/resources/generator/server/springboot/custom-jhlite/test/CucumberTest.java.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactoryTest.java
Labels: area: enhancement :wrench:

#10061 Declaration can have 'final' modifier
  src/main/resources/generator/server/springboot/logsspy/test/LogsSpyExtension.java.mustache
Labels: area: enhancement :wrench:

#10067 remove banner modules
  src/main/java/tech/jhipster/lite/generator/server/springboot/banner/application/BannerApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/banner/domain/BannerModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/banner/infrastructure/primary/BannerModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/banner/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/slug/domain/JHLiteFeatureSlug.java
  src/main/java/tech/jhipster/lite/generator/slug/domain/JHLiteModuleSlug.java
  src/main/resources/config/application.yml
  src/main/resources/generator/server/springboot/banner/banner-jhipster-v2.txt
  src/main/resources/generator/server/springboot/banner/banner-jhipster-v3.txt
  src/main/resources/generator/server/springboot/banner/banner-jhipster-v7-react.txt
  src/main/resources/generator/server/springboot/banner/banner-jhipster-v7-vue.txt
  src/main/resources/generator/server/springboot/banner/banner-jhipster-v7.txt
  src/test/features/server/springboot/banner.feature
  src/test/java/tech/jhipster/lite/generator/server/springboot/banner/domain/BannerModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/customjhlite/domain/CustomJHLiteModuleFactoryTest.java
Labels: generator: internal

#10068 Variable element initializer null is redundant
  src/main/resources/generator/server/springboot/cucumber/rest/CucumberRestTestContext.java.mustache
Labels: area: enhancement :wrench:

#10070 Unnecessary unboxing
  src/main/resources/generator/server/javatool/base/main/error/Assert.java.mustache
Labels: area: enhancement :wrench:

#10069 Use 'a' before a consonant sound
  src/main/resources/generator/server/springboot/mvc/security/jwt/authentication/main/application/AuthenticatedUser.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/main/application/AuthenticatedUser.java.mustache
Labels: area: enhancement :wrench:, server: java

#10025 chore(eslint): apply eslint on whole sources
  src/main/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactory.java
  src/main/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactory.java
  src/main/resources/generator/client/common/cypress/src/test/javascript/integration/.eslintrc.cjs
  src/test/features/client/browser-test/cypress.feature
  src/test/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.java
Labels: area: enhancement :wrench:, theme: client

#9172 jMolecules and jQAssistant (living) documentation modules
  src/main/java/tech/jhipster/lite/generator/server/documentation/jmolecules/application/JMoleculesApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/documentation/jmolecules/domain/JMoleculesModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/documentation/jmolecules/infrastructure/primary/JMoleculesModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/documentation/jmolecules/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/documentation/jqassistant/application/JQAssistantApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/documentation/jqassistant/domain/JQAssistantModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/documentation/jqassistant/infrastructure/primary/JQAssistantModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/slug/domain/JHLiteModuleSlug.java
  src/main/resources/generator/dependencies/pom.xml
  src/main/resources/generator/server/documentation/jqassistant/.jqassistant.yml
  src/main/resources/generator/server/javatool/archunit/test/HexagonalArchTest.java.mustache
  src/test/features/server/documentation/jmolecules.feature
  src/test/features/server/documentation/jqassistant.feature
  src/test/java/tech/jhipster/lite/generator/server/documentation/jmolecules/domain/JMoleculesModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/documentation/jqassistant/domain/JQAssistantModuleFactoryTest.java
  tests-ci/generate.sh
Labels: area: feature request :bulb:, $$ bug-bounty $$, $200, theme: docs

#10074 OAuth2 module: improve custom name, instead of using jhipster
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/core/domain/OAuth2ModuleFactory.java
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/docker/jhipster-realm.json.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/core/domain/OAuth2ModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: security, server: spring boot

#10075 UI: hide minimap by default
  src/main/webapp/app/module/primary/landscape-minimap/LandscapeMiniMap.component.ts
  src/test/webapp/unit/module/primary/landscape/LandscapeMiniMapComponent.spec.ts
Labels: area: enhancement :wrench:, generator: internal

#10085 Docker compose version is obsolete
  src/main/docker/sonar.yml
  src/main/resources/generator/server/sonar/sonar.yml.mustache
  src/main/resources/generator/server/springboot/broker/kafka/akhq.yml.mustache
  src/main/resources/generator/server/springboot/broker/kafka/kafka.yml.mustache
  src/main/resources/generator/server/springboot/database/cassandra/cassandra.yml.mustache
  src/main/resources/generator/server/springboot/database/mariadb/mariadb.yml.mustache
  src/main/resources/generator/server/springboot/database/mongodb/mongodb.yml.mustache
  src/main/resources/generator/server/springboot/database/mysql/mysql.yml.mustache
  src/main/resources/generator/server/springboot/database/neo4j/neo4j.yml.mustache
  src/main/resources/generator/server/springboot/database/postgresql/postgresql.yml.mustache
  src/main/resources/generator/server/springboot/database/redis/redis.yml.mustache
  src/main/resources/generator/server/springboot/dbmigration/cassandra/cassandra-migration.yml
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/docker/keycloak.yml.mustache
  src/main/resources/generator/server/springboot/springcloud/configclient/jhipster-registry.yml.mustache
  src/main/resources/generator/server/springboot/springcloud/consul/src/consul.yml.mustache
Labels: area: enhancement :wrench:, theme: docker :whale:

#10086 Docker compose version is obsolete
  src/main/resources/generator/server/springboot/broker/pulsar/pulsar.yml.mustache
  src/main/resources/generator/server/springboot/database/mssql/mssql.yml.mustache
Labels: area: enhancement :wrench:, theme: docker :whale:

#10084 Sonar: reactivate S2699 rule
  sonar-project.properties
  src/test/webapp/unit/http/AxiosHttp.spec.ts
Labels: area: enhancement :wrench:, generator: internal

#10098 Angular 18: bump @angular-builders/jest 18.0.0
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#10099 Sonar: reactivate S2699 rule
  src/main/resources/generator/client/react/src/test/javascript/spec/common/primary/app/App.spec.tsx.mustache
  src/main/resources/generator/client/react/src/test/javascript/spec/common/primary/app/App.test.tsx.mustache
  src/main/resources/generator/client/react/src/test/javascript/spec/login/primary/loginForm/index.test.tsx.mustache
  src/main/resources/generator/client/react/src/test/javascript/spec/login/primary/loginModal/index.test.tsx.mustache
  src/main/resources/generator/client/vue/test/spec/http/AxiosHttp.spec.ts.mustache
  src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache
  src/main/resources/generator/server/sonar/sonar-project.properties.mustache
Labels: area: enhancement :wrench:, theme: client

#10128 Improve logs when using JHLite
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModulesApplyer.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModuleFiles.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/git/JGitGitRepository.java
  src/test/features/modules.feature
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/git/JGitGitRepositoryTest.java
Labels: area: enhancement :wrench:, generator: internal

#10118 feat: introduce a new ElementReplacer dedicated to insert text at end of file
  src/main/java/tech/jhipster/lite/module/domain/replacement/EndOfFileReplacer.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemGitIgnoreHandler.java
  src/test/java/tech/jhipster/lite/module/domain/replacement/EndOfFileReplacerTest.java
Labels: area: enhancement :wrench:, generator: internal

#10130 Bug: deleted files are not committed
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/git/JGitGitRepository.java
Labels: area: bug :bug:, generator: internal

#10132 Bump Node to 20.15.0
  CONTRIBUTING.md
  pom.xml
Labels: area: dependencies

#10133 Bump Node to 20.15.0 for generated project
  src/main/resources/generator/dependencies/common/package.json
Labels: area: dependencies

#10143 fix: prevent OutOfMemory while writing pom.xml when using indentation > 2
  pom.xml
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MavenCommandHandler.java
Labels: area: bug :bug:, theme: maven

#10153 chore: remove @Autowired annotations in Cucumber configuration and steps
  src/main/resources/generator/server/springboot/cucumber/CucumberConfiguration.java.mustache
  src/main/resources/generator/server/springboot/cucumber/CucumberJpaReset.java.mustache
  src/main/resources/generator/server/springboot/cucumberauthentication/jwt/AuthenticationSteps.java.mustache
  src/main/resources/generator/server/springboot/cucumberauthentication/oauth2/AuthenticationSteps.java.mustache
  src/main/resources/generator/server/springboot/mvc/sample/feature/test/sample/infrastructure/primary/beer/BeersSteps.java.mustache
Labels: area: enhancement :wrench:, theme: tests

#10168 Sonar: Add a nested comment
  src/test/java/tech/jhipster/lite/shared/error/infrastructure/primary/BeanValidationErrorsHandlerTest.java
  src/test/java/tech/jhipster/lite/shared/error_generator/infrastructure/primary/BeanValidationErrorsResource.java
Labels: area: enhancement :wrench:
