Repository seed4j/seed4j, pull requests merged in 2025-09, with the labels that each got.

#13224 Bump NPM to 11.6.0
  CONTRIBUTING.md
  pom.xml
Labels: area: dependencies

#13232 Docker Hub: publish main
  .github/workflows/publish-jvm-docker-image.yml
Labels: area: enhancement :wrench:, generator: internal, theme: docker :whale:

#13238 Fix docker build name for renovate bot
  .github/workflows/publish-jvm-docker-image.yml
Labels: area: enhancement :wrench:, generator: internal

#13239 Upgrade actions dependencies
  src/main/resources/generator/ci/github/actions/.github/workflows/github-actions.yml.mustache
  src/test/resources/com/seed4j/generator/ci/github/actions/domain/GitHubActionsModuleFactoryTest.shouldBuildGitHubActionsGradleModule.github-actions.yml.approved.txt
  src/test/resources/com/seed4j/generator/ci/github/actions/domain/GitHubActionsModuleFactoryTest.shouldBuildGitHubActionsMavenModule.github-actions.yml.approved.txt
  src/test/resources/projects/ci/github-actions-gradle.yml
  src/test/resources/projects/ci/github-actions-maven.yml
Labels: area: dependencies

#13246 Add root folder restriction in forced project configuration
  src/main/java/com/seed4j/shared/projectfolder/domain/ForcedProjectFolder.java
  src/test/java/com/seed4j/shared/projectfolder/domain/ForcedProjectFolderTest.java
Labels: area: bug :bug:, generator: internal

#13265 Sonarcloud: update name
  sonar-project.properties
Labels: area: enhancement :wrench:, generator: CI

#13266 Delete deploy.yml github workflow
  .github/workflows/deploy.yml
Labels: generator: CI, area: remove

#13302 Split history files with ms
  src/main/java/com/seed4j/project/infrastructure/secondary/FileSystemProjectsRepository.java
  src/test/java/com/seed4j/project/infrastructure/secondary/FileSystemProjectsRepositoryTest.java
  src/test/resources/projects/composed-history/20250819203001002-another-test-module.json
Labels: area: enhancement :wrench:, generator: internal

#13320 Bump spring-boot to 3.5.6 (generated apps)
  src/main/resources/generator/dependencies/pom.xml
Labels: area: enhancement :wrench:, server: spring boot, area: dependencies

#13321 CI: try to fix tests-windows
  .github/workflows/github-actions.yml
Labels: area: enhancement :wrench:, generator: CI

#13323 chore: fix ErrorProne warning: "EqualsGetClass: Prefer instanceof to getClass when implementing Object#equals"
  src/main/java/com/seed4j/statistic/infrastructure/secondary/AppliedModuleEntity.java
Labels: generator: internal, area: refactoring

#13330 Bump start-server-and-test to 2.1.2
  package-lock.json
  package.json
Labels: area: dependencies

#13339 Replace start-server-and-test with concurrently and wait-on
  package-lock.json
  package.json
Labels: area: dependencies

#13360 Fix sonar issues
  src/main/webapp/app/module/primary/landscape-minimap/LandscapeMiniMap.component.ts
  src/main/webapp/app/module/primary/landscape-rank-module-filter/LandscapeRankModuleFilter.component.ts
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
  src/main/webapp/app/module/primary/landscape/LandscapeConnector.ts
  src/main/webapp/app/module/primary/modules-patch-loader/ModulesPatchLoader.component.ts
  src/main/webapp/app/shared/optional/domain/Optional.ts
Labels: area: enhancement :wrench:, generator: internal

#13371 ci: build and test with java 25 by default
  .github/actions/setup/action.yml
  .github/workflows/github-actions.yml
Labels: generator: internal, generator: CI, area: dependencies
