Repository seed4j/seed4j, pull requests merged in 2025-07, with the labels that each got.

#12837 Add support for pnpm package manager
  .github/actions/setup/action.yml
  .github/workflows/github-actions.yml
  src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/angular/core/infrastructure/primary/AngularModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/react/core/domain/ReactModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/react/security/jwt/domain/ReactJwtModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/svelte/core/infrastructure/primary/SvelteModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/tikui/domain/TikuiModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/vue/core/infrastructure/primary/VueModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/init/domain/InitModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/init/infrastructure/primary/InitModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/prettier/domain/PrettierModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendJavaBuildToolModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/MavenFrontendPluginExecutions.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/infrastructure/primary/FrontendJavaBuildToolModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/template/domain/ThymeleafTemplateModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/template/infrastructure/primary/ThymeleafTemplateModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/typescript/core/domain/TypescriptModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/typescript/core/infrastructure/primary/TypescriptModuleConfiguration.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
  src/main/java/tech/jhipster/lite/module/domain/nodejs/NodeLazyPackagesInstaller.java
  src/main/java/tech/jhipster/lite/module/domain/nodejs/NodePackageManager.java
  src/main/java/tech/jhipster/lite/module/domain/nodejs/NodePackageName.java
  src/main/java/tech/jhipster/lite/module/domain/nodejs/NodeVersions.java
  src/main/java/tech/jhipster/lite/module/domain/properties/JHipsterModuleProperties.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertiesDefinition.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertyDefinition.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/nodejs/LazyNodePackagesInstaller.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/nodejs/NpmLazyPackagesInstaller.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/ProjectFormatterConfiguration.java
  src/main/java/tech/jhipster/lite/shared/npmdetector/infrastructure/secondary/NodePackageManagerInstallationReader.java
  src/main/java/tech/jhipster/lite/shared/npmdetector/infrastructure/secondary/NodePackageManagerInstallationType.java
  src/main/resources/generator/dependencies/common/package.json
  src/main/resources/generator/dependencies/react/package.json
  src/main/resources/generator/init/README.md.mustache
  src/main/resources/generator/init/package.json.mustache
  src/test/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/react/core/domain/ReactModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/init/domain/InitModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/prettier/domain/PrettierModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendJavaBuildToolModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/template/domain/ThymeleafTemplateModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/typescript/core/domain/TypescriptModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/domain/JHipsterModulesFixture.java
  src/test/java/tech/jhipster/lite/module/domain/nodejs/NodePackageManagerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/nodejs/NoopNodeLazyPackagesInstaller.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/ProjectFormatterConfigurationTest.java
  src/test/resources/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModulesRepositoryTest.shouldApplyModuleToGradleProject.package.json.approved.txt
  src/test/resources/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModulesRepositoryTest.shouldApplyModuleToMavenProject.package.json.approved.txt
  tests-ci/generate.sh
  tests-ci/modulePayload.json
Labels: area: feature request :bulb:, theme: client

#12872 ci: generate apps with nodePackageManager parameter for main branch
  .github/workflows/github-actions.yml
Labels: generator: CI

#12873 feat(liquibase-async): use properties provided by SpringBoot for configuring Liquibase
  src/main/resources/generator/server/springboot/dbmigration/liquibase/main/LiquibaseConfiguration.java.mustache
Labels: area: enhancement :wrench:, server: spring boot, theme: database migration

#12856 Bump Vite to 7.0.0
  package-lock.json
  package.json
Labels: area: dependencies

#12898 Nullish coalescing should be preferred
  src/test/webapp/component/support/Interceptor.ts
Labels: generator: internal, area: refactoring, theme: tests

#12892 Bump vue-tsc to 3.0.1
  package-lock.json
  package.json
Labels: area: dependencies

#12912 Local-Variable Type Inference should be used
  src/main/resources/generator/server/springboot/async/src/AsyncConfiguration.java.mustache
Labels: area: refactoring

#12913 Underscores should be used to make large numbers readable
  src/main/resources/generator/server/javatool/protobuf/test/ProtobufDatesWriterTest.java.mustache
Labels: area: refactoring

#12927 Remove duplicated entry in gitattributes
  .gitattributes
Labels: generator: internal, area: refactoring

#12944 Bump Node to 22.17.1
  CONTRIBUTING.md
  pom.xml
Labels: area: dependencies

#12948 Rename slugs and features releated to SonarQube
  src/main/java/tech/jhipster/lite/generator/server/sonarqube/infrastructure/primary/SonarQubeModuleConfiguration.java
  src/main/java/tech/jhipster/lite/shared/slug/domain/JHLiteFeatureSlug.java
  src/main/java/tech/jhipster/lite/shared/slug/domain/JHLiteModuleSlug.java
  src/test/features/server/sonar.feature
  tests-ci/generate.sh
Labels: area: enhancement :wrench:, generator: internal, area: breaking change

#12778 Rename ToggleButtonExpandableVue to ToggleButtonExpandable
  src/main/webapp/app/module/primary/landscape-rank-module-filter/LandscapeRankModuleFilter.component.ts
  src/main/webapp/app/module/primary/landscape-rank-module-filter/LandscapeRankModuleFilter.html
  src/main/webapp/app/shared/toggle-button-expandable/infrastructure/primary/ToggleButtonExpandable.component.ts
  src/main/webapp/app/shared/toggle-button-expandable/infrastructure/primary/index.ts
  src/test/webapp/unit/shared/toggle-button-expandable/infrastructure/primary/ToggleButtonExpandable.spec.ts
Labels: generator: internal, area: refactoring

#12940 Add sonar-typescript module
  .github/workflows/github-actions.yml
  src/main/java/tech/jhipster/lite/generator/typescript/sonar/application/SonarTypescriptApplicationService.java
  src/main/java/tech/jhipster/lite/generator/typescript/sonar/domain/SonarTypescriptModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/typescript/sonar/infrastructure/primary/SonarTypescriptModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/typescript/sonar/package-info.java
  src/main/java/tech/jhipster/lite/shared/slug/domain/JHLiteModuleSlug.java
  src/main/resources/generator/dependencies/common/package.json
  src/main/resources/generator/init/gitignore
  src/main/resources/generator/typescript/sonar/Dockerfile
  src/main/resources/generator/typescript/sonar/sonar-project.properties.mustache
  src/main/resources/generator/typescript/sonar/sonar.md.mustache
  src/main/resources/generator/typescript/sonar/sonar.yml.mustache
  src/main/resources/generator/typescript/sonar/sonar_generate_token.sh
  src/test/features/sonar-typescript.feature
  src/test/java/tech/jhipster/lite/generator/typescript/sonar/domain/SonarTypescriptModuleFactoryTest.java
  tests-ci/generate.sh
Labels: area: feature request :bulb:, theme: typescript

#12755 Rewrite imports
  src/main/webapp/app/module/domain/Category.ts
  src/main/webapp/app/module/domain/Module.ts
  src/main/webapp/app/module/domain/ModuleParameter.ts
  src/main/webapp/app/module/domain/ModulePropertyDefinition.ts
  src/main/webapp/app/module/domain/ModuleToApply.ts
  src/main/webapp/app/module/domain/Modules.ts
  src/main/webapp/app/module/domain/ModulesRepository.ts
  src/main/webapp/app/module/domain/ModulesToApply.ts
  src/main/webapp/app/module/domain/Preset.ts
  src/main/webapp/app/module/domain/ProjectHistory.ts
  src/main/webapp/app/module/domain/landscape/Landscape.ts
  src/main/webapp/app/module/domain/landscape/LandscapeElement.ts
  src/main/webapp/app/module/domain/landscape/LandscapeElementId.ts
  src/main/webapp/app/module/domain/landscape/LandscapeFeature.ts
  src/main/webapp/app/module/domain/landscape/LandscapeLevel.ts
  src/main/webapp/app/module/domain/landscape/LandscapeModule.ts
  src/main/webapp/app/module/domain/landscape/LandscapeSelectionElement.ts
  src/main/webapp/app/module/domain/landscape/LandscapeSelectionTree.ts
  src/main/webapp/app/module/domain/landscape/LandscapeUnselectionTree.ts
  src/main/webapp/app/module/primary/PropertyValue.ts
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
  src/main/webapp/app/module/primary/module-parameters/ModuleParameters.component.ts
  src/main/webapp/app/module/primary/module-properties-form/ModulePropertiesForm.component.ts
  src/main/webapp/app/module/primary/modules-patch/ComponentModulePatchCategory.ts
  src/main/webapp/app/module/primary/modules-patch/ComponentModulesPatch.ts
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.component.ts
  src/main/webapp/app/module/secondary/LocalStorageModuleParametersRepository.ts
  src/main/webapp/app/module/secondary/LocalWindowThemeRepository.ts
  src/main/webapp/app/module/secondary/RestAppliedModule.ts
  src/main/webapp/app/module/secondary/RestCategory.ts
  src/main/webapp/app/module/secondary/RestLandscape.ts
  src/main/webapp/app/module/secondary/RestLandscapeElement.ts
  src/main/webapp/app/module/secondary/RestLandscapeFeature.ts
  src/main/webapp/app/module/secondary/RestLandscapeLevel.ts
  src/main/webapp/app/module/secondary/RestLandscapeModule.ts
  src/main/webapp/app/module/secondary/RestManagementRepository.ts
  src/main/webapp/app/module/secondary/RestModule.ts
  src/main/webapp/app/module/secondary/RestModulePropertiesDefinitions.ts
  src/main/webapp/app/module/secondary/RestModulePropertyDefinition.ts
  src/main/webapp/app/module/secondary/RestModuleToApply.ts
  src/main/webapp/app/module/secondary/RestModules.ts
  src/main/webapp/app/module/secondary/RestModulesRepository.ts
  src/main/webapp/app/module/secondary/RestModulesToApply.ts
  src/main/webapp/app/module/secondary/RestPreset.ts
  src/main/webapp/app/module/secondary/RestPresetModuleToApply.ts
  src/main/webapp/app/module/secondary/RestPresets.ts
  src/main/webapp/app/module/secondary/RestProjectFoldersRepository.ts
  src/main/webapp/app/module/secondary/RestProjectHistory.ts
  src/main/webapp/app/shared/alert/infrastructure/primary/WindowApplicationListener.ts
Labels: generator: internal, area: refactoring

#12749 Remove unnecessary assertion
  src/test/webapp/unit/shared/http/infrastructure/secondary/AxiosHttp.spec.ts
Labels: generator: internal, area: refactoring, theme: tests, area: needs discussion

#12959 Distribute openrewrite upgrade recipes
  README.md
  src/main/resources/META-INF/rewrite/upgrade.yml
  src/main/resources/META-INF/rewrite/version-1.20.0.yml
  src/main/resources/META-INF/rewrite/version-1.21.0.yml
  src/main/resources/META-INF/rewrite/version-1.33.0.yml
  src/main/resources/META-INF/rewrite/version-1.34.0.yml
Labels: area: feature request :bulb:, generator: internal, $$ bug-bounty $$, $200

#12965 Fix: Streams that encapsulate a closeable resource should be closed
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemProjectFiles.java
Labels: area: enhancement :wrench:, generator: internal

#12971 OpenRewrite: fix recipe related to Sonar
  src/main/resources/META-INF/rewrite/version-1.34.0.yml
Labels: area: enhancement :wrench:, generator: internal

#12972 Bump vue-tsc to 3.0.2
  package-lock.json
  package.json
Labels: generator: internal, area: dependencies

#12973 Bump vue-tsc to 3.0.3
  package-lock.json
  package.json
Labels: generator: internal, area: dependencies

#12982 Bump prettier-plugin-organize-imports and vue-tsc
  package-lock.json
  package.json
  src/main/resources/generator/dependencies/common/package.json
  src/main/resources/generator/dependencies/vue/package.json
Labels: generator: internal, area: dependencies

#12991 Bump spring-boot to 3.5.4
  pom.xml
Labels: server: spring boot, generator: internal, area: dependencies

#12990 Bump NPM to 11.5.1
  CONTRIBUTING.md
  pom.xml
Labels: generator: internal, area: dependencies

#13000 Refacto: vue-pinia in a specific module
  src/main/java/tech/jhipster/lite/generator/client/vue/core/application/VueApplicationService.java
  src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/vue/core/infrastructure/primary/VueModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/vue/pinia/application/VuePiniaApplicationService.java
  src/main/java/tech/jhipster/lite/generator/client/vue/pinia/domain/VuePiniaModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/vue/pinia/infrastructure/primary/VuePiniaModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/client/vue/pinia/package-info.java
  src/test/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/vue/pinia/domain/VuePiniaModuleFactoryTest.java
Labels: area: refactoring, client: vue
