Repository seed4j/seed4j, pull requests merged in 2025-01, with the labels that each got.

#11668 chore(generator): configure Modernizer maven plugin
  pom.xml
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModulesApplyer.java
  src/main/java/tech/jhipster/lite/module/domain/properties/JHipsterProjectFolder.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemGeneratedProjectRepository.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/YamlFileSpringPropertiesHandler.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/git/JGitGitRepository.java
  src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/GradleVersionCatalogDependenciesReader.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectDownloader.java
  src/main/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepository.java
  src/main/java/tech/jhipster/lite/shared/projectfolder/domain/ForcedProjectFolder.java
  src/main/java/tech/jhipster/lite/shared/projectfolder/domain/FreeProjectFolder.java
  src/main/java/tech/jhipster/lite/statistic/infrastructure/secondary/InMemoryStatisticsRepository.java
  src/test/java/tech/jhipster/lite/HexagonalArchTest.java
  src/test/java/tech/jhipster/lite/TestFileUtils.java
  src/test/java/tech/jhipster/lite/cucumber/rest/CucumberRestAssertions.java
  src/test/java/tech/jhipster/lite/cucumber/rest/CucumberRestTestContext.java
  src/test/java/tech/jhipster/lite/module/domain/file/JHipsterFileContentTest.java
  src/test/java/tech/jhipster/lite/module/domain/file/JHipsterSourceTest.java
  src/test/java/tech/jhipster/lite/module/domain/properties/JHipsterPropertyExampleTest.java
  src/test/java/tech/jhipster/lite/module/domain/replacement/JHipsterModuleMandatoryReplacementsTest.java
  src/test/java/tech/jhipster/lite/module/domain/replacement/JHipsterModuleOptionalReplacementsTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/primary/ModulesSteps.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModuleFilesTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemPackageJsonHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemSpringCommentsCommandsHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemSpringFactoriesCommandsHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemSpringPropertiesCommandsHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemStartupCommandsReadmeCommandsHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemYamlSpringCommentsCommandsHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterModulesAssertions.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/PropertiesFileSpringCommentsHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/PropertiesFileSpringFactoriesHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/PropertiesFileSpringPropertiesHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/YamlFileSpringPropertiesHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/git/JGitGitRepositoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/FileSystemMavenDependenciesReaderTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MavenCommandHandlerTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MavenProjectJavaDependenciesRepositoryTest.java
  src/test/java/tech/jhipster/lite/project/infrastructure/primary/ProjectsSteps.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepositoryTest.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/NpmProjectFormatterTest.java
  src/test/java/tech/jhipster/lite/shared/error/infrastructure/primary/AssertionErrorMessagesTest.java
  src/test/java/tech/jhipster/lite/shared/error/infrastructure/primary/GeneratorErrorsMessagesTest.java
  src/test/java/tech/jhipster/lite/shared/projectfolder/domain/ForcedProjectFolderTest.java
Labels: generator: internal, area: refactoring

#11679 feat(logs-spy): logs-spy module should only require spring-boot, not spring-server
  src/main/java/tech/jhipster/lite/generator/server/springboot/logsspy/infrastructure/primary/LogsSpyModuleConfiguration.java
Labels: area: enhancement :wrench:, server: java

#11683 ci: switch back to latest lts for node version
  .github/workflows/github-actions.yml
Labels: generator: CI, area: dependencies

#11676 ci: generate fullapp with both gradle and maven
  .github/workflows/github-actions.yml
  src/main/resources/generator/server/springboot/mvc/sample/liquibase/00000000000_sample_feature_schema.xml
  tests-ci/generate.sh
Labels: generator: internal, generator: CI

#11669 feat(code-quality): new module for modernizer maven/gradle plugin
  src/main/java/tech/jhipster/lite/generator/server/javatool/modernizer/application/ModernizerApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/modernizer/domain/ModernizerModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/modernizer/primary/ModernizerModuleConfiguration.java
  src/main/java/tech/jhipster/lite/shared/slug/domain/JHLiteModuleSlug.java
  src/main/resources/generator/dependencies/build.gradle.kts
  src/main/resources/generator/dependencies/gradle/libs.versions.toml
  src/main/resources/generator/dependencies/pom.xml
  src/main/resources/generator/server/javatool/archunit/test/HexagonalArchTest.java.mustache
  src/main/resources/generator/server/springboot/cucumber/rest/CucumberRestAssertions.java.mustache
  src/main/resources/generator/server/springboot/cucumber/rest/CucumberRestTestContext.java.mustache
  src/main/resources/generator/server/springboot/dbmigration/cassandra/TestCassandraMigrationLoader.java.mustache
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/ApplicationErrorsMessagesTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/AssertionErrorMessagesTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/sample/cassandrapersistence/test/infrastructure/secondary/CassandraBeerCatalogRepositoryIT.java.mustache
  src/main/resources/generator/server/springboot/mvc/sample/cassandrapersistence/test/infrastructure/secondary/CassandraBeerRepositoryIT.java.mustache
  src/main/resources/generator/server/springboot/mvc/sample/jpapersistence/test/infrastructure/secondary/JpaBeersRepositoryIT.java.mustache
  src/main/resources/generator/server/springboot/mvc/sample/mongodbpersistence/test/infrastructure/secondary/MongoDBBeersRepositoryIT.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/authentication/test/infrastructure/primary/JwtReaderTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/account/test/infrastructure/secondary/OAuth2AuthenticationReaderTest.java.mustache
  src/test/features/server/javatool/modernizer.feature
  src/test/java/tech/jhipster/lite/generator/server/javatool/modernizer/domain/ModernizerModuleFactoryTest.java
  tests-ci/generate.sh
Labels: area: feature request :bulb:, server: java

#11661 Fix empty char on commands
  src/main/java/tech/jhipster/lite/module/domain/startupcommand/StartupCommandLine.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/FileSystemStartupCommandsReadmeCommandsHandlerTest.java
Labels: area: enhancement :wrench:

#11686 Angular: angular-builders beta to stable version
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#11691 Bump Node to 22.13.0
  CONTRIBUTING.md
  pom.xml
Labels: area: dependencies

#11692 Clean code
  CONTRIBUTING.md
  documentation/hexagonal-architecture.md
  src/main/resources/generator/init/.lintstagedrc.cjs
  src/main/resources/generator/server/documentation/hexagonal-application-service/hexagonal-application-service-architecture.md
  src/main/resources/generator/server/springboot/dbmigration/cassandra/cassandra-migration.md
  src/test/resources/projects/init/.lintstagedrc.empty.cjs
Labels: area: enhancement :wrench:

#11702 chore(deps): upgrade prettier-java for generator
  package-lock.json
  package.json
  src/main/java/tech/jhipster/lite/project/domain/download/Project.java
Labels: generator: internal, area: dependencies

#11684 Fix: update springdoc-openapi.version to v2.8.0
  pom.xml
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/OpenApiModulesConfiguration.java
  src/main/resources/generator/dependencies/pom.xml
  src/test/java/tech/jhipster/lite/wire/springdoc/infrastructure/primary/SpringDocSteps.java
Labels: area: dependencies, area: needs discussion

#11716 Upgrade Angular
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#11725 Angular 19.1 + Typescript 5.7
  src/main/resources/generator/dependencies/angular/package.json
Labels: area: dependencies, client: angular

#11747 Simplify tests: uses describe.each
  src/test/webapp/unit/router/index.spec.ts
Labels: theme: tests

#11753 Angular: remove unused CommonModule
  src/main/resources/generator/client/angular/admin/src/main/webapp/app/admin/health/health.component.ts.mustache
  src/main/resources/generator/client/angular/core/src/main/webapp/app/app.component.ts.mustache
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/login/login.component.ts.mustache
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/login/login.component.ts.mustache
  src/test/resources/projects/angular/app.component.ts
Labels: area: enhancement :wrench:, client: angular

#11754 Angular: format files with Prettier
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/login/login.component.html.mustache
Labels: area: enhancement :wrench:, client: angular

#11755 Tests: clean code
  src/test/webapp/unit/module/primary/modules-patch/ModulesPatchComponent.spec.ts
Labels: generator: internal, theme: tests

#11765 Use object property shorthand
  src/test/webapp/unit/module/primary/landscape/LandscapeMiniMapComponent.spec.ts
Labels: area: enhancement :wrench:, theme: tests

#11766 Fix update vitest monorepo to v3 (major)
  package-lock.json
  package.json
  src/main/resources/generator/client/react/security/jwt/src/test/webapp/unit/login/primary/loginModal/index.test.tsx.mustache
  src/main/resources/generator/dependencies/common/package.json
Labels: area: dependencies, client: react

#11769 Bump Node to 22.13.1
  CONTRIBUTING.md
  pom.xml
Labels: area: dependencies

#11771 Simplify tests: uses describe.each
  src/main/resources/generator/client/vue/webapp/app/test/webapp/unit/router/infrastructure/primary/HomeRouter.spec.ts.mustache
Labels: client: vue, theme: tests

#11774 Clean code: use nullish coalescing
  src/main/webapp/app/module/secondary/RestModule.ts
Labels: generator: internal, area: refactoring

#11776 Clean code: use Promise.prototype.finally
  src/main/webapp/app/module/primary/project-actions/ProjectActions.component.ts
Labels: generator: internal, area: refactoring

#11777 Spring-boot 3.4.2
  pom.xml
Labels: generator: internal, area: dependencies

#11778 Generated apps: bump to spring-boot 3.4.2
  src/main/resources/generator/dependencies/pom.xml
Labels: area: dependencies

#11779 Clean code: use template literals
  src/main/webapp/app/module/primary/module-parameters/ModuleParameters.component.ts
  src/main/webapp/app/module/primary/modules-patch/ComponentModulePatch.ts
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.component.ts
Labels: generator: internal, area: refactoring

#11780 Rename variables
  src/main/java/tech/jhipster/lite/generator/client/angular/security/oauth2/domain/AngularOauth2ModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/javatool/protobuf/domain/ProtobufModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/account/domain/OAuth2AccountModuleFactory.java
Labels: generator: internal, area: refactoring

#11724 add optional rank at modules domain
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModuleRank.java
  src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModuleResource.java
  src/test/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResourceFixture.java
  src/test/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResourcesTest.java
Labels: area: feature request :bulb:, generator: internal

#11795 Rename variable: ENFORCER_ARTIFACTID=>ENFORCER_ARTIFACT_ID
  src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/MavenModuleFactory.java
Labels: generator: internal, area: refactoring

#11798 Clean code
  src/main/java/tech/jhipster/lite/statistic/infrastructure/secondary/AppliedModulesChangeUnit.java
  src/main/resources/generator/server/springboot/dbmigration/cassandra/README.md
  src/test/java/tech/jhipster/lite/module/domain/replacement/RegexReplacerTest.java
  src/test/webapp/unit/loader/primary/Loader.spec.ts
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/webapp/unit/module/primary/modules-patch/ModulesPatchComponent.spec.ts
Labels: generator: internal, area: refactoring

#11796 New datasource modules for postgresql/mariadb/mysql/mssql
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/datasource/application/DatasourceApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/datasource/domain/DatasourceModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/datasource/domain/DatasourceProperties.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/datasource/infrastructure/primary/DatasourceModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/datasource/package-info.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/jooq/application/JooqApplicationService.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/jooq/domain/CommonModuleBuilder.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/jooq/domain/DatabaseType.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/jooq/domain/JooqModuleCodegenConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/jooq/domain/JooqModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/jooq/infrastructure/primary/JooqModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/jpa/domain/DatabaseType.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/jpa/domain/JpaModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/jpa/domain/SQLCommonModuleBuilder.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/database/jpa/infrastructure/primary/JpaModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/flyway/infrastructure/primary/FlywayModuleConfiguration.java
  src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/infrastructure/primary/LiquibaseModuleConfiguration.java
  src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
  src/main/java/tech/jhipster/lite/module/domain/jooqplugin/DatabaseType.java
  src/main/java/tech/jhipster/lite/module/domain/jooqplugin/JooqModuleCodegenConfiguration.java
  src/main/java/tech/jhipster/lite/shared/slug/domain/JHLiteFeatureSlug.java
  src/main/java/tech/jhipster/lite/shared/slug/domain/JHLiteModuleSlug.java
  src/main/resources/generator/server/springboot/database/datasource/MsSQLTestContainerExtension.java.mustache
  src/main/resources/generator/server/springboot/database/datasource/databaseType.md.mustache
  src/main/resources/generator/server/springboot/database/datasource/docker/container-license-acceptance.txt.mustache
  src/main/resources/generator/server/springboot/database/datasource/docker/mariadb.yml.mustache
  src/main/resources/generator/server/springboot/database/datasource/docker/mssql.yml.mustache
  src/main/resources/generator/server/springboot/database/datasource/docker/mysql.yml.mustache
  src/main/resources/generator/server/springboot/database/datasource/docker/postgresql.yml.mustache
  src/main/resources/generator/server/springboot/database/jpa/DatabaseConfiguration.java.mustache
  src/test/features/server/springboot/database/datasource.feature
  src/test/features/server/springboot/database/jooq-mariadb.feature
  src/test/features/server/springboot/database/jooq-mssql.feature
  src/test/features/server/springboot/database/jooq-mysql.feature
  src/test/features/server/springboot/database/jooq-postgresql.feature
  src/test/features/server/springboot/database/jooq.feature
  src/test/features/server/springboot/database/jpa-mariadb.feature
  src/test/features/server/springboot/database/jpa-mssql.feature
  src/test/features/server/springboot/database/jpa-mysql.feature
  src/test/features/server/springboot/database/jpa-postgresql.feature
  src/test/features/server/springboot/database/jpa.feature
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/datasource/domain/DatasourceModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/jooq/domain/JooqModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/database/jpa/domain/JpaModuleFactoryTest.java
  tests-ci/generate.sh
Labels: area: feature request :bulb:, theme: database, theme: database migration

#11797 Font property font-family does not have generic default
  src/main/glyph/css/jhlite-icons-embedded.css
  src/main/glyph/css/jhlite-icons-ie7.css
  src/main/glyph/css/jhlite-icons.css
Labels: area: enhancement :wrench:, generator: internal

#11189 fix: allow applying other front module after vitest config being formatted with prettier
  src/main/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactory.java
  src/main/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactory.java
  src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactory.java
  src/main/java/tech/jhipster/lite/generator/typescript/common/domain/EslintShortcuts.java
  src/main/java/tech/jhipster/lite/generator/typescript/common/domain/TsConfigShortcuts.java
  src/main/java/tech/jhipster/lite/generator/typescript/common/domain/VitestShortcuts.java
  src/main/java/tech/jhipster/lite/generator/typescript/common/package-info.java
  src/main/resources/generator/typescript/vitest.config.ts.mustache
  src/test/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.java
  src/test/resources/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.shouldBuildModuleWithStyle.vitest.config.ts.approved.txt
  src/test/resources/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.shouldCreateVueModule.eslint.config.js.approved.txt
  src/test/resources/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.shouldCreateVueModule.vitest.config.ts.approved.txt
Labels: area: bug :bug:, theme: client

#11799 Tests: some refacto
  src/main/resources/generator/client/angular/admin/src/main/webapp/app/admin/health/health.component.spec.ts.mustache
  src/main/resources/generator/client/angular/admin/src/main/webapp/app/admin/health/modal/health-modal.component.spec.ts.mustache
  src/main/resources/generator/client/angular/admin/src/main/webapp/app/config/application-config.service.spec.ts.mustache
  src/main/resources/generator/client/angular/core/src/main/webapp/app/app.component.spec.ts.mustache
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/login/login.component.spec.ts.mustache
  src/main/resources/generator/client/angular/security/oauth2/src/main/webapp/app/auth/http-auth.interceptor.spec.ts.mustache
  src/main/resources/generator/client/common/i18n/i18n.spec.ts
  src/main/resources/generator/client/react/security/jwt/src/test/webapp/unit/login/primary/loginForm/index.test.tsx.mustache
  src/main/resources/generator/client/react/security/jwt/src/test/webapp/unit/login/primary/loginModal/index.test.tsx.mustache
  src/test/resources/projects/angular/app.component.spec.ts
  src/test/webapp/unit/common/primary/timeout/Timeout.spec.ts
  src/test/webapp/unit/common/primary/toast/Toast.spec.ts
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/webapp/unit/module/primary/landscape/LandscapeConnector.spec.ts
  src/test/webapp/unit/module/primary/landscape/LandscapeMiniMapComponent.spec.ts
  src/test/webapp/unit/module/primary/landscape/LandscapeScroller.spec.ts
  src/test/webapp/unit/module/primary/modules-patch/ModulesPatchComponent.spec.ts
  src/test/webapp/unit/module/secondary/RestProjectFoldersRepository.spec.ts
  src/test/webapp/unit/shared/alert/infrastructure/primary/WindowApplicationListener.spec.ts
  src/test/webapp/unit/shared/alert/infrastructure/secondary/MittAlertBus.spec.ts
  src/test/webapp/unit/shared/alert/infrastructure/secondary/MittAlertListener.spec.ts
  src/test/webapp/unit/shared/logger/infrastructure/secondary/ConsoleLogger.spec.ts
Labels: area: refactoring, theme: tests

#11814 implement rank mapper and rest dto
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscape.java
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeLevels.java
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeModule.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterLandscapeModule.java
  src/test/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeFixture.java
  src/test/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterLandscapeTest.java
Labels: area: feature request :bulb:, generator: internal

#11816 Sonar: Remove this unused method parameter properties
  src/main/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactory.java
Labels: area: bug :bug:

#11818 rename builder interface from JHipsterLandscapeModuleDependenciesBuilder to JHipsterLandscapeModuleOptionalBuilder
  src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscapeModule.java
Labels: area: feature request :bulb:, generator: internal

#11823 Bump NPM to 11.1.0
  CONTRIBUTING.md
  pom.xml
Labels: generator: internal, area: dependencies

#11827 Convert some functions to arrow functions
  src/main/webapp/app/module/primary/PropertyValue.ts
  src/main/webapp/app/module/primary/project-actions/ProjectActions.component.ts
  src/test/webapp/unit/module/domain/Modules.fixture.ts
  src/test/webapp/unit/module/domain/landscape/Landscape.fixture.ts
Labels: generator: internal, area: refactoring

#11832 Release script without clean
  .gitignore
  release.sh
Labels: area: enhancement :wrench:, generator: internal

#11833 build(generator): correctly handle mvn verify -DskipTests
  pom.xml
Labels: area: enhancement :wrench:, generator: internal, theme: tests

#11835 Add eslint-plugin-cypress to the ESLint config
  eslint.config.js
Labels: area: feature request :bulb:, generator: internal, theme: tests
