Repository seed4j/seed4j, pull requests merged in 2025-02, with the labels that each got.

#11846 Repo org updated @nextui-org to @heroui
  src/main/java/tech/jhipster/lite/generator/client/react/security/jwt/domain/ReactJwtModuleFactory.java
  src/main/resources/generator/client/react/security/jwt/src/main/webapp/app/login/primary/loginForm/index.tsx.mustache
  src/main/resources/generator/client/react/security/jwt/src/main/webapp/app/login/primary/loginModal/index.tsx.mustache
  src/main/resources/generator/client/react/security/jwt/tailwind.config.js
  src/main/resources/generator/dependencies/react/package.json
  src/test/java/tech/jhipster/lite/generator/client/react/security/jwt/domain/ReactJwtModuleFactoryTest.java
Labels: area: dependencies, client: react

#11848 Refacto getMediaPreference function
  src/main/webapp/app/module/secondary/GetMediaPreference.ts
Labels: generator: internal, area: refactoring

#11847 React: remove unused dependency (ts-node)
  src/main/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactory.java
  src/main/resources/generator/dependencies/react/package.json
  src/test/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.java
Labels: area: dependencies, client: react

#11852 Refacto: implicit return
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
Labels: generator: internal, area: refactoring

#11853 Refacto: arrow function and implicit return
  src/main/webapp/app/module/primary/landscape/LandscapeNavigation.ts
Labels: generator: internal, area: refactoring

#11854 Refacto: apply nullish coalescing
  src/main/webapp/app/module/secondary/LocalStorageModuleParametersRepository.ts
Labels: generator: internal, area: refactoring

#11858 Refacto: Typescript - Methods are public by default
  src/main/webapp/app/module/domain/landscape/Landscape.ts
  src/main/webapp/app/module/domain/landscape/LandscapeFeature.ts
  src/main/webapp/app/module/domain/landscape/LandscapeFeatureSlug.ts
  src/main/webapp/app/module/domain/landscape/LandscapeModule.ts
  src/main/webapp/app/module/domain/landscape/LandscapeSelectionTree.ts
  src/main/webapp/app/module/domain/landscape/LandscapeUnselectionTree.ts
Labels: generator: internal, area: refactoring

#11862 Refacto: Typescript - Methods are public by default
  src/main/resources/generator/typescript/webapp/common/domain/optional/Optional.ts
  src/main/webapp/app/module/domain/ModuleSlug.ts
  src/main/webapp/app/module/domain/Modules.ts
  src/main/webapp/app/module/primary/modules-patch/ComponentModulePatch.ts
  src/main/webapp/app/module/primary/modules-patch/ComponentModulePatchCategory.ts
  src/main/webapp/app/module/primary/modules-patch/ComponentModulesPatch.ts
  src/main/webapp/app/shared/loader/infrastructure/primary/Loader.ts
  src/main/webapp/app/shared/optional/domain/Optional.ts
Labels: generator: internal, area: refactoring

#11863 Fix update to vitest 3.0.5
  package-lock.json
  package.json
  src/main/resources/generator/dependencies/common/package.json
Labels: area: dependencies

#11864 Some refacto
  src/main/webapp/app/module/domain/landscape/Landscape.ts
  src/main/webapp/app/module/domain/landscape/LandscapeFeature.ts
  src/main/webapp/app/module/domain/landscape/LandscapeSelectionTree.ts
  src/main/webapp/app/module/primary/landscape/LandscapeConnector.ts
  src/main/webapp/app/module/primary/landscape/LandscapeNavigation.ts
  src/main/webapp/app/module/primary/modules-patch/ComponentModulesPatch.ts
Labels: generator: internal, area: refactoring

#11836 test(generator): allow loading module files from classpath
  .prettierignore
  src/test/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/react/core/domain/ReactCoreModulesFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/client/vue/core/domain/VueModulesFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/prettier/domain/PrettierModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/generator/server/javatool/protobuf/domain/ProtobufModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterModulesAssertions.java
  src/test/resources/projects/init/.lintstagedrc.empty.cjs
  src/test/resources/projects/init/.lintstagedrc.withPrettierModuleApplied.cjs
  src/test/resources/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModulesRepositoryTest.shouldApplyModuleToGradleProject.build.gradle.kts.approved.txt
  src/test/resources/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModulesRepositoryTest.shouldApplyModuleToGradleProject.package.json.approved.txt
  src/test/resources/tech/jhipster/lite/module/infrastructure/secondary/FileSystemJHipsterModulesRepositoryTest.shouldApplyModuleToMavenProject.package.json.approved.txt
Labels: generator: internal, theme: tests

#11867 Some refacto
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.component.ts
Labels: generator: internal, area: refactoring

#11866 use typed translation on react i18next on each context
  src/main/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactory.java
  src/main/resources/generator/client/common/i18n/i18n.spec.ts
  src/main/resources/generator/client/common/i18n/i18n.ts
  src/test/features/client/react-i18n.feature
  src/test/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactoryTest.java
  src/test/resources/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactoryTest.shouldBuildI18nModule.HomePage.tsx.approved.txt
Labels: area: feature request :bulb:, client: react

#11872 improve regex to patch react i18n files to be more flexible
  src/main/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactory.java
  src/test/resources/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactoryTest.shouldBuildI18nModule.HomePage.tsx.approved.txt
Labels: area: enhancement :wrench:, client: react

#11873 Refacto: function to arrow function
  src/main/webapp/app/module/secondary/RestAppliedModule.ts
Labels: generator: internal, area: refactoring

#11874 ESLint: add sort-imports
  eslint.config.js
  src/main/webapp/app/module/primary/landscape-minimap/LandscapeMiniMap.component.ts
  src/main/webapp/app/module/primary/landscape-module/LandscapeModule.component.ts
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
  src/main/webapp/app/module/primary/module-parameters/ModuleParameters.component.ts
  src/main/webapp/app/module/primary/module-properties-form/ModulePropertiesForm.component.ts
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.component.ts
  src/main/webapp/app/module/secondary/LocalWindowThemeRepository.ts
  src/main/webapp/app/module/secondary/RestModulesRepository.ts
  src/main/webapp/app/module/secondary/RestPreset.ts
  src/main/webapp/app/module/secondary/RestPresets.ts
  src/main/webapp/app/module/secondary/RestProjectHistory.ts
  src/main/webapp/app/shared/toast/infrastructure/primary/Toast.component.ts
  src/test/webapp/unit/common/primary/header/Header.spec.ts
  src/test/webapp/unit/common/primary/timeout/Timeout.fixture.ts
  src/test/webapp/unit/common/primary/toast/Toast.spec.ts
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/webapp/unit/module/primary/landscape/LandscapePresetConfigurationComponent.spec.ts
  src/test/webapp/unit/module/primary/modules-patch/ModulesPatchComponent.spec.ts
  src/test/webapp/unit/module/primary/project-actions/ProjectActionsComponent.spec.ts
  src/test/webapp/unit/module/secondary/RestModulesRepository.spec.ts
  src/test/webapp/unit/root/infrastructure/primary/App.spec.ts
  src/test/webapp/unit/router/index.spec.ts
Labels: area: enhancement :wrench:, generator: internal

#11876 Display invalid project folder in logs
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/InvalidProjectFolderException.java
  src/main/java/tech/jhipster/lite/module/infrastructure/primary/RestJHipsterModuleProperties.java
  src/test/java/tech/jhipster/lite/module/infrastructure/primary/InvalidProjectFolderExceptionTest.java
Labels: area: enhancement :wrench:, generator: internal

#11878 Sonar: remove platform in docker-compose
  src/main/docker/sonar.yml
Labels: generator: internal, theme: docker :whale:, area: needs discussion

#11885 chore(deps): upgrade to prettier 3.5 on jhipster-lite engine and enable experimentalOperatorPosition at start of line
  .prettierrc
  package-lock.json
  package.json
  src/main/webapp/app/module/domain/landscape/Landscape.ts
  src/main/webapp/app/module/primary/landscape/Landscape.component.ts
  src/main/webapp/app/module/primary/modules-patch/ModulesPatch.component.ts
  src/test/resources/projects/react-app/index.css
Labels: area: enhancement :wrench:, generator: internal, area: dependencies

#11889 Sonar: remove platform in docker-compose
  src/main/resources/generator/server/sonar/sonar.yml.mustache
Labels: area: enhancement :wrench:, area: refactoring, theme: docker :whale:

#11886 chore(deps): upgrade generated apps to use prettier 3.5 and enable experimentalOperatorPosition at start of line
  src/main/resources/generator/dependencies/common/package.json
  src/main/resources/generator/prettier/.prettierrc.mustache
Labels: area: enhancement :wrench:, area: dependencies

#11890 Bump Node to 22.14.0
  CONTRIBUTING.md
  pom.xml
Labels: generator: internal, area: dependencies

#11899 feat(liquibase): configure a default dedicated liquibase context for tests
  src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseModuleFactory.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseModuleFactoryTest.java
Labels: area: enhancement :wrench:, theme: database migration, theme: tests

#11897 feat(logs-spy): improved version of LogsSpy that better handle concurrent modifications
  src/main/resources/generator/server/springboot/logsspy/test/LogsSpy.java.mustache
Labels: area: enhancement :wrench:, theme: tests

#11837 Add eslint-plugin-cypress to the ESLint config (for apps)
  src/main/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactory.java
  src/main/resources/generator/client/angular/core/eslint.config.mjs.mustache
  src/test/java/tech/jhipster/lite/generator/client/tools/cypress/domain/CypressModuleFactoryTest.java
Labels: area: feature request :bulb:

#11900 Vitest: describe.each => describe.for
  src/main/resources/generator/client/vue/webapp/app/test/webapp/unit/router/infrastructure/primary/HomeRouter.spec.ts.mustache
  src/test/webapp/unit/router/index.spec.ts
Labels: area: enhancement :wrench:, generator: internal, theme: tests

#11902 gitignore: remove file that does not exist on the project
  .gitignore
Labels: generator: internal, area: refactoring

#11903 Clean code
  documentation/hexagonal-architecture.md
  src/main/resources/generator/client/vue/security/oauth2_keycloak/webapp/app/test/webapp/unit/auth/infrastructure/secondary/KeycloakAuthRepository.spec.ts.mustache
  src/main/resources/generator/server/javatool/base/main/assertions.md.mustache
  src/main/resources/generator/server/sonar/sonar.md.mustache
Labels: generator: internal, area: refactoring

#11919 Vue: Upgrade Pinia 3
  src/main/resources/generator/dependencies/vue/package.json
Labels: area: dependencies, client: vue

#11911 Rename some tests
  src/main/java/tech/jhipster/lite/generator/client/react/i18n/domain/ReactI18nModuleFactory.java
  src/main/resources/generator/client/common/i18n/i18n.spec.ts
  src/main/resources/generator/client/react/core/src/test/webapp/unit/home/infrastructure/primary/HomePage.spec.tsx.mustache
  src/main/resources/generator/client/react/security/jwt/src/test/webapp/unit/login/primary/loginForm/index.test.tsx.mustache
  src/main/resources/generator/client/react/security/jwt/src/test/webapp/unit/login/primary/loginModal/index.test.tsx.mustache
  src/test/resources/projects/react-app/HomePage.spec.tsx
Labels: area: enhancement :wrench:, generator: internal, area: refactoring, theme: tests

#11929 Angular: use self closing tag
  src/main/resources/generator/client/angular/core/src/main/webapp/app/app.component.html.mustache
  src/test/resources/projects/angular/app.component.html
Labels: area: enhancement :wrench:, area: refactoring, client: angular

#11936 Rename angularapp to angularjwtapp
  .github/workflows/github-actions.yml
  CONTRIBUTING.md
  tests-ci/generate.sh
Labels: generator: internal, area: refactoring, client: angular

#11945 Sonar: Remove this public modifier
  src/main/resources/generator/server/springboot/broker/kafka/KafkaPropertiesTest.java.mustache
  src/main/resources/generator/server/springboot/broker/kafka/SampleConsumerTest.java.mustache
  src/main/resources/generator/server/springboot/broker/kafka/SampleProducerTest.java.mustache
  src/main/resources/generator/server/springboot/springcloud/gateway/java/test/GatewayResourceIT.java.mustache
Labels: area: enhancement :wrench:

#11949 Bump Spring-boot to 3.4.3
  pom.xml
Labels: generator: internal, area: dependencies

#11950 Bump Spring-boot to 3.4.3 (apps)
  src/main/resources/generator/dependencies/pom.xml
Labels: area: enhancement :wrench:, area: dependencies

#11970 Sonar: reactivate circular dependencies rules
  sonar-project.properties
Labels: generator: internal, area: refactoring

#11971 Revert "Sonar: reactivate circular dependencies rules"
  sonar-project.properties
Labels: generator: internal, area: refactoring

#11952 Reduce logs on npm test
  src/test/webapp/unit/module/primary/landscape/LandscapeComponent.spec.ts
  src/test/webapp/unit/module/primary/landscape/LandscapePresetConfigurationComponent.spec.ts
  src/test/webapp/unit/module/primary/modules-patch/ModulesPatchComponent.spec.ts
Labels: generator: internal, area: refactoring, theme: tests

#11980 Fix possibility to commit *.json.mustache files
  .lintstagedrc.js
Labels: area: bug :bug:, generator: internal

#11982 Angular/Lint: ignore .angular folder
  src/main/resources/generator/client/angular/core/eslint.config.mjs.mustache
Labels: area: enhancement :wrench:, client: angular

#11983 Sonar: Local-Variable Type Inference should be used
  src/main/java/tech/jhipster/lite/shared/error/infrastructure/primary/AssertionErrorsHandler.java
  src/main/java/tech/jhipster/lite/shared/error/infrastructure/primary/BeanValidationErrorsHandler.java
  src/main/java/tech/jhipster/lite/shared/error/infrastructure/primary/GeneratorErrorsHandler.java
  src/main/java/tech/jhipster/lite/wire/security/infrastructure/primary/CorsFilterConfiguration.java
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/main/ApplicationErrorsHandler.java.mustache
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/main/AssertionErrorsHandler.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/common/main/infrastructure/primary/AuthenticationExceptionAdvice.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/authentication/main/infrastructure/primary/JwtReader.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/basic-auth/main/infrastructure/primary/AuthenticationResource.java.mustache
  src/main/resources/generator/server/springboot/mvc/web/main/BeanValidationErrorsHandler.java.mustache
  src/main/resources/generator/server/springboot/mvc/web/main/cors/CorsFilterConfiguration.java.mustache
Labels: area: enhancement :wrench:, generator: internal, area: refactoring

#11990 Sonar: Local-Variable Type Inference should be used
  src/main/java/tech/jhipster/lite/shared/error/infrastructure/primary/ArgumentsReplacer.java
  src/main/java/tech/jhipster/lite/shared/error/infrastructure/primary/AssertionErrorsConfiguration.java
  src/main/java/tech/jhipster/lite/shared/error/infrastructure/primary/GeneratorErrorsConfiguration.java
  src/main/resources/generator/server/springboot/dbmigration/liquibase/main/AsyncSpringLiquibase.java.mustache
  src/main/resources/generator/server/springboot/dbmigration/liquibase/test/SpringLiquibaseUtilTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/main/ApplicationErrorsConfiguration.java.mustache
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/main/ArgumentsReplacer.java.mustache
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/main/AssertionErrorsConfiguration.java.mustache
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/ApplicationErrorsMessagesTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/AssertionErrorMessagesTest.java.mustache
  src/test/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/shared/error/infrastructure/primary/AssertionErrorMessagesTest.java
  src/test/java/tech/jhipster/lite/shared/error/infrastructure/primary/GeneratorErrorsMessagesTest.java
Labels: area: enhancement :wrench:, generator: internal, area: refactoring

#11995 Sonar: Local-Variable Type Inference should be used
  src/main/resources/generator/server/springboot/cucumber/rest/CucumberRestTemplate.java.mustache
  src/main/resources/generator/server/springboot/cucumber/rest/CucumberRestTestContext.java.mustache
  src/main/resources/generator/server/springboot/cucumber/rest/ElementAssertions.java.mustache
  src/main/resources/generator/server/springboot/cucumberauthentication/jwt/AuthenticationSteps.java.mustache
  src/main/resources/generator/server/springboot/cucumberauthentication/oauth2/AuthenticationSteps.java.mustache
  src/main/resources/generator/server/springboot/dbmigration/liquibase/test/AsyncSpringLiquibaseTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/authentication/test/application/AuthenticatedUserTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/main/infrastructure/primary/CustomClaimConverter.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/test/application/AuthenticatedUserTest.java.mustache
  src/main/resources/generator/server/springboot/webflux/web/main/HeaderUtil.java.mustache
  src/test/java/tech/jhipster/lite/cucumber/rest/CucumberRestTestContext.java
  src/test/java/tech/jhipster/lite/cucumber/rest/ElementAssertions.java
  src/test/java/tech/jhipster/lite/module/infrastructure/primary/ModulesSteps.java
  src/test/java/tech/jhipster/lite/project/infrastructure/primary/ProjectsSteps.java
Labels: area: enhancement :wrench:, generator: internal, area: refactoring

#12000 Angular 19.2
  src/main/java/tech/jhipster/lite/generator/client/angular/security/oauth2/domain/AngularOauth2ModuleFactory.java
  src/main/resources/generator/client/angular/security/jwt/src/main/webapp/app/login/login.component.html.mustache
  src/main/resources/generator/dependencies/angular/package.json
  src/test/java/tech/jhipster/lite/generator/client/angular/security/oauth2/domain/AngularOauth2ModuleFactoryTest.java
Labels: area: enhancement :wrench:, area: dependencies, client: angular

#12001 Sonar: Local-Variable Type Inference should be used
  src/main/java/tech/jhipster/lite/wire/gitinfo/infrastructure/primary/GitInfoConfiguration.java
  src/main/resources/generator/server/javatool/archunit/test/HexagonalArchTest.java.mustache
  src/main/resources/generator/server/javatool/memoizers/test/MemoizersTest.java.mustache
  src/main/resources/generator/server/javatool/protobuf/test/ProtobufDatesReaderTest.java.mustache
  src/main/resources/generator/server/springboot/dbmigration/liquibase/main/SpringLiquibaseUtil.java.mustache
  src/main/resources/generator/server/springboot/dbmigration/liquibase/test/SpringLiquibaseUtilTest.java.mustache
  src/main/resources/generator/server/springboot/logging/logstash/main/LogstashTcpLifeCycle.java.mustache
  src/main/resources/generator/server/springboot/logging/logstash/test/LogstashTcpLifeCycleTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/ApplicationExceptionTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/authentication/test/application/AuthenticatedUserTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/jwt/authentication/test/infrastructure/primary/JWTFilterTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/kipe/authorization/test/ApplicationAuthorizationsTest.java.mustache
  src/main/resources/generator/server/springboot/mvc/security/oauth2/core/test/application/AuthenticatedUserTest.java.mustache
  src/main/resources/generator/server/springboot/technicaltools/gitinfo/main/GitInfoConfiguration.java.mustache
  src/test/java/tech/jhipster/lite/HexagonalArchTest.java
  src/test/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseModuleFactoryTest.java
  src/test/java/tech/jhipster/lite/module/domain/replacement/MandatoryReplacementExceptionTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/git/GitCommitExceptionTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/git/GitInitExceptionTest.java
  src/test/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/maven/MalformedAdditionalInformationExceptionTest.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/ProjectFormattingExceptionTest.java
  src/test/java/tech/jhipster/lite/project/infrastructure/secondary/ProjectZippingExceptionTest.java
  src/test/java/tech/jhipster/lite/shared/error/domain/GeneratorExceptionTest.java
  src/test/java/tech/jhipster/lite/shared/memoizer/domain/MemoizersTest.java
Labels: area: enhancement :wrench:, generator: internal, area: refactoring
